### ISSUE TITLE
Callback function to QB.chat.send

### ISSUE THREAD

**Issue by jpascal** [QuickBlox/quickblox-javascript-sdk#10]
I need callback here:
```javascript
QB.chat.send(to, message, function(message_with_id){
  // and load message by message.id
});
```

**Comment by alexbassy** [comment]
Why do you need the callback? You can set the ID yourself in the message parameter. Please give more details.

**Comment by jpascal** [comment]
Yes, offcouce

**Comment by jpascal** [comment]
Yes, I can set ID. It's working. But I want be informed about complete sending message to server by callback function. 

Example
```javascript
$('#text').prop('disabled', true);
QB.chat.send(to, message, function(error, message){
  if(!error) {
    $('#text').val('');
    $('#messages').append('<p>'+message.body+'</p>');
    $('#text').focus();
  } else {
    console.log(error);
    alert('Message not sent. Try later.');
  }
  $('#text').prop('disabled', false);
});
```

**Comment by alexbassy** [comment]
Got it - will check with Igor to see if this is possible. As far as I know, it's fire-and-forget...

This can however be done with group chat messages, as you receive all messages (including sent), so a listener can be assigned.

**Comment by jpascal** [comment]
Other functions have callbacks but send function has not. Not good)
I'm waiting response from you.

**Comment by jpascal** [comment]
@alexbassy, this is possible or not?

**Comment by soulfly** [comment]
It's possible with iOS right now only
Android will support this soon
After this we will add this for web

http://quickblox.com/blog/quickblox-releases-ios-sdk-2-2-with-new-chat-api-stream-management-android-sdk-2-1-1-ios-webrtc-sdk-1-0-2/

**Comment by ManojSolanki** [comment]
Hi, please let us know if you added the callback function for web?
