### ISSUE TITLE
undefined `this.socket` when sending message.

### ISSUE THREAD

**Issue by tonchis** [QuickBlox/quickblox-javascript-sdk#103]
Hello Quickblox people! I'm trying out the SDK to build a simple chat (very much like the example one in this repository) and I'm running with an issue when calling `QB.chat.send`. Below is my code.

```
  var message = {
    type: "chat",
    body: text,
    extension: {
      save_to_history: 1,
    },
    senderId: Buyer.id,
    markable: 1
  };

  QB.chat.send(Operator.id, message);
```

Both `Buyer` and `Operator` are existing Quickblox users. The JS error I get is the following:

![screen shot 2016-01-25 at 18 09 54](https://cloud.githubusercontent.com/assets/106882/12564610/eeb3c69e-c38e-11e5-9fa8-1a7f014b4f0d.png)

This code seems to come from the `stophe.js` dependency. I think so because some code in that lib seems to match the `_onIdle:` right there, but that's all I can get from `grep`ping around.

I'm on Safari, and had this problem with versions `2.0.2` and `2.0.3` of the SDK. Maybe (or probably) this isn't a bug and there's something I'm doing wrong.

Thanks in advance!

**Comment by dimaspirit** [comment]
Hi, are you sure that you created session and connected to chat by `QB.chat.connect(param, callback)` ?
You could see tutorial - http://quickblox.com/developers/Web_XMPP_Chat_Sample#Login_to_Chat
or get more info / code of your app for deleted help.

**Comment by tonchis** [comment]
@dimaspirit ahá! I didn't find that guide the first time. I was missing a `QB.chat.connect` that was it. Before we close, one question about that.

I see that in the example the session is created with the user. In my use case I first create a session, then create a user and log in with it. What would be the best time to call `QB.chat.connect`? before or after creating the `chat.dialog`?

**Comment by dimaspirit** [comment]
In first you call `QB.chat.connect`, then you use others methods.
In this methods set handlers - https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/js/modules/qbChat.js#L309

Is it clear?

**Comment by tonchis** [comment]
@dimaspirit ahhh! yes. Thank you for the help. I'll close now :)
