### ISSUE TITLE
XSS attack

### ISSUE THREAD

**Issue by n8m** [QuickBlox/quickblox-javascript-sdk#110]
If I pass some XSS strings to text chat - it will break dialogs list in admin section on quickblox website. Since js can't parse message with xss string it's displaying empty screen on 'chat' page on admin. It can also break something else

**Comment by Vladlukhanin** [comment]
Thanks for the information, we will correct this problem

**Comment by Vladlukhanin** [comment]
This problem has been fixed in our backend, but will be applied after the next release of REST API.
