### ISSUE TITLE
Private messages when using the SDK doesn't fire the eventListener or don't save to history/created dialog.

### ISSUE THREAD

**Issue by byronrode** [QuickBlox/quickblox-javascript-sdk#111]
Guys, I have spent the last 2 days working non-stop on this, and between your documentation, issues here on GH or tagged questions on SO, I haven't been able to get anywhere. Firstly, your main documentation is behind some of your recommendations on SO. That said here is a problem that I really hope you can help resolve.

if I create private chat by first creating a dialog:
##### Step 1

``` javascript
var params = {
    type: 3,
    occupants_ids: [$scope.recipient.qb_userid, $scope.sender.qb_userid],
};

QB.chat.dialog.create(params, function(err, createdDialog) {
    if (err) {
        console.log(err);
    } else {
        $scope.dialog_id = createdDialog._id;
        $scope.messages[$scope.dialog_id] = {};
    }
});
```

Then creating a chat:
##### Step 2

``` javascript
var message_object = {
    type: 'chat',
    senderId: $scope.sender.qb_userid,
    body: $scope.data.message,
    extension: {
        save_to_history: 1,
    },
    send_to_chat: 1,
};

opponentId = QB.chat.helpers.getRecipientId([$scope.recipient.qb_userid, $scope.sender.qb_userid], $scope.dialog_id);
QB.chat.send(opponentId, message_object);
QB.chat.onMessageListener = $scope.onMessageSend;
```

The message appears to send correctly to QB, and the `onMessageListener` is called but the chat message itself is never attached to the created dialog in step 1. If I log in to the admin, the dialog is created, but there are no attached messages. The message object returned in the listener also shows `dialog_id = null`.

I tried adding `dialog_id`, `dialogId`, `chat_dialog_id` and various other ways of typing it out to the message object, but no matter what I have tried, using the method above, never stores a message. We use `$localStorage` to keep the message dialogs on the device for faster processing, but if we reset the user or re-install the app, the messages are then gone. Not good. Also, if we notify the user that they have a message (we don't use the QB Push service) the user cannot see any updates to his messages, but is notified of it (through the listener). This means we cannot correctly create new messages or update existing dialog streams because the saved dialog from step 1 never has any message data stored in it.

An alternative approach that I tried which somewhat works, but doesn't fire the onMessageListener (so we cannot get access to the `dialog_id`, post a notification or make other changes to the app) is to not create a dialog at all, and just initiate a chat (please note that specifying **just** the actual QB user id not the Jid has absolutely no effect).

``` javascript
var message_object = {
    type: 'chat',
    senderId: $scope.sender.qb_userid,
    body: $scope.data.message,
    extension: {
        save_to_history: 1,
    },
    send_to_chat: 1,
};

QB.chat.send(QB.chat.helpers.getUserJid($scope.recipient.qb_userid), message_object);
QB.chat.onMessageListener = $scope.onMessageSend;
```

The problem with the above is that we cannot update localStorage and objects, because they rely on the dialog ID as key, and we don't know what it is, without having to manually do a second call to get all the dialogs, and then filter those dialogs based on the occupant ID's. This is neither efficient, nor is it what your documentation says it should do.

Is there an issue with the JavaScript SDK, in which case should we then use the REST API, and if we do, how do we call the messageSendListener (or do we need to rely on promises using $http) to handle this?

**Comment by Vladlukhanin** [comment]
We reproduced this actions and, in any case, we can get `dialog_id` from received message object. Please provide us with a response from the creation of the dialog and object of the received message so that we could explore further your problem.
Also, we need to know your version of the JS SDK.

**Comment by byronrode** [comment]
Here you go. Please see comments in code below. We are using version 2.0.4 of the SDK and have as a workaround in the meantime, started sending messages using the REST API, but would really like to get the listener and chat working properly so that we can listen for incoming messages.

``` javascript
var params = {
    type: 3,
    occupants_ids: [$scope.recipient.qb_userid, $scope.sender.qb_userid],
};

QB.chat.dialog.create(params, function(err, createdDialog) {
    if (err) {
        console.log(err);
    } else {
        console.log(JSON.stringify(createdDialog));
        $scope.dialog_id = createdDialog._id;
        $scope.messages[$scope.dialog_id] = {};
    }
});
```

``` javascript
{
    "_id": "56bc9196a28f9a79c4000692",
    "created_at": "2016-02-11T13:50:14Z",
    "last_message": null,
    "last_message_date_sent": null,
    "last_message_user_id": null,
    "name": "byronrode",
    "occupants_ids": [
        8879389,
        8879498
    ],
    "photo": null,
    "silent_ids": [

    ],
    "type": 3,
    "updated_at": "2016-02-11T13:50:14Z",
    "user_id": 8879498,
    "xmpp_room_jid": null,
    "unread_messages_count": null
}
```

``` javascript
var message_object = {
    type: 'chat',
    senderId: $scope.sender.qb_userid,
    body: 'Dummy message text',
    extension: {
        save_to_history: 1,
    },
    send_to_chat: 1,
};

QB.chat.send(QB.chat.helpers.getUserJid($scope.recipient.qb_userid), message_object);
QB.chat.onMessageListener = $scope.onMessageSend; 

// Message is delivered to dialog but the listener **doesn't** fire.
```

``` javascript

// If I change the opponentId
opponentId = QB.chat.helpers.getRecipientId([$scope.recipient.qb_userid, $scope.sender.qb_userid], $scope.dialog_id);
QB.chat.send(opponentId, message_object);
QB.chat.onMessageListener = $scope.onMessageSend;

// Then the listener fires, but the message is not saved. Output below

{
    "id": "56bc95be11dcb912af000000",
    "dialog_id": null,
    "type": "chat",
    "body": "Hello",
    "extension": {
        "save_to_history": "1"
    },
    "delay": null
}
```

**Comment by Vladlukhanin** [comment]
If you want to get the `dialog_id` of outgoing messages this way, it will not work, because the message itself does not go throught this dialog. You can get a `dialog_id` through your application when you select the dialog (see our samples: https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat).
Later, we plan to track delivered/not delivered to dialog messages status on the server side and then listener will be added to SDK (analogue messageSendListener).
