### ISSUE TITLE
Listeners with session token previously obtained wont work

### ISSUE THREAD

**Issue by fiorin** [QuickBlox/quickblox-javascript-sdk#112]
Im building an external chat for a social network. Users just login at main page and the clean password is discarded after success. We store a MD5 version at BD, but its useless to connect at our quickblox account.

So, at login controller we call QB API with user data and store same QM.session JSON used at local storage, with token, user login and crypto password. We cant pass clean password to JS for security reasons.

Opening in another window, the JS chat calls with AJAX an API from my network which returns QM.session and store at localStorage to bypass authentication from pure JS.

The session was initialized by 'QB.init(token)' and chat works almost fine, except for a problem with listeners. The token has 1 year expiration. And seems same which the generated with default strategy. 

Login as usual using 'QBApiCalls.createSession' > 'QBApiCalls.connectChat' works, but using token generated before and 'QBApiCalls.connectChat' won't. 

Anyone knows why this is happening ? Or anything to help me ? Tnx

**Comment by soulfly** [comment]
Is it possible to receive from you some logs from browsers console?
will help to understand what errors you are receiving

**Comment by fiorin** [comment]
Had no errors. Everything else works fine: receive and send message, manage conctat list, and constant output 'presence' at console. The only things doesnt work are the listeners. So, i cant handle real time messages or status, cause doesnt trigger. 

The code was at my work pc, just monday to have acess, but running two instances: first with local create session then connect; a second one with my way using old section token; create an identical local storage and very similar outputs, except for listener trigger

**Comment by fiorin** [comment]
Theres console output from loading app until establish pinging presence '_presence xmlns="jabber:client"_'

`[QBChat]: Status.CONNECTING quickblox.js:874:5`
`[QBChat]: Chat Protocol - BOSH quickblox.js:874:5`
`[QBChat]: Status.CONNECTING quickblox.js:874:5`
`[QBChat]: Chat Protocol - BOSH quickblox.js:874:5`

`[QBChat RECV]: <stream:features xmlns="jabber:client"> quickblox.js:2540:127`
`[QBChat SENT]: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN"> quickblox.js:2541:128`
`[QBChat RECV]: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"> quickblox.js:2540:127`
`[QBChat RECV]: <stream:features xmlns="jabber:client"> quickblox.js:2540:127`
`[QBChat SENT]: <iq type="set" id="_bind_auth_2" xmlns="jabber:client"> quickblox.js:2541:128`

`[QBChat RECV]: <iq to="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" id="_bind_auth_2" xmlns="jabber:client" type="result"> quickblox.js:2540:127`
 `[QBChat SENT]: <iq type="set" id="_session_auth_2" xmlns="jabber:client"> quickblox.js:2541:128
[QBChat RECV]: <iq to="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" id="_session_auth_2" xmlns="jabber:client" type="result"> quickblox.js:2540:127`
`[QBChat]: Status.CONNECTED at 15:09:29 quickblox.js:874:5`
`[QBChat SENT]: <iq from="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" type="set" id="1:enableCarbons" xmlns="jabber:client"> quickblox.js:2541:128`
`[QBChat RECV]: <iq to="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" id="1:enableCarbons" xmlns="jabber:client" type="result"> quickblox.js:2540:127`
`[QBChat SENT]: <iq from="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" type="get" id="2:getRoster" xmlns="jabber:client"> quickblox.js:2541:128`
`[QBChat RECV]: <iq to="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" id="2:getRoster" xmlns="jabber:client" type="result"> quickblox.js:2540:127`

`2016-02-16T01:09:30.044Z qbApiCalls.js:41:4`
`[QBChat SENT]: <presence xmlns="jabber:client"> quickblox.js:2541:128`
`[QBChat RECV]: <presence to="7758569-32449@chat.quickblox.com" xmlns="jabber:client" from="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508"> quickblox.js:2540:127`
`2016-02-16T01:09:30.481Z qbApiCalls.js:41:4`
`2016-02-16T01:09:31.155Z qbApiCalls.js:41:4`
`[QBChat SENT]: <message from="7758569-32449@chat.quickblox.com/1220770403-quickblox-6508" to="7757616" type="chat" id="56c2064b6a0c623727000000" xmlns="jabber:client"> quickblox.js:2541:128`
 [QBChat RECV]: <presence to="7758569-32449@chat.quickblox.com" xmlns="jabber:client" from="7758252-32449@chat.quickblox.com/f9184e58f01d0fe4" id="ycTsP-196"> `

**Comment by dimaspirit** [comment]
@fiorin could you show the snippet of code where you set listeners?

**Comment by fiorin** [comment]
How i call the listeners:
`chatCallbacksInit: function() {`
`var ContactListView = this.app.views.ContactList,`
`MessageView = this.app.views.Message;`

`QB.chat.onMessageListener = MessageView.onMessage;`
`QB.chat.onSubscribeListener = ContactListView.onSubscribe;`
`QB.chat.onMessageTypingListener = MessageView.onMessageTyping;`
`QB.chat.onContactListListener = ContactListView.onPresence;`
`},`
Same way as the example from documentation which, for example, at MessageView:
`onMessage: function(id, message, recipientJid, isOfflineStorage) {`

**Comment by fiorin** [comment]
@soulfly @dimaspirit Im gonna change the way how handle this process, so.. thanks for attention. 

Cya guys
