### ISSUE TITLE
Question: Is it possible to use login ids instead of occupants_ids

### ISSUE THREAD

**Issue by ritesh-nitw** [QuickBlox/quickblox-javascript-sdk#113]
In order to perform any operation in chat api, **occupants_id** seems to be only way in docs:

```
var params = {
  type: 2,
  occupants_ids: [45,78],
  name: "The A team"
};
```

Can I pass logins_ids, as I have to make an un-necessary query to my nosql db for login_ids and occupants_ids mapping?

**Comment by soulfly** [comment]
No, it's not possible at this stage, only users' ids
you have to store them in your application in a some way
