### ISSUE TITLE
Using fetch API for requests

### ISSUE THREAD

**Issue by farwayer** [QuickBlox/quickblox-javascript-sdk#114]
It is new standard API like XMLHttpRequest but more powerful.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
Not all browsers are supporting `fetch` API now but you can use polyfill.
Using `fetch` API will help to remove extra dependencies like jQuery and Zepto and will help to make easy integration with `React Native`  #25 , `Native Scripts` and some other frameworks.

**Comment by dimaspirit** [comment]
It's a good idea. Thanks for your advice.

**Comment by dimaspirit** [comment]
We are preparing 3x version of SDK, so we will use fetch there

**Comment by netchkin** [comment]
@dimaspirit any ETA on 3x version of SDK?
