### ISSUE TITLE
How to delete a quickblox user from node js or javasript 

### ISSUE THREAD

**Issue by vamsi0391** [QuickBlox/quickblox-javascript-sdk#118]
Hi, I'm trying to delete quickblox user from node js using  the following function. 
 var params;
 params = parseInt(user_id); In user_id I'm passing quickblox id(9070123)
QB.users.delete(params, function(err, user){
                                      if (user) {
                                        console.log("   Quickboxid deleted "+JSON.stringify(user))
                                      } else  {
                                         console.log("   error at Quickboxid deleting "+err)
                                      }
                                    });
I'm getting error like, TypeError: Object.keys called on non-object.
Please give suggestions. Thanks in advance.

**Comment by Vladlukhanin** [comment]
Hey. In what line the error? What a file?

This method could not reproduce the error, even if specifically allow:

```
var QBUser = {
 login: "admin-login",
 password: "admin-pass"
}; // olnly admin can delete users

QB.init(appId, authKey, authSecret, config); // your creds

QB.createSession(QBUser, function(err, result) {
    if (err) {
        console.log('QB >>> Something went wrong: ' + JSON.stringify(err));
    } else {
    QB.users.create({
      'login': 'NewUser_'+Math.floor(Math.random()*9999999),
      'password': 'secret123',
      'full_name': 'QB_Test',
      'website': 'https://quickblox.com'
    }, function(err, res){
      if (err) {
        console.log('err'+JSON.stringify(err));
      } else {
        console.log('res: '+JSON.stringify(res));
        QB.users.delete(res.id, function(err, res){
          if (err) {
            console.log('err: '+JSON.stringify(err));
          }else{
            console.log('res: '+JSON.stringify(res));
          }
        });
      }
    });
  }
});
```

**Comment by vamsi0391** [comment]
fdfdfdfdfdfdfd

**Comment by vamsi0391** [comment]
I created my admin like xxxx@gmail.com and password like 123456 and i'm initiating  as follows:
var QBUser = {
 login: "xxxx@gmail.com",
 password: "123456s"
}; 
QB.init(29781, 'gp2aT-jtR32rtcU', 'pBJhJ8JOrGdntpQ');
I'm getting error : QB >>> Something went wrong: {"code":401,"status":"401 Unauthorized","message":{"errors":["Unauthorized"]},"detail":["Unauthorized"]}
I used login (11100122001) as well as Id(517085) also but same error occurs

And the error when deleting is from :
Path: node_modules/quickblox/js/qbProxy.js:16
Object.keys(ajaxCall.data).forEach(function(item,i,ar)
and the error is as follows:
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.ServiceProxy.ajax (/opt/games/node_modules/quickblox/js/qbProxy.js:160:15)
    at Object.UsersProxy [as delete](/opt/games/node_modules/quickblox/js/modules/qbUsers.js:126:18)
    at Object.<anonymous> (/opt/games/src/server/route/admin/admin.js:1892:42)
    at Object._onImmediate (/opt/games
/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback](timers.js:345:15)

**Comment by Vladlukhanin** [comment]
Most likely your **login** or **password** is incorrect. Please authorized as an administrator in the session, it the only way you can delete another user.
"Object.keys called on non-object" is manifested in the callback, which should return an error from the server.
Use Node.js v4.0.0 (need ES6) or higher to avoid TypeError errors (we will fix it for ES5 later).

**Comment by vamsi0391** [comment]
ok i will try as your suggestion

**Comment by vamsi0391** [comment]
I registered quickblox as Sign in with Google, then what credentials to be passed in code to create session

**Comment by Vladlukhanin** [comment]
http://quickblox.com/developers/Javascript#Authorization
Only need to log in the owner of an admin panel (admin) to have the right to delete users.
A normal QB User can delete only himself.

**Comment by vamsi0391** [comment]
Please check my situation:
I have a situation like this, in my app,  user can be deactivated, so at the time I'm deleting the user from database through node js API, so in that service I'm writing quickblox logic to dynamically delete from quickblox panel also. So the steps i following is as follows:
var QB = require('quickblox');
QB.init(2123xx45, 'gp2aY-jtQxxxx32mmnU', 'phUtxxxIoPq');
var QBUser = {
         email: "xxxx@gmail.com",  
        password: "123456xxxx"
}; // olnly admin can delete users
 // These are admin email and password. I created admin as SignIn with Google account  
QB.createSession(QBUser, function(err, result) {       //Creating session with above credentials
        if (err) {
                console.log('QB >>> Something went wrong: ' + JSON.stringify(err));  //I'm getting error here
        } else {
                console.log('QB >>> result: ' + JSON.stringify(result));
       }
});
exports.deleteUser=function(req,res){          //Node service to delete user from MongoDb
   db.userModel.remove({_id:req.body.userid},function(err,userDeleted){
           if(userDeleted){       //user deleted from database
                     var user_id=req.body.quckbloxId;
                  QB.users.delete(user_id, function(err, user){  //Trying to delete user from Quickblox Admin //here
                 if (err) {
                             console.log("   error at Quickboxid deleting "+err)
                   } else  {
                             console.log("   Quickboxid deleted")
                        }
                });
          }
       })
    }
My intention is  to delete as Admin only from the service

**Comment by vamsi0391** [comment]
Hi please give any suggestion

**Comment by dimaspirit** [comment]
@vamsi0391 Hi, sorry, but I don't understand what is wrong. 
Could you specify a question?

**Comment by vamsi0391** [comment]
Hi, Please see the above comment started with "Please check my situation:"

**Comment by vamsi0391** [comment]
Question is How to delete quickblox user in admin panel using node service.

Please check my situation:
I have a situation like this, in my app, user can be deactivated, so at the time I'm deleting the user from database through node js API, so in that service I'm writing quickblox logic to dynamically delete from quickblox panel also. So the steps i following is as follows:
var QB = require('quickblox');
QB.init(2123xx45, 'gp2aY-jtQxxxx32mmnU', 'phUtxxxIoPq');
var QBUser = {
email: "xxxx@gmail.com",
password: "123456xxxx"
};      // only admin can delete users

// These are admin email and password. I created admin as SignIn with Google account

QB.createSession(QBUser, function(err, result) { //Creating session with above credentials
if (err) {
console.log('QB >>> Something went wrong: ' + JSON.stringify(err));   // I'm getting error here
} else {
console.log('QB >>> result: ' + JSON.stringify(result));
}
});
exports.deleteUser=function(req,res){ //Node service to delete user from MongoDb
db.userModel.remove({_id:req.body.userid},function(err,userDeleted){
if(userDeleted){ //user deleted from database
var user_id=req.body.quckbloxId;
QB.users.delete(user_id, function(err, user){ //Trying to delete user from Quickblox Admin //here
if (err) {
console.log(" error at Quickboxid deleting "+err)
} else {
console.log(" Quickboxid deleted")
}
});
}
})
}
My intention is to delete as Admin only from the service

**Comment by dimaspirit** [comment]
I understood that you want to deactivate user and delete from QB. You wrote the snippet.
What is wrong? Is you get a error?

**Comment by vamsi0391** [comment]
yes I'm getting error here: Unable to create admin session

var QB = require('quickblox');
QB.init(2123xx45, 'gp2aY-jtQxxxx32mmnU', 'phUtxxxIoPq');
var QBUser = {
email: "xxxx@gmail.com",
password: "123456xxxx"
}; // only admin can delete users

QB.createSession(QBUser, function(err, result) { //Creating session with above credentials
if (err) {
console.log('QB >>> Something went wrong: ' + JSON.stringify(err)); // **_error here unable to create      session with admin**_*****
} else {
console.log('QB >>> result: ' + JSON.stringify(result));
}
});

**Comment by dimaspirit** [comment]
@vamsi0391, is this message ('unable to create a session with admin') of error?

**Comment by vamsi0391** [comment]
I'm getting error like this: 
QB >>> Something went wrong: {"code":401,"status":"401 Unauthorized","message":{"errors":["Unauthorized"]},"detail":["Unauthorized"]}

**Comment by vamsi0391** [comment]
I'm giving correct admin credentials. I login with gmail account

**Comment by dimaspirit** [comment]
@vamse0391, try create QB.createSession  and also login in chat QB.chat.connect.
http://quickblox.com/developers/Web_XMPP_Chat_Sample#Login_to_Chat

**Comment by vamsi0391** [comment]
Yes I will check

**Comment by IegorKozakov** [comment]
@vamsi0391, Hello. Can you try again on a  new version of quickblox-javascript-sdk?

**Comment by dimaspirit** [comment]
Checkout this page https://quickblox.com/developers/Errors

**Comment by dimaspirit** [comment]
@vamsi0391 are you resolve the issue?

**Comment by SnuK87** [comment]
I'm currently trying the same and get this error:
```
[ERROR] QBApi - { code: 403,
  status: '403 Forbidden',
  message: '{"errors":{"base":["You are not owner of this object"]}}',
  detail: null }
```

@Vladlukhanin What exactly is an admin user? 
- Is it a user where I check `Is admin (read only)`? I tried it and got the error
- Is it the login I use for the QB admin panel? But what should I use as login? That user only has `Username` and `Email`
- Is there another admin user I missed?

I'm using the same code that you posted so I think I missed some details about admin users.
