### ISSUE TITLE
Different 1-1 Private Chat Dialogs for same occupants based on data properties

### ISSUE THREAD

**Issue by hash1492** [QuickBlox/quickblox-javascript-sdk#119]
I have a use case in my project where two people can have multiple chat dialogs between them depending the the topic. For Example: Person A and Person B have a chat dialog for topic X. Same two people also have another chat dialog for topic Y. 

I tried creating dialogs by provding topic related details in the params object. Here is my code:

```
var params = {
                type: 3,
                occupants_ids: [user_quickblox_id],
                data: {
                  class_name: "Ads",
                  ad_id: ad_id,
                  ad_title: $scope.ad_detail.title,
                  ad_user: $scope.ad_detail.personal_info.name
                },
              };

              QB.chat.dialog.create(params, function(err, createdDialog) {
                if (err) {
                  console.log(err);
                } else {
                  console.log(createdDialog);
                 ...
                }
              });
```

What is happening is that the first dialog is created successfully (Lets call this Dialog 1), with the data properties.
But when I try to create another dialog with the same occupants but different data properties, I am returned with the previously created dialog of those occupants, which is Dialog 1.

Question: Is it possible for 2 occupants to have multiple 1-1 Private chat dialogs based on different data properties? 

Please reply at the earliest as it is interupting my work.
Thanks

**Comment by Vladlukhanin** [comment]
Hello. You can have only one Private chat for 2 occupants. But you could use Group dialog for your goals.

**Comment by hash1492** [comment]
Thanks
