### ISSUE TITLE
Crash in the background in mobile browser when receiving a msg

### ISSUE THREAD

**Issue by BrunoSalerno** [QuickBlox/quickblox-javascript-sdk#123]
If I have the chat running in a browser in a mobile device, and the browser is not in the foreground, receiving a msg makes quickblox crash.

Remote debbuging outputs this:

`quickblox.min.js:4 Error: TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.`

**Comment by dimaspirit** [comment]
@BrunoSalerno , do you want to get a PushNotification by QBSDK?

**Comment by BrunoSalerno** [comment]
@dimaspirit I solved it! Sorry :S. The problem was that window.Notification is not working in mobile browsers. I thought It was related to Quickblox because of the `quickblox.min.js:4 ...` thing in the log message. But it looks like it's not.

**Comment by dimaspirit** [comment]
Good, can I close the issue?) Also, we have SDK for all platform if you need.

**Comment by BrunoSalerno** [comment]
Yes @dimaspirit thanks! Yes I know, we are using iOS and Android SDK too.
