### ISSUE TITLE
QuickBlox Video Chat Demo Sample: "this.socket is undefined" after calling start call

### ISSUE THREAD

**Issue by Sirsendu786** [QuickBlox/quickblox-javascript-sdk#125]
I am getting "**this.socket is undefined**" error  in QuickBlox Video Chat Demo Sample. It's works fine when I run it locally (from local file system) but if I integrate it to a ASP.NET MVC application which running on local IIS Espress (Visual Studio 2015) I am getting below error in Firefox console window the moment I click on "Start Call" and accept to share audio/video deviec media:

> this.socket is undefined QB.js:8111:0
> [QBWebRTC]: _dialingCallback, answerTimeInterval: 5000 QB.js:1620:32
> TypeError: this.socket is undefined
>  QB.js:8111:175
> [QBWebRTC]: _dialingCallback, answerTimeInterval: 10000 QB.js:1620:32
> TypeError: this.socket is undefined
>  QB.js:8111:175
> [QBWebRTC]: _dialingCallback, answerTimeInterval: 15000 QB.js:1620:32
> TypeError: this.socket is undefined
>  QB.js:8111:175
> [QBWebRTC]: _dialingCallback, answerTimeInterval: 20000 QB.js:1620:32
> TypeError: this.socket is undefined
>  QB.js:8111:175
> [QBWebRTC]: _dialingCallback, answerTimeInterval: 25000 QB.js:1620:32
> TypeError: this.socket is undefined

Here "QB.JS" is a unminified version of QuickBlox JS SDK. I did it, so that can get to know which code block in JS SDK throwing the error and it happens to be the below code block

```
                           _onIdle: function() {
                                var b = this._conn._data;
                                if (b.length > 0 && !this._conn.paused) {
                                    for (var c = 0; c < b.length; c++)
                                        if (null !== b[c]) {
                                            var d, e;
                                            d = "restart" === b[c] ? this._buildStream().tree() : b[c], e = a.serialize(d), this._conn.xmlOutput(d), this._conn.rawOutput(e), this.socket.send(e)
                                        }
                                    this._conn._data = []
                                }
                            }
```

specifically the line 

`d = "restart" === b[c] ? this._buildStream().tree() : b[c], e = a.serialize(d), this._conn.xmlOutput(d), this._conn.rawOutput(e), this.socket.send(e)`

more specifically the part in that line `this.socket.send(e)`.

QuickBlox documentation says that, it should be run over HTTPS for security reason and so I tried that as well by enabling SSL and attaching a self signed certificate but **NO LUCK**

Can you shed some light here as to what going wrong and why such weird undocumented behavior I am seeing.

**NOTE:** It's the same sample I have downloaded from GitHib (Following QuickBlox documentation page) and haven't change anything except the config file to include my own "AppId/AuthKey/AuthSecrect and few demo users"

Thanks,
Sirsendu Mukherjee

**Comment by Sirsendu786** [comment]
related stackoverflow question thread

http://stackoverflow.com/questions/36343943/quickblox-video-chat-demo-web-sample-this-socket-is-undefined-after-calling-s

**Comment by soulfly** [comment]
Hi

thanks for reporting this

here is how the **socket** var is initialised

`this.socket = new WebSocket(this._conn.service, "xmpp");`

so can you make sure that WebSocket are supported on your server environment?

**Comment by Sirsendu786** [comment]
@soulfly I enabled websocket in IIS but still receiving the same error. Any other suggestion?

**Comment by soulfly** [comment]
Does it work well if you just run this sample via **grunt server** ?

**Comment by Sirsendu786** [comment]
@soulfly, No worries, I have solved the issue and it was **not** because of "WebSocket". It was due to a mistake I was doing but it's weird that you guys JS SDK doesn't give a helpful error information. 

I will soon post an answer both here and in stackoverflow for anyone facing the same issue in future.

Thanks.

**Comment by soulfly** [comment]
Thanks, looking forward to your answer

**Comment by dimaspirit** [comment]
@Sirsendu786 ,can you share the answer with everyone, please?

**Comment by dimaspirit** [comment]
@Sirsendu786 , can you share the answer with everyone, please? Do you have other questions?

**Comment by dimaspirit** [comment]
@Sirsendu786 what is the result if you use `grunt server` ?  If all is ok it's means the problem in  IIS Express (env.). Do you have another point?

**Comment by Sirsendu786** [comment]
@soulfly and @dimaspirit sorry, couldn't post a comment before since I was stuck in other task and now fully involved in QuickBlox integration (We went for Enterprise license). Below is the brief:

After debugging found that, sole reason I was facing the issue because 
1. I already did a "QB.Init()" and again were doing another "QB.Init()"

I fixed that and ran but was still facing the same issue and finally found that 
1. I already had a session opened  in my "_layout.cshtml" file by means of (QB.createSession()) and in another place I was trying to create a video session by saying "QB.webrtc.createsession()" because of which I was getting the error.

I am sure about that, cause once I destroyed the session then everything worked absolutely fine. 

So to answer **other readers**:

In case you are facing the same make sure 
1. You haven't already initiated the QB frameworkby saying "QB.Init()"
2. You haven't already have a chat session opened. My observation: if you have a XMPP chat session opened by saying "QB.createSession()" and you are trying to create a video webrtc session it gives this weird error. In case, you need to create a session for some purpose then destroy it before opening a video session like:

```
QB.createSession(function(res, err)
{
  if(err)
   console.log(JSON.Stringify(err));
else
   //do your stuff here and once done

QB.Destroysession(function(){
}
});
});
```

Now you can go ahead and start creating a video session and it will work just fine.

Question / Suggestion for QuickBlox member:
1. Please have a proper error message cause "this.socket is undefined" is not a proper error message and doesn't gives any information about what went wrong.
2. Per request from @darya from your team, if you want to reproduce the issue then follow either of the below scenario:

a) create a text chat session and then try creating a video chat session.

b) Create a simple html file with two button: on click of first button open up text chat and do some chatting then click on the (click browser back button if required) 2nd button and try opening the video chat. You will see that the issue getting reproduced.

Please let me know your findings and any solution / workaround you can offer on this issue.

Thanks,
Sirsendu Mukherjee

**Comment by Sirsendu786** [comment]
Posted an answer in stackoverflow thread as well only with specific workaround.

**Comment by dimaspirit** [comment]
@Sirsendu786 ok, we will handle the error with a right message.

> Please let me know your findings and any solution / workaround you can offer on this issue.

Sorry, I don't understand what is a solution / workaround  you need? We are talking about `this.socket is undefined` issue ?

**Comment by Sirsendu786** [comment]
@dimaspirit, What I am trying to say is: I am not much confident on the workaround I am using current (i.e, destroying the other session before opening a video session). So I was asking, if guys can try to reproduce the same at your end and if issue found then probably can propose a better solution / workaround for this issue.

For betterment, can you please follow the reproduction step I have mentioned and let me know if you can reproduce the issue in-house.

Thank You.

**Comment by IegorKozakov** [comment]
@Sirsendu786. As I see, you found a solution to your problem.
I can't reproduce this issue. Now, if you will create a new session, the old one will be rewritten.
Can you try to reproduce this issue using a new version of JS SDK?

**Comment by dimaspirit** [comment]
See the solution here http://stackoverflow.com/questions/36343943/quickblox-video-chat-demo-web-sample-this-socket-is-undefined-after-calling-s
