### ISSUE TITLE
Problems with webpack

### ISSUE THREAD

**Issue by Otann** [QuickBlox/quickblox-javascript-sdk#13]
Hi guys!

I am using webpack, tool like browserify, but focused on nodejs packages instead of bower.

I've tried to require your package in on of my modules and is seems that webpack detected quite a few dependencies not listed in package.json: `fs`, `net` and `tls`.

I wonder, how do you deal with your code requiring then in your bower distribution?
Is there any cases using your library with Webpack already?

I can support you with any information to improve your manuals to show how to use it with Webpack.

**Comment by flipxfx** [comment]
+1 for out of the box web pack support.

**Comment by soulfly** [comment]
Hi there, 

Is it only fs, net, tls and json should be added to package.json?

**Comment by Otann** [comment]
Yep, for me adding them to `package.json` solved the issue.
But this raises concerns about if they are used in the browser and if they are not, then it would be good to separate code and save data.

**Comment by yloeza** [comment]
does anyone had an issue with `webpack` and `strophe-pollyfill`?
I also needed to add `json loader` and the not listed `fs`, `net` and `tls` dependencies on package json.

**Comment by dimaspirit** [comment]
Thanks, we know about this issue and will fix in next version (2.0.4).

**Comment by dimaspirit** [comment]
Hey everyone, in version [v2.0.4](http://quickblox.com/developers/Javascript#Framework_changelog) we added all dependencies via npm. If this will not fix issue, we must waiting when will be fix this [issue](https://github.com/strophe/strophejs/issues/166)

**Comment by soulfly** [comment]
We also release 2.1 version with other updates for it, please check
http://quickblox.com/developers/Javascript#Framework_changelog
