### ISSUE TITLE
QB.chat.connect taking too long to respond

### ISSUE THREAD

**Issue by hash1492** [QuickBlox/quickblox-javascript-sdk#132]
Hi, I am using the Quickblox javascript sdk V 2.1.0 in my Ionic Framework App. For login, I am using the Facebook access token and not normal username and password. Here is my code:

```
var CONFIG = {
    chatProtocol: {

        websocket: "wss://chat.quickblox.com:5291",
        active: 2 // or set 2 if you would like to use websockets
    },
    ssl: true,
    debug: {mode: 1}
};

QB.init(28732, "P-vdT2rhS-xUzCn", "BWpYvxTBaOWvbfN", CONFIG);


facebookConnectPlugin.getAccessToken(function(token) {

    console.log("====QB createSession called");
    var params = {provider: 'facebook', keys: {token: token}};
    QB.createSession(params, function(err, session) {
        if (session) {
            console.log("=====QB connect called====");
            console.log(session);
            QB.chat.connect({userId: session.user_id, password: session.token}, function(err, roster) {
                if (err) {
                    console.log(err);
                } else {
                    console.log("====CONNECTED!!!====");
                }
            });
        }else{
            console.log(err);
        }
    });
});

```

Here, QB.createSession is called and the response comes immediately. But for QB.chat.connect, it takes about 10 seconds to connect and get its response. So every time the user opens my app , quickblox starts initializing and the user has to wait more than 10 seconds before he/she can use the chat functionality. Is there something that I am missing? Please get back to me ASAP as this is a big problem in my app's performance.

**Comment by dimaspirit** [comment]
@hash1492 , could you share with us full log and made a screenshot of Network tab from Inspector?

**Comment by hash1492** [comment]
![image](https://cloud.githubusercontent.com/assets/8502490/14740132/3ea3f2ea-08aa-11e6-837d-d585d1412f76.png)

In the logs, the time taken between "=====QB connect called====" and "=====QB connected ====" is about 10 seconds

**Comment by hash1492** [comment]
![image](https://cloud.githubusercontent.com/assets/8502490/14740240/1911530a-08ab-11e6-9306-90eee70bb534.png)

**Comment by hash1492** [comment]
@dimaspirit could you please tell me whats wrong with this call? I am unable to proceed due to this long delay.

Thanks

**Comment by dimaspirit** [comment]
@hash1492 , where do you live? And share your config (endpoints), please.

**Comment by hash1492** [comment]
@dimaspirit  I live in Gujarat, India. And what config are you talking about? The quickblox code is mentioned above. And QB.chat.connect is whats talking too long.

**Comment by dimaspirit** [comment]
http://quickblox.com/developers/Javascript#Configuration

**Comment by hash1492** [comment]
@dimaspirit Here is my config that I am using in my code:

```
var CONFIG = {
    chatProtocol: {

        websocket: "wss://chat.quickblox.com:5291",
        active: 2 // or set 2 if you would like to use websockets
    },
    ssl: true,
    debug: {mode: 1}
};
```

 I don't have the "endpoints" property inside the CONFIG object, like in the link you shared above. Everything is working fine with this config, EXCEPT that QB.chat.connect call is taking about 10 seconds.

Do I need to change my config?

**Comment by hash1492** [comment]
@dimaspirit , hello update on this? Let me know if I need to change my config.

**Comment by dimaspirit** [comment]
Sure, we will continue to research an issue. Could you make a test of your connection and share with us?

**Comment by bhaumik-gandhi** [comment]
@dimaspirit , hello We have same issue and I have config as same as @hash1492 you can see connection details in this URL: http://www.speedtest.net/result/5354984982.png

**Comment by Vladlukhanin** [comment]
Hi guys!
The improvements will be added in the next release.

**Comment by sanjaytaneja** [comment]
Hi,
 Any updates? I'm facing the same issue. Please let me know if there is a workaround until it is fixed.

**Comment by ajeeshcitrus** [comment]
Any updates around this??

**Comment by dimaspirit** [comment]
Hi, we add servers based in Asia, so could anyone confirm this issue?
