### ISSUE TITLE
Is wss://chat.quickblox.com:5291 down?

### ISSUE THREAD

**Issue by jguillen1984** [QuickBlox/quickblox-javascript-sdk#138]
**Environment details**
_(Operating system, browser information, SDK version)_
MacOSX, Chrome Browser, Latest SDK

**Did this work before?**
I don't know

**Expected behavior**
I would expect your sample example to connect to the provided endpoint ( chat.quickblox.com:5291 ) I also tried port :5290 when chatProtocol.active set to 2, as well as both http and https endpoints when  chatProtocol.active set to 1.

**Actual behavior**
I get connection refused.

**Logs**
_(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))_
`quickblox.min.js:8 WebSocket connection to 'wss://chat.quickblox.com:5291/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Steps to reproduce the behavior**
Go to http://quickblox.github.io/quickblox-javascript-sdk/samples/chat/ and click on "Quick" or "Block".

**Any others comments?**
Here is my config var from config.js
`
var config = {
  chatProtocol: {
    active: 2
  },
  debug: {
    mode: 1,
    file: null
  },
  stickerpipe: {
    elId: 'stickers_btn',

```
apiKey: 'Shh ... it is a secret',

enableEmojiTab: false,
enableHistoryTab: true,
enableStoreTab: true,

userId: null,

priceB: '0.99 $',
priceC: '1.99 $'
```

  }
};
`

**Comment by dimaspirit** [comment]
@jguillen1984 hi, could you check one more time this sample http://quickblox.github.io/quickblox-javascript-sdk/samples/chat ?
It's possible, we make some work on our shared server.

**Comment by dimaspirit** [comment]
Also, you could use bosh instead of websocket. 
uses
```
chatProtocol: {
  active: 1
},
```
in config

**Comment by dimaspirit** [comment]
@jguillen1984 , could you confirm this issue?
