### ISSUE TITLE
Update user tags

### ISSUE THREAD

**Issue by shide1989** [QuickBlox/quickblox-javascript-sdk#139]
Hi,
i would LOVE if it was possible to update a user's tags using the Javascript SDK,
i tried to update a user's tags using the following parameters in `QB.users.update` :

```
tags
user_tags
```

such as :
`
    var params = {
        user_tags: ["testing"]
    };
`

if you know a way of doing this, please let me know asap.
I even posted a question on stackoverflow
thank you !

**Comment by shide1989** [comment]
even on iOS they can do it : 
`updateParameters.tags = [[self.tagsTextField.text componentsSeparatedByString:@","] mutableCopy];
`

**Comment by dimaspirit** [comment]
@shide1989 , sure.
Are you trying http://quickblox.com/developers/Sample-users-javascript#Update_your_own_profile ? or you can set any parameters in a custom data.
Also, see how to update a tags list here https://gist.github.com/dimaspirit/c26b4d61e7db2e63fdbb#file-join_anonym-js-L64

**Comment by shide1989** [comment]
@dimaspirit thank you so much ! i couldn't find the right parameter name "tag_list" anywhere....
you made my day, thanks !
