### ISSUE TITLE
Can't receive incoming video calls between iOS and Web

### ISSUE THREAD

**Issue by jpascal** [QuickBlox/quickblox-javascript-sdk#14]
When I make call from iOS on Web console I see this:
```
[QBChat RECV]:  \<message xmlns="jabber:client" type="qbvideochat_call" ... ></message>
...
...
...
[QBChat RECV]:  <message xmlns="jabber:client" type="qbvideochat_call" ... ></message>
```
But QB.webrtc.onCallListener not invoked.

**Comment by soulfly** [comment]
For this you have to use new WebRTC iOS SDK

http://quickblox.com/developers/VideoChat#WebRTC_samples

Old iOS/Android samples don't work with Web
