### ISSUE TITLE
Quickblox Javacsript SDK Documentation is outdated

### ISSUE THREAD

**Issue by shide1989** [QuickBlox/quickblox-javascript-sdk#140]
Hi guys,
if you could update the Quickblox Documentation you would actualy bring peace to earth.
I don't know how many hours/days i've wasted all because the documentation is outdated.

Please do something about it, the only examples/sources working are the that you can download...

Oh and please add the following parameter "tag_list" on the QB.users.update fonction documentation.

Thanks

**Comment by soulfly** [comment]
Hi Sebastien, it's up to date

what exactly is not working on your side? please let us know

**Comment by shide1989** [comment]
hi,
there's missing info on many functions (user subscriptions listing for example)
http://quickblox.com/developers/Sample-push_notifications-javascript#Sending_Push_Notifications

**Comment by dimaspirit** [comment]
@shide1989 , we are starting to write the [API ref](https://quickblox.github.io/quickblox-javascript-sdk/docs/).
