### ISSUE TITLE
401 Unauthorized Error while using QB.createSession

### ISSUE THREAD

**Issue by himanshunimje** [QuickBlox/quickblox-javascript-sdk#142]
I am using Javascript SDK and its chat sample code to get started. The code works perfectly fine with the test users 'quick' and 'blox'. Though I am having issues while using other user's credentials with the same code.

Following are the changes that I have done:
1. In addition to this code in config.js:

```
var QBUser1 = {
id: 6729114,
name: 'quickuser',
login: 'chatusr11',
pass: 'chatusr11'
},
QBUser2 = {
id: 6729119,
name: 'bloxuser',
login: 'chatusr22',
pass: 'chatusr22'
};
```

I have added the following variable with new user's credentials.

```
var QBUser3 = {
id: 13718335,
name: 'testtutor',
login: 'karlmarx',
pass: 'himanshu123'
};
```
1. In order to log in with this user and open the chat history and chat dialog box, I have changed the following code in connection.js:

```
currentUser = QBUser3;
connectToChat(QBUser3);
```

which gives the following error in browser console:

which gives a '401 Unauthorized' Error. The exact error log is:

`Object {readyState: 4, responseText: "{"errors":["Unauthorized"]}", responseJSON: Object, status: 401, statusText: "Unauthorized"}
`
I have double checked the login and password.

Kindly let me know what exactly could be the issue for this error.

Thanks

**Comment by dimaspirit** [comment]
@himanshunimje , in this [sample](http://quickblox.github.io/quickblox-javascript-sdk/samples/chat/) we don't create a new user. So, you can't just change params and create a new user like [here](https://gist.github.com/dimaspirit/c26b4d61e7db2e63fdbb).

If you want to see how it work https://github.com/QuickBlox/q-municate-web.

Also, we have sample how to work with users - http://quickblox.com/developers/Sample-users-javascript

**Comment by himanshunimje** [comment]
@dimaspirit Thanks a lot dima. This solved my issue with the user registration and user login.

I was getting confused with the two types of user authentication present in the docs. Anyways, it is sorted now and again, thanks for the same :)
