### ISSUE TITLE
QB.pushnotifications.subscriptions.list 404 error

### ISSUE THREAD

**Issue by shide1989** [QuickBlox/quickblox-javascript-sdk#146]
Hi,
after successfuly creating a session:

> [ServiceProxy] Request:  POST { data: '{"url":"https://api.quickblox.com/session.json","type":"POST","data":{"application_id":"xxx","auth_key":"xxx","nonce":204,"timestamp":1467721076,"user":{"login":"xxx","password":"xxx"},"signature":"xxx"}}' }

i tried to retrieve a user's subscription but i get this error :

> [SubscriptionsProxy] list
> [ServiceProxy] Request:  GET { data: '{"url":"https://api.quickblox.com/subscriptions.json"}' }
> error : {"code":404,"status":"404 Not Found","message":" ","detail":null}

how can i solve this ???
ps : again, there's no info in the QB Javascript documentation, and i had to use the example given in the ZIP Archive we can download here : http://quickblox.com/developers/Javascript#Node.js_and_NPM_integration

**Comment by Vladlukhanin** [comment]
Hi, @shide1989 !
`error : {"code":404,"status":"404 Not Found","message":" ","detail":null}` - it means that you don't have  subscriptions for the device which is specified in the authorization token.
Here is the code of [pushNotification](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/spec/QB-PushnotificationsSpec.js) test, it may be helpful for you.

**Comment by shide1989** [comment]
thanx @Vladlukhanin, 

i found out we were loosing subscriptions for some obscure reason i'm still looking for.
Thank you for your answer, they could at least return a proper result with an empty set....
It's quickblox anyway, you can't have a proper response and documentation haha

**Comment by shide1989** [comment]
@Vladlukhanin  i spoke too fast, actualy i still get the 404 error even thought i have a user sbubscription

**Comment by shide1989** [comment]
anyone ??

**Comment by dimaspirit** [comment]
Hi, @shide1989 
Are you sure you have subscriptions ? Do you see in the admin panel?

If you are sure share to us code snippet and logs, please

**Comment by shide1989** [comment]
@dimaspirit :
yes / yes. btw i'm using the js sdk w NodeJS.

```

        _createSession(QBUser, function (err, response) {
          if (err) return callback(err, null);

          QB.pushnotifications.subscriptions.list(function (err, result) {
            if (err) {
              console.error('[Quickblox] Error :', err);
              return callback('[Quickblox] no subscriptions for user :' + QBUser);
            }

            if (result.length > 0) {
              QB.pushnotifications.events.create(notifParams, function (err, response) {
                if (err) {
                  console.error('[pushnotifications error]', QBUser, err);
                  return callback(err);
                }
                // console.log('[QuickBlox] PushNotification Sent | %j', notifParams);
                callback(null, response);
              });
            }
            else {
              console.log('No subscriptions found for user : %j', QBUser);
              callback('No subscriptions found for user : ' + JSON.stringify(QBUser));
            }
          });
        });

```

**Comment by waelbentaleb** [comment]
I have the same issue here, I can't list my subscription for both REST API and JavaScript SDK.

**Comment by dimaspirit** [comment]
Sorry for the long delay.
Could you specify this issue? Environment details, SDK version, logs and screenshots from Network (Developer tools) for this requests.
Also, you could check this case by [test cases](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/spec/QB-PushnotificationsSpec.js) to make sure that this SDK issue. Just change [config](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/spec/config.js).

If you are our customer write to support and we help to resolve the issue more quickly.
