### ISSUE TITLE
Getting notified when a new chat room is created.

### ISSUE THREAD

**Issue by Buooy** [QuickBlox/quickblox-javascript-sdk#149]
We are trying to get notified when a new chat room is created so that we can trigger a backend workflow such as scheduling a follow up email.

How can we do that? Can we have a nodejs process continually running and listening for a new chatroom?

**Comment by IegorKozakov** [comment]
Hallo @Buooy! As I understood, you need to send email notifications to all users, which was added to the group chat. Now we are in develop of this functionality. 

But you can create a chat bot, using node.js.
http://quickblox.com/developers/ChatBots
When you will do this, you can configure system messages, and send them to the chat bot. 
https://quickblox.com/developers/Web_XMPP_Chat_Sample#System_notifications
For example, you can send a list of users in a system message and bot will send the email notifications to all users in that list.

**Comment by dimaspirit** [comment]
@Buooy , is this solution for you?
