### ISSUE TITLE
Unable to create message with attachments in Node.js

### ISSUE THREAD

**Issue by rooswelt** [QuickBlox/quickblox-javascript-sdk#151]
When creating a message using this code
`var message = {
                message: 'bbbbbb'
            };
            message.attachments = [{
                    type: 'image/jpeg',
                    id: 6296283
                }];
            message.chat_dialog_id = dialogId;
            message.send_to_chat = 1;
            QB.chat.message.create(message, function (err, createdMessage) {
                if (err) {
                    console.log("XXXError creating hello message " + JSON.stringify(err));
                } else {
                    console.log("XXXHello message created: " + JSON.stringify(createdMessage));
                }
            });`

Works fine in browser but in Node.js does not add any attachment

Logs from browser:
![schermata 2016-08-11 alle 12 10 06](https://cloud.githubusercontent.com/assets/1296566/17585525/9688cf94-5fbc-11e6-9efc-9f19c3a2e0a6.png)

Logs from Node.js:
![schermata 2016-08-11 alle 12 09 01](https://cloud.githubusercontent.com/assets/1296566/17585494/73484438-5fbc-11e6-9b95-3cdb7df36c80.png)

SDK Version: 2.14

Thanks in advance

**Comment by Vladlukhanin** [comment]
Hi, @rooswelt !

Try to create a message with attachments like an object where is object's key is number(index):
message.attachments = [{ type: 'image/jpeg', id: 6296283 }]; => {'0': { 'type': 'image/jpeg', 'id': 6296283 }};

**Comment by rooswelt** [comment]
Hi, @Vladlukhanin 

thanks for your help, it works!
