### ISSUE TITLE
addListener callback doesn't accept stanza or message

### ISSUE THREAD

**Issue by nalnaji** [QuickBlox/quickblox-javascript-sdk#16]
Hello all, I am trying to learn how to accept incoming messages from chat. Right now the QB CHAT [RECV] is printing the XML form. I want to be able to add a handler for every message. The docs say:

```
The handler will receive the stanza that triggered it as its argument.
```
and the format states:
![screen shot 2015-05-15 at 9 03 23 pm](https://cloud.githubusercontent.com/assets/5743986/7664631/dee17214-fb45-11e4-9b8f-0ad3a103c257.png)

What I have done is (addListener is at the bottom):
![screen shot 2015-05-15 at 8 59 49 pm](https://cloud.githubusercontent.com/assets/5743986/7664637/073b3628-fb46-11e4-9496-c702b0d99dd0.png)

The handler doesn't receive the message as an argument like the specifications stated. I am not sure if I am using this incorrectly. Please advise.

**Comment by nalnaji** [comment]
I changed the following code in the JS SDK to the following and it seems to work now. It receives the stanza object.

![screen shot 2015-05-16 at 12 38 53 am](https://cloud.githubusercontent.com/assets/5743986/7665252/07cdb6ec-fb64-11e4-8d87-71b6c2972b52.png)

**Comment by soulfly** [comment]
Hi there, 

What do you mean by "I want to be able to add a handler for every message" ?

Why current listener implementation doesn't work for you?

**Comment by nalnaji** [comment]
Sorry, I misread the documentation for "onMessageListener". Thank you for your reply. This is a great solution for XMPP by the way. :)
