### ISSUE TITLE
QB.chat.onMessageListener firing twice

### ISSUE THREAD

**Issue by jmanlapid** [QuickBlox/quickblox-javascript-sdk#164]
I'm having an issue where the QB.chat.onMessageListener is firing twice at the exact same time in group chat messages so then I'm appending duplicate messages on the client. I tried updated the SDK to the latest version but I'm still receiving the error. Any insight into why this may be happening? My tech stack is Ionic/Angular.

**Comment by IegorKozakov** [comment]
Hallo @jmanlapid. First of all, you should check does server send you duplicated messages.
For this, you need to enable debugging. Here is the link, where you can read more: https://quickblox.com/developers/Javascript#Configuration.

Please check it, and send us your log file.

**Comment by dimaspirit** [comment]
@jmanlapid , is this pull request resolve your issue?
https://github.com/QuickBlox/quickblox-javascript-sdk/pull/238
