### ISSUE TITLE
QB.chat._autoSendPresence method not found can you please provide alternate for that.

### ISSUE THREAD

**Issue by arpit-icreate** [QuickBlox/quickblox-javascript-sdk#167]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)_

**Environment details**
_(Operating system, browser information, SDK version)_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
QB.chat._autoSendPresence is private methods. 
Don't use private methods, please.

Why do you need this method?

**Comment by arpit-icreate** [comment]
Hello,
 we need this to stay connected with QUICKBOX. i am disconnected after few mins so we are using it to stay connected with Server.

**Comment by dimaspirit** [comment]
What is your environment details (Operating system, browser information, SDK version)?
What is broken?

**Comment by dimaspirit** [comment]
@arpit-icreate , could you confirm the issue and give us more information?
