### ISSUE TITLE
Public groups (type 1) always have 0 unread_message_count

### ISSUE THREAD

**Issue by jmanlapid** [QuickBlox/quickblox-javascript-sdk#168]
`QuickBlox JavaScript SDK - v2.2.1 - 2016-09-07`

My public group chats (type 1) always have an unread_messages_count of 0. Was this meant to be? Do private group chats (type 2) have their unread_message_count update? 

Here is my code for sending out messages.

``` javascript
     var msgParams = {
        type:'groupchat',
        body: inputMessage.text,
        extension: {
          save_to_history: 1,
          sender_id: $scope.userId,
          attachments: [{
            url: file.url(),
            type: 'photo'
          }]
        }
      };
    QB.chat.send($scope.group.get('quickBloxGroupJid'), msgParams);
```

**Comment by dimaspirit** [comment]
https://quickblox.com/developers/Web_XMPP_Chat_Sample#Create_a_Public_group_chat_dialog
The public doesn't have a list of occupants, so unread_messages_count is equal zero always.

Use group chat dialog if you need to get unread_messages_count .
