### ISSUE TITLE
How can I delete a quickblox unwanted/duplicate user from javascript.

### ISSUE THREAD

**Issue by gvijaydhanasekaran** [QuickBlox/quickblox-javascript-sdk#170]
I need to implement the quickblox application in various platform like Android, IOS, and Web also. Duplicate user entry has been created during user change their devices many times. In web user closing browser without logout, in that time duplicate entry has been created.
How can I handle this situation ?

Even I had tried to delete a duplicate users during login. But I can not delete the duplicate entry.

`                

```
               var params = {
                  filter: { field: 'full_name', param: 'in', value: data.username },
                  order: { sort: 'desc', field: 'id' }
                };
                QB.users.listUsers(params, function(err, result){
                        if (err) {
                            console.log("errMsg ==> ", err);
                        } else {
                            _.each(result.items, function(item) {
                                if (item.user.full_name == data.username) {
                                    QB.users.delete(item.user.id, function(err, user){
                                        if (user) {
                                            console.log("user deleted successfully");
                                        } else  {
                                            console.error('User not delete ============> : ', err);
                                        }
                                    });
                                }
                            });
                        }
                });
```

`

The above code was executed during login "app.helpers.join". It throw the error 

`

 Object {code: 403, status: "error", message: "Forbidden", detail: "{"errors":{"base":["You are not owner of this object"]}}"}

`

I am using  SDK v2.2.1

**Comment by IegorKozakov** [comment]
Hello, @gvijaydhanasekaran. 
To delete users from the app, you need to be logged in  as the owner of the QB application or as the current user (which you want to delete).

For example, you logged in as the user with id 123456, wich is not the owner of your application. You tried to delete the user with id 654321. The server will send you an error, but if you will try to delete the user with id 123456 (your logged in user), the server will delete it successful.

Also, we have a snippet of code for register anonymous users.
https://gist.github.com/dimaspirit/c26b4d61e7db2e63fdbb

**Comment by gvijaydhanasekaran** [comment]
Thanks for your reply :)
Ok, we cannot delete every user manually. As a owner, it will irritate this process. Is any snippet available for delete duplicate user or old logged in users (one or more months older). Because I need a requirement for limit the QB users.

**Comment by dimaspirit** [comment]
@gvijaydhanasekaran you need to be login as owner/admin and use https://quickblox.com/developers/Sample-users-javascript#Delete_a_user
