### ISSUE TITLE
QB Chat server not connecting 

### ISSUE THREAD

**Issue by ramansinghpadda** [QuickBlox/quickblox-javascript-sdk#18]
Hello 
I am using javascript-sdk and from samples , I am trying to run chat module after updating required config changes. Login working properly but after login nothing works.

        if (err) {
          console.log('SERVER ERROR RESPONSE ');
          console.log(err);
        } else {
          console.log('SERVER SUCCESS RESPONSE ');
          console.log(roster);

          QB.chat.onMessageListener = showMessage;

          $('#feed').val('User : CONNECTED at ' + getLocalTime());
        }
      });

Taking long time to connect socket server and after 1-2 min it return failed status . 

Please help & suggest me , where is the actual problem . 

Thanks

Raman Singh

**Comment by soulfly** [comment]
Hey, 

Please post the whole code and also your config

**Comment by ramansinghpadda** [comment]
js/qbConfig.js

 endpoints: {
    api: 'https://api.quickblox.com',
    chat: 'chat.quickblox.com',
    muc: 'muc.chat.quickblox.com',
    turn: 'turnserver.quickblox.com',
    s3Bucket: 'qbprod'
  },
  chatProtocol: {
    // bosh: 'http://chat.quickblox.com:5280',
    bosh: 'https://chat.quickblox.com:5281', // With SSL
    // websocket: 'ws://chat.quickblox.com:5290',
    websocket: 'wss://chat.quickblox.com:5291', // With SSL
    active: 2
  },

samples/chat/config.js

var QBApp = {
  appId: 23853,
  authKey: 'WVBFGKa4pqfb-cX',
  authSecret: 'UAMbFhVbPNHJ9HF'
};

var QBUser1 = {
      id: 3310096,
      name: 'Ramansingh',
      login: 'ramansingh',
      pass: 'Test@123'
    },
    QBUser2 = {
      id: 3310111,
      name: 'ReenaNalwa',
      login: 'reenanalwa',
      pass: 'Test@123'
    };

Samples/chat/main.js


// Init QuickBlox application here
//
QB.init(QBApp.appId, QBApp.authKey, QBApp.authSecret);

var opponent, currentUser;

$(document).ready(function() {

  $("#loginForm").modal("show");
  $('#loginForm .progress').hide();

  // User1 login action
  //
  $('#user1').click(function() {
    opponent = QBUser2;
    connectChat(QBUser1);
  });

  // User2 login action
  //
  $('#user2').click(function() {
    opponent = QBUser1;
    connectChat(QBUser2);
  });

  // Send message action
  //
  $('#sendMessage').click(function() {
    var msg = $('#message').val().trim();
    $('#message').val('').focus();

    if (msg.length > 0){
      sendMessage(opponent.id, msg);
    }
  });
});

function connectChat(user) {

  $('#loginForm button').hide();
  $('#loginForm .progress').show();

  // Create session and connect to chat
  //
  QB.createSession({login: user.login, password: user.pass}, function(err, res) {
    if (res) {
        console.log('Session History');
        console.log(res);
        
      var user_jid = QB.chat.helpers.getUserJid(user.id, QBApp.appId);
      var params={jid: user_jid, password: user.pass};
      console.log('Connecting Chat');
      console.log(params);
     
      QB.chat.connect(params, function(err, roster) {
        $("#loginForm").modal("hide");

        if (err) {
          console.log('SERVER ERROR RESPONSE ');
          console.log(err);
        } else {
          console.log('SERVER SUCCESS RESPONSE ');
          console.log(roster);

          QB.chat.onMessageListener = showMessage;

          $('#feed').val('User : CONNECTED at ' + getLocalTime());
        }
      });
    }
  });
}

// Send a chat message
//
function sendMessage(user_id, val) {
  var msg = {
    type: 'chat',
    body: val,

    extension: {
      time: Math.floor(Date.now() / 1000),
    }
  };
  
  var user_jid = QB.chat.helpers.getUserJid(user_id, QBApp.appId);
 
    QB.chat.send(user_jid, msg);

  showMessage(null, msg);
}

// Show messages in UI
//
function showMessage(userId, msg) {

  var body = msg.body,
      time = msg.extension && msg.extension.time,
      messageDate = new Date(time * 1000);

  var message = "\n";
      message += (userId === null ? "Me" : "Opponent");
      message += " (" + messageDate.getHours() + ':' + (messageDate.getMinutes().toString().length === 1 ? '0'+messageDate.getMinutes() : messageDate.getMinutes()) + ':' + messageDate.getSeconds() + ")";
      message +=  ": ";
      message += body;

  var currentText = $('#feed').val();
  $('#feed').val(currentText + message); 
}

function getLocalTime() {
  return (new Date).toTimeString().split(' ')[0];
}


Session.json return session properly but unable to connect chat server

Error Message - Which i am getting 

Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. quickblox.js:2707
[QBChat]: Status.CONNFAIL - The connection attempt failed quickblox.js:941
[QBChat]: Status.DISCONNECTED at 18:14:54 quickblox.js:941
[QBChat]: Status.CONNECTING quickblox.js:941
[QBChat]: Chat Protocol - WebSocket quickblox.js:941
[QBChat]: Status.CONNFAIL - The connection attempt failed quickblox.js:941
[QBChat]: Status.DISCONNECTED at 18:17:01 quickblox.js:941
[QBChat]: Status.CONNECTING quickblox.js:941
[QBChat]: Chat Protocol - WebSocket quickblox.js:941
[QBChat]: Status.CONNFAIL - The connection attempt failed quickblox.js:941
[QBChat]: Status.DISCONNECTED at 18:19:09 quickblox.js:941
[QBChat]: Status.CONNECTING

**Comment by ramansinghpadda** [comment]
[QBChat]: Status.CONNFAIL - The connection attempt failed quickblox.js:941
SERVER ERROR RESPONSE  main.js:60
Object {code: 422, status: "error", message: "Unprocessable Entity", detail: "Status.CONNFAIL - The connection attempt failed"}

**Comment by soulfly** [comment]
Can you try active: 1 in qbConfig.js

**Comment by ramansinghpadda** [comment]
Hii i am getting another problem.(JavaScript SDK), 

As i want to integrate web-rtc video chat. I have integrated the peer-to-peer chat successfully. But Now problem is in my application requirement i want status of users. Are they available for video chat or not.

![download](https://cloud.githubusercontent.com/assets/3245756/8003231/4e789212-0b93-11e5-93dd-4a6a1b11fcc6.png)


So i want to check status of user , Are they in session or not ?  

Please suggest me

**Comment by ramansinghpadda** [comment]
Is it possible to get any user status related to same APP ?

**Comment by soulfly** [comment]
You can use Roster API
http://quickblox.com/developers/Web_XMPP_Chat_Sample#Code_snippets_.28Roster.29

**Comment by raghuarvapally1** [comment]
[QBChat]: Status.CONNFAIL - The connection attempt failed quickblox.js:941
SERVER ERROR RESPONSE main.js:60
Object {code: 422, status: "error", message: "Unprocessable Entity", detail: "Status.CONNFAIL - The connection attempt failed"}

I tied with active: 1 in qbConfig.js still i am getting issue. Can you please help.

This is sample application downloaded from github....

**Comment by soulfly** [comment]
This sample?
https://github.com/QuickBlox/quickblox-javascript-sdk/tree/master/samples/chat

**Comment by raghuarvapally1** [comment]
Yes this sample application.....

**Comment by dimaspirit** [comment]
@ramansinghpadda and @raghuarvapally1 are you got the answer? Or update yours questions, please.

**Comment by highelf** [comment]
i use the latest version 2.0.3 but in safari the problem still .
is there any configuration that we must to apply ?

**Comment by dimaspirit** [comment]
@highelf, what OS and version of Safari are you use?

**Comment by highelf** [comment]
@dimaspirit in mac OS and Windows 7

**Comment by dimaspirit** [comment]
The last version of Safari for Window is 5.x
And now Windows version was discontinue, we are support Safari from 6.x ( http://quickblox.com/developers/Javascript#Browsers_support )

Could you show your logs on Safari for MacOS? We will trying to help you.

**Comment by varunsaini3150** [comment]
@soulfly 
sir i am trying to connect qb jdk with node js
session is created but when i use 
var user = {
      id: 4448514,
      name: 'chatuserweb1',
      login: 'chatuserweb1',
      pass: 'chatuserweb1'
    };

QB.createSession({login: user.login, password: user.pass}, function(err, res) {
  if (res) {
    QB.chat.connect({userId: user.id, password: user.pass}, function(err, roster) {
      if (err) {
          console.log(err);
      } else {

```
   /*
   *  (Object) roster - The user contact list
   *  roster = {
   *    '1126541': {subscription: 'both', ask: null},        // you and user with ID 1126541 subscribed to each other.
   *    '1126542': {subscription: 'none', ask: null},        // you don't have subscription but user maybe has
   *    '1126543': {subscription: 'none', ask: 'subscribe'}, // you haven't had subscription earlier but now you asked for it
   *  }; 
   */

  }
});
```

  }else{
    console.log(err);
  }
});

in this session is creating but when it moves to chat.connect

i got error on terminal that
this function is not supported with browser yet line 310 qbchat.js
i commented that line and next error comes to be that value of coonection is null at connection.connect();
at the begining of qbchat.js connection = conn is defined but value of conn is coming null from another file which i dont know

**Comment by dimaspirit** [comment]
@varunsaini3150 hey, JS SDK don't support Node env. 
We are working on this. 
Now https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/spec/QB-ChatSpec.js#L19

**Comment by varunsaini3150** [comment]
@soulfly  @dimaspirit  ,sir 
i want to listen to all messages sent+receive through running script on console all the time 
my full task is to connect qb through console nd when i connect qb with my company credentials and super admin id. it ll start listening all the messages which are coming to every group which are connected by super admin and with all the groups that are going to be created. by default if each time a new group is created linked with our company then they automatically contain our super admin in that.
thats why i want to connect qb through console and then want to login with super admin id and then want to listen all messages. 

please tell me the way even if its not through node js but should be by console or terminal. working on ubuntu 14.04 os
- and one more question if js sdk doesnt work for node js then how come it is creating session and i am reciving token and even though i am able to retrieve all the dialogs list of particular login id

**Comment by garretblankenship** [comment]
Ran into this issue on a IPhone 6s running Safari. When I go to the web application everything connects just fine but if I close the phone and then unlock the phone and open the browser again I get the connection issue. I think this is happening because I am using ReactJS and the component remounts which recalls the `QB.chat.connect()`. Is there a method you can use to see if you are already connected to chat and if that connection is still valid?
