### ISSUE TITLE
Need API documentation

### ISSUE THREAD

**Issue by EleDiaz** [QuickBlox/quickblox-javascript-sdk#181]
In general is difficult find API documentation.

This example, don't have full API description:
https://quickblox.com/developers/Web_XMPP_Chat_Sample#Guide:_Getting_Started_with_Chat_API

No there are full modules documentation (QB.users, QB.content....):
http://quickblox.github.io/quickblox-javascript-sdk/docs/

Switch between source code of SDK and my own application to know what methods there available to use is heavy.

**Comment by dimaspirit** [comment]
@EleDiaz Hi, sorry, API docs. in progress. 
We are working on this case.

I will notify when we are finished. 

> Switch between source code of SDK and my own application to know what methods there available to use is heavy.

What do you mean? Are you speaking about versions?

**Comment by ganeshub** [comment]
+1 for API Docs 
+1 for Node.js code samples

**Comment by dimaspirit** [comment]
To all, 
we finished writing [docs](https://quickblox.github.io/quickblox-javascript-sdk/docs/) for all modules except call (WebRTC).
About Node.js code samples there is no difference between browsers or Node.js.
We have the little [example](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat_bots) for bots in chat which help to start.
