### ISSUE TITLE
JS SDK: Can not send custom data while audio/video call to IOS SDK

### ISSUE THREAD

**Issue by olimjon** [QuickBlox/quickblox-javascript-sdk#185]
**Environment details**
*(Operating system, browser information, SDK version)*

1 Side:  QuickBlox JavaScript SDK - v2.1.2 - 2016-05-16  

2 Side: iOS version: 9.3.2
Quickblox iOS SDK version: 2.7.6
QuickbloxWebRTC SDK version: 2.2
Language: Objective-C
XCode version: 8.1

 
**Did this work before?**
No 

**Expected behavior**
We want send extra data while call. We are using session object's call method. There is a problem to get this data from IOS SDK. 

**Actual behavior**
we are sending js Object like this: 

this.currentSession.call({compact_data:compact_data}, function (error) {}) 

I can get this object using JS SDK. But there is some trouble with getting this data from IOS SDK. it gets nil; 

**Steps to reproduce the behavior**
pass js object while calling to IOS device. monitor custom data from IOS

**Comment by dimaspirit** [comment]
So you need to ask about this issue our iOS team in this [repo](https://github.com/QuickBlox/quickblox-ios-sdk).
