### ISSUE TITLE
QB.chat.connect often returning password error when password is correct.

### ISSUE THREAD

**Issue by Femtosecond** [QuickBlox/quickblox-javascript-sdk#19]

**Comment by soulfly** [comment]
First of all you can use

    var jid = QB.chat.helpers.getUserJid(user.id, 24325);

instead of 

     var jid = user.id + "-24325" + "@chat.quickblox.com";

The second this to check is can you log 'chatparams before QB.chat.connect and provide here a log, so we will be bale to check which parameters you provide
