### ISSUE TITLE
Message with attachments in node.js

### ISSUE THREAD

**Issue by ganeshub** [QuickBlox/quickblox-javascript-sdk#190]
This code from  [q-municate web](https://github.com/QuickBlox/q-municate-web/blob/master/app/scripts/views/attach.js#L196) app works when executed in browser. But breaks in node.js.
Messages with attachment are getting received as text messages with body text as 'Attachment' 

```js
            msg = {
                'type': type,
                'body': attach.type === 'location' ? 'Location' : 'Attachment',
                'extension': {
                    'save_to_history': 1,
                    'dialog_id': dialog_id,
                    'date_sent': time,
                    'attachments': [
                        attach
                    ]
                },
                'markable': 1
            };

            msg.id = QB.chat.send(jid, msg);
```

Reason seem to be this code from [sdk](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/1b2002c3e4d8a16ad641527f8bd97ae825b78e7b/src/modules/qbChatHelpers.js#L134)

```js
  filledExtraParams: function(stanza, extension, isSystemMsg) {
        var helper = this;

        Object.keys(extension).forEach(function(field) {
            if (field === 'attachments') {
                extension[field].forEach(function(attach) {
                    stanza.c('attachment', attach).up();
                });
            } else if (typeof extension[field] === 'object') {
                helper._JStoXML(field, extension[field], stanza);
            } else {
                if(utils.getEnv().browser) {
                    stanza.c(field).t(extension[field]).up();
                } else if(utils.getEnv().node) {
                stanza.getChild('extraParams')
                    .c(field).t(extension[field]).up();
                }
            }
        });

        stanza.up();

        return stanza;
    },
```
This code returns stanza with attachments element as children of extraParams in browser and children of root element in node.js.

**Comment by dimaspirit** [comment]
Yeap, we will fix it next release.

**Comment by ganeshub** [comment]
@dimaspirit Thanks. But Is there a workaround for time being ?

**Comment by IegorKozakov** [comment]
Hello @ganeshub. We fixed this bug and will update our repo next week. But you can take changes from the develop branch. 
I'll notify you when we will upload our changes to the npm repository.

**Comment by ganeshub** [comment]
Thanks @IegorKozakov for considering my request. Looking forward for npm update.

**Comment by dimaspirit** [comment]
@ganeshub , are you update the SDK? Could you confirm the issue?
