### ISSUE TITLE
onCallListener not working

### ISSUE THREAD

**Issue by koolll** [QuickBlox/quickblox-javascript-sdk#194]
I am using quickblox sdk to integrate webrtc video call to my application.I am trying to use user1 to call another user. But user2 **onCallListener**  seem like not response. Please see my code below . 
First Page
`   
     

     
        QB.init(xxxx, 'xxxxxxx', 'xxxxxx', true);
        var user = {
            id: 19404224,
            name: 'user1',
            login: 'fe523eb3-95a8-461a-9fa9-1223dea943c9',
            pass: 'doc12345#'
        };

        QB.createSession({ login: user.login, password: user.pass }, function (err, res) {
            if (res) {
                QB.chat.connect({ userId: user.id, password: user.pass }, function (err, roster) {
                    if (err) {
                        console.log(err);
                    } else {
                        var calleesIds = [20285555]; // client2 
                        var sessionType = QB.webrtc.CallType.VIDEO; // AUDIO is also possible

                        var session = QB.webrtc.createNewSession(calleesIds, sessionType);
                       
                        var extension = {};
                        session.call(extension, function (error) {
                            alert("calling");
                        });

                        QB.webrtc.onUserNotAnswerListener = function (session, userId) {
                            alert("no answer");
                        };

                        QB.webrtc.onCallListener = function (session, extension) {
                            alert("calling");
                        };

                        QB.webrtc.onRemoteStreamListener = function (session, userID, remoteStream) {
                            // attach the remote stream to DOM element
                            session.attachMediaStream('remoteVideo', remoteStream);
                        };

                        /*
                        *  (Object) roster - The user contact list
                        *  roster = {
                        *    '1126541': {subscription: 'both', ask: null},        // you and user with ID 1126541 subscribed to each other.
                        *    '1126542': {subscription: 'none', ask: null},        // you don't have subscription but user maybe has
                        *    '1126543': {subscription: 'none', ask: 'subscribe'}, // you haven't had subscription earlier but now you asked for it
                        *  }; 
                        */

                    }
                });
            } else {
                console.log(err);
            }
        });

    </script>
</body>
</html>
`

Second page
`
    <script>
        
     

     
        QB.init(xxx, 'xxxxx', 'xxxxx', true);
        var user = {
            id: 20285555,
            name: 'client2',
            login: 'ec529e51-c7c7-4be2-9c68-151bf721753b',
            pass: 'doc12345#'
        };

        QB.createSession({ login: user.login, password: user.pass }, function (err, res) {
            if (res) {
                QB.chat.connect({ userId: user.id, password: user.pass }, function (err, roster) {
                    if (err) {
                        console.log(err);
                    } else {
                        var calleesIds = [19404224]; // User's ids 
                        var sessionType = QB.webrtc.CallType.VIDEO; // AUDIO is also possible

                        var session = QB.webrtc.createNewSession(calleesIds, sessionType);
                       

                        var mediaParams = {
                            audio: true,
                            video: true,
                            options: {
                                muted: true,
                                mirror: true
                            },
                            elemId: 'localVideo'
                        };

                        session.getUserMedia(mediaParams, function (err, stream) {
                            if (err) {

                            } else {

                            }
                        });

                        QB.webrtc.onCallListener = function (session, extension) {
                            alert("calling"); //no working here
                        };

                        /*
                        *  (Object) roster - The user contact list
                        *  roster = {
                        *    '1126541': {subscription: 'both', ask: null},        // you and user with ID 1126541 subscribed to each other.
                        *    '1126542': {subscription: 'none', ask: null},        // you don't have subscription but user maybe has
                        *    '1126543': {subscription: 'none', ask: 'subscribe'}, // you haven't had subscription earlier but now you asked for it
                        *  }; 
                        */

                    }
                });
            } else {
                console.log(err);
            }
        });

    </script>
</body>
</html>
`
Any comment? Thanks

**Comment by IegorKozakov** [comment]
@koolll As I see, the user from the first page trying to call to the user from the second page.

you need to get mediaParams at the first page. In the getUserMedia callback you should make a call
`
var mediaParams = {
    audio: true,
    video: true,
    options: {
        muted: true,
        mirror: true
    },
    elemId: 'localVideo'
};

session.getUserMedia(mediaParams, function (err, stream) {
    session.call(extension, function (error) {
        alert("calling");
    })
});
`

You can check in our [WebRCT sample](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/samples/webrtc/js/app.js#L363)

**Comment by koolll** [comment]
@IegorKozakov Thanks I had change my code for the first page. Yes ,it able to get the alert message after make a call. But for the second page I still not able to get the **onCallListener** , alert.Can you please give some idea? Sorry I am beginner for the javascript

Update my code here
First Page
```
QB.createSession({ login: user.login, password: user.pass }, function (err, res) {
            if (res) {
                QB.chat.connect({ userId: user.id, password: user.pass }, function (err, roster) {
                    if (err) {
                        console.log(err);
                    } else {
                        var calleesIds = [20285555]; // client2 
                        var sessionType = QB.webrtc.CallType.VIDEO; // AUDIO is also possible

                        var session = QB.webrtc.createNewSession(calleesIds, sessionType);
                        var mediaParams = {
                            audio: true,
                            video: true,
                            options: {
                                muted: true,
                                mirror: true
                            },
                            elemId: 'localVideo'
                        };
                        var extension = {};
                        session.getUserMedia(mediaParams, function (err, stream) {
                            session.call(extension, function(error) {
                                alert("calling");
                            });
                        });
                        
                        


                        QB.webrtc.onCallListener = function (session, extension) {
                            alert("calling");
                        };

                        QB.webrtc.onRemoteStreamListener = function (session, userID, remoteStream) {
                            // attach the remote stream to DOM element
                            session.attachMediaStream('remoteVideo', remoteStream);
                        };

                        /*
                        *  (Object) roster - The user contact list
                        *  roster = {
                        *    '1126541': {subscription: 'both', ask: null},        // you and user with ID 1126541 subscribed to each other.
                        *    '1126542': {subscription: 'none', ask: null},        // you don't have subscription but user maybe has
                        *    '1126543': {subscription: 'none', ask: 'subscribe'}, // you haven't had subscription earlier but now you asked for it
                        *  }; 
                        */

                    }
                });
            } else {
                console.log(err);
            }
        });
```

Second page
  ```
 QB.createSession({ login: user.login, password: user.pass }, function (err, res) {
            if (res) {
                QB.chat.connect({ userId: user.id, password: user.pass }, function (err, roster) {
                    if (err) {
                        console.log(err);
                    } else {
                       
                        var calleesIds = []; // client2 
                        var sessionType = QB.webrtc.CallType.VIDEO; // AUDIO is also possible

                        var session = QB.webrtc.createNewSession(calleesIds, sessionType);


                        QB.webrtc.onCallListener = function onCallListener(session, extension) {
                            alert("incomming call");
                        };


                        


                        /*
                        *  (Object) roster - The user contact list
                        *  roster = {
                        *    '1126541': {subscription: 'both', ask: null},        // you and user with ID 1126541 subscribed to each other.
                        *    '1126542': {subscription: 'none', ask: null},        // you don't have subscription but user maybe has
                        *    '1126543': {subscription: 'none', ask: 'subscribe'}, // you haven't had subscription earlier but now you asked for it
                        *  }; 
                        */

                    }
                });
            } else {
                console.log(err);
            }
        });
```

**Comment by koolll** [comment]
Thanks I find a solution , issue solved

**Comment by TarunNarula** [comment]
Can you please share how you find the solution ?
