### ISSUE TITLE
Android Webview unable to disable/enable video, mute/unmute audio and record/download video

### ISSUE THREAD

**Issue by shishram** [QuickBlox/quickblox-javascript-sdk#196]
My Code is mentioned below, Please let me know if anything else I have to add to make it working.

NOTE: and permissions(camera,audio) also not being accepted using webview for that I have used Manifest permission and its working. 

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "WEB";
    @Bind(R.id.web_view)
    WebView mWebView;
    private String LOCAL_FILE = "file:///android_asset/samples/webrtc/index.html";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
        StrictMode.setVmPolicy(builder.build());
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        loadWebView();
    }

    private void loadWebView() {

        WebSettings webSettings = mWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setDomStorageEnabled(true);
        webSettings.setAllowFileAccessFromFileURLs(true);
        webSettings.setAllowUniversalAccessFromFileURLs(true);
        webSettings.setPluginState(WebSettings.PluginState.ON);

        mWebView.addJavascriptInterface(new WebAppInterface(this), "Android");

        // Set a web view client and a chrome client
        mWebView.setWebViewClient(new WebViewClient());
        mWebView.setWebChromeClient(new WebChromeClient() {
            // Need to accept permissions to use the camera and audio
            @Override
            public void onPermissionRequest(final PermissionRequest request) {
                Log.d(TAG, "onPermissionRequest");
                MainActivity.this.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        // Make sure the request is coming from our file
                        // Warning: This check may fail for local files
                        //if (request.getOrigin().toString().equals(LOCAL_FILE)) {
                            request.grant(request.getResources());
                        /*} else {
                            request.deny();
                        }*/
                    }
                });
            }
        });
        // Load the local HTML file into the webview
        mWebView.loadUrl(LOCAL_FILE);
    }

    private class WebAppInterface {
        Context mContext;

        WebAppInterface(Context c) {
            mContext = c;
        }

        // This function can be called in our JS script now
        @JavascriptInterface
        public void showToast(String toast) {
            Toast.makeText(mContext, toast, Toast.LENGTH_LONG).show();
        }
    }

}

below index.html div not functioning at all in webview

<div class="caller__frames_acts">
                    <button class="caller__frames_acts_btn j-caller__ctrl" data-target="video">
                        <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19" version="1.1">
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-290.000000, -80.000000)">
                              <g transform="translate(288.000000, 78.000000)">
                                <path d="M0 0L24 0 24 24 0 24 0 0Z"/>
                                <path class="svg_icon" d="M21 6.5L17 10.5 17 7C17 6.45 16.55 6 16 6L9.82 6 21 17.18 21 6.5 21 6.5ZM3.27 2L2 3.27 4.73 6 4 6C3.45 6 3 6.45 3 7L3 17C3 17.55 3.45 18 4 18L16 18C16.21 18 16.39 17.92 16.54 17.82L19.73 21 21 19.73 3.27 2 3.27 2Z"/>
                              </g>
                            </g>
                          </g>
                        </svg>
                    </button>

                    <button class="caller__frames_acts_btn j-caller__ctrl" data-target="audio">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" version="1.1">
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-347.000000, -80.000000)">
                              <g transform="translate(344.000000, 78.000000)">
                                <path d="M0 0L24 0 24 24 0 24 0 0Z"/>
                                <path class="svg_icon" d="M19 11L17.3 11C17.3 11.74 17.14 12.43 16.87 13.05L18.1 14.28C18.66 13.3 19 12.19 19 11L19 11ZM14.98 11.17C14.98 11.11 15 11.06 15 11L15 5C15 3.34 13.66 2 12 2 10.34 2 9 3.34 9 5L9 5.18 14.98 11.17 14.98 11.17ZM4.27 3L3 4.27 9.01 10.28 9.01 11C9.01 12.66 10.34 14 12 14 12.22 14 12.44 13.97 12.65 13.92L14.31 15.58C13.6 15.91 12.81 16.1 12 16.1 9.24 16.1 6.7 14 6.7 11L5 11C5 14.41 7.72 17.23 11 17.72L11 21 13 21 13 17.72C13.91 17.59 14.77 17.27 15.54 16.82L19.73 21 21 19.73 4.27 3 4.27 3Z"/>
                              </g>
                            </g>
                          </g>
                        </svg>
                    </button>

                    <button class="caller__frames_acts_btn_record j-record" alt="record video">
                    </button>
                </div>

**Comment by dimaspirit** [comment]
@shishram are you using Cordova or Phonegap?

**Comment by shishram** [comment]
@dimaspirit I am trying to implement it directly in WebView native in Android Studio by putting all the quickblox SDK code in assets.

**Comment by dimaspirit** [comment]
@shishram What is a type of SDK you use?
Javascript SDK of Java SDK ?

**Comment by shishram** [comment]
@dimaspirit I have used Javascript SDK

**Comment by dimaspirit** [comment]
Are you using React Native?
Sorry, the question still doesn't clear for me.

WebView is part of what?
If you write by  Android Studio and using Java why are you using JS SDK?
Maybe you need look at Java SDK?

**Comment by shishram** [comment]
Webview is part of Android native development, I am not using react too.
The reason I am using this is because I wanna capture video frames and save
them or video recording feature I need, but I am not sure of video
recording is there in Java SDK. Let me know if it's there then it will do
too.

**Comment by dimaspirit** [comment]
Are you sure that you have a permission on audio?
You can check stream what you have by MediaStream.getAudioTracks()

**Comment by shishram** [comment]
Permissions are there call is connecting properly only record video and mute/unmute and camera turn on/off not working. For Java SDK I am not sure of video
recording is there in Java SDK. Let me know if it's there then it will do
too.

**Comment by soulfly** [comment]
As far as I remember, WebRTC is supported staring from Android 5 WebView 

In modern versions of Android the WebView component is based on the Chromium open source project which already includes WebRTC ([more info](https://developer.chrome.com/multidevice/webview/overview)). As listed there all Android devices starting from Android 5.0 support WebRTC API in WebView. 

So please check this first of all, do you use Android 5.0 and above or not

Also, regarding permissions, make sure you the following permissions:

   ```
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
```
