### ISSUE TITLE
 Microphone not working in cordova video chat

### ISSUE THREAD

**Issue by startappsolution** [QuickBlox/quickblox-javascript-sdk#197]
In cordova Android 6.0 for video chat video works very well, but microphone not working..Also i gave permission for microphone...please tell me the solution for this.......

**Comment by pknath** [comment]
Same for me. microphone not working even in android 5.0 and 6.0

**Comment by soulfly** [comment]
Here is a solution 

http://quickblox.com/developers/Sample-webrtc-cordova#Android_WebRTC_support

proper permissions for config.xml

also commit with the changes https://github.com/QuickBlox/quickblox-javascript-sdk/commit/772cea80428e23a0ceec01918e54df4a0a9aeb23#diff-5f1e743bd47e1286a6f57330e79e0c22

**Comment by pknath** [comment]
Thanks @soulfly ,

just fixed sometime back. Yes did the same and it worked added the permissions. :)
