### ISSUE TITLE
Keep seeing this warning in firefox on QBlox v1.9.2 (ff 38.0.5)

### ISSUE THREAD

**Issue by tpemckiernan** [QuickBlox/quickblox-javascript-sdk#20]
RTCIceServer.url is deprecated! Use urls instead.

**Comment by soulfly** [comment]
do you use the latest version of js sdk? 

latest is 1.9.2

**Comment by soulfly** [comment]
This is on Mozilla Firefox only because they are going to replace url with urls

So now it works as is

you don't need any changes and can ignore this warning for now
