### ISSUE TITLE
How can i integrate chatbot to my iOS mobile app?.

### ISSUE THREAD

**Issue by Uday-1985** [QuickBlox/quickblox-javascript-sdk#202]
Hi there,

I have an iOS, Android and web app.I want to implement a chatbot like feature into all these three apps.I would like to know how to integrate your bot to my apps?.

Thanks,
Uday

**Comment by dimaspirit** [comment]
@udaymedic Hi, we have an article to help you https://quickblox.com/developers/ChatBots

**Comment by Uday-1985** [comment]
I have checked that article but with no luck.It doesn't let users know
about how to use it for mobile app.

Best Regards,
Uday

**Comment by dimaspirit** [comment]
You don't make a chatbot for each platform. We recommend using user as chatbot.
https://chatbotsmagazine.com/the-complete-beginner-s-guide-to-chatbots-8280b7b906ca#.6y89ffj32 Recommend reading.

**Comment by Uday-1985** [comment]
Okay, perfect.I will read it and will let you know if there is any
confusions.Thanks dima.

Best Regards,
Uday

**Comment by dimaspirit** [comment]
@Uday-1985 , do you need any help?

**Comment by Uday-1985** [comment]
I have done with it and created a sample chat bot. Thanks

Thanks,

Uday
