### ISSUE TITLE
Adding a video stream to audio call after the call has started.

### ISSUE THREAD

**Issue by utkarshmaximess** [QuickBlox/quickblox-javascript-sdk#203]
**Expected behavior**

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Hi, now this features doesn't include in our SDK.
Recommend use video call with muted video and switch on if you need.
