### ISSUE TITLE
react-native failure

### ISSUE THREAD

**Issue by Kraignos** [QuickBlox/quickblox-javascript-sdk#204]
Hi,

I couldn't get it working for a react-native app.
I always have an error during module transformation:

`Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░  75.8% (356/409)...(node:28525) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2391): UnableToResolveError: Unable to resolve module fs from /Users/me/Development/quickblox_app/node_modules/quickblox/src/qbUtils.js: Module does not exist in the module map or in these directories:
  /Users/me/Development/quickblox_app/node_modules/quickblox/node_modules
,   /Users/me/Development/quickblox_app/node_modules
,   /Users/me/node_modules
`

Any idea ? Thanks

**Comment by TonyHaddad91** [comment]
Hey,
are u able to manage this because I'm facing same issue

**Comment by t-fritsch** [comment]
My 2 cents : looks like this bug is due to quickblox thinking that the app is running in node.js environment and thus requiring lots of unavailable packages (fs, crypto, etc.). 
I tried to force env to browser by setting `isBrowser = true` everywhere and commenting every `require(...)` instruction that was firing an error with no result yet. 

Another solution could be to force those packages to install inside the RN app as suggested here : https://stackoverflow.com/a/37493577 and here : https://stackoverflow.com/a/45304528
but I'm not sure this is the right direction since quickblox *can* work outside node.js, so this option to install all this stuff, seems a bit hacky and I'm worried that it may cause some unwanted effects or security breach (?).

any advice on this @dimaspirit ?

**Comment by t-fritsch** [comment]
So I tried to use rn-nodeify but after adding crypto, fs, util, events, http, https, url, stream and zlib (one after another, followed by a complete and long process : yarn install+react-native link+delete app/build folders+full rebuild cycle) it seems like a dead end : Adding child_process to rn-nodify was ineffective and I couldn't get rid of the "Unable to resolve module child_process". 

So sad.

Has someone managed to make quickblox work on React Native ? Should I consider using another chat system ?

**Comment by Dandroas** [comment]
@tfritsch-km IMO I would use another. I have enterprise support, and when I initially asked, they said it should work fine, despite the fact that there is obvs issues (as you pointed out, Node modules.).

I wished we used firebase from the getgo

**Comment by vikas-polarisft** [comment]
Hi is there any update on this issue, was migrating from Ionic to React-Native and got blocked on this issue trying to require Quickblox and getting the fs module issue

**Comment by t-fritsch** [comment]
Thanks @Dandroas I followed your advice and switched to firebase (I would have preferred not using a google service but it works fine so far).

I hope one day QuickBlox team will try to make their js sdk compatible with React Native since the tech is quite growing, and QB service seems very cool.

**Comment by dimaspirit** [comment]
To all,
in a few future sprints, we will research and will fix this issue.

**Comment by pournam** [comment]
Is there any update on this? We have a big project that started on web which is using quickblox for chat, now we are finishing a react native app but cannot get messaging to work. We are considering to rewrite all our messaging to use firebase on web so we can support on RN. Any chance quickblox will work on react native very soon?

**Comment by Rumesh25** [comment]
Guys, it looks like QuickBlox is not responding anymore. I spent 3 weeks to ping them on various support channels, but it looks like something completely broken… 
I did my own investigation on the issues with React-Native, you can ping me at <rumeshtubalor@gmail.com>, I will share it with you. I do not wan’t to waste my time anymore here.. I need to finish my project

**Comment by tfritsch-km** [comment]
@Rumesh25 the latest commit on any of the quickblock's repositories (https://github.com/QuickBlox) was on 29th may...
looks like nothing happened since then

no good news.. 🙊

**Comment by vadimkhmyrovqb** [comment]
@Kraignos @pournam Our team is going to publish ReactNative SDK in Q2 2019.
