### ISSUE TITLE
ES6 browser usage

### ISSUE THREAD

**Issue by bilby91** [QuickBlox/quickblox-javascript-sdk#207]
Hello, I'm trying to use the SDK with ES6 in the browser, using babel for transpiling code. When I try to import Quickblox `import QuickBlox from 'quickblox'` I get multiple errors because there are multiple node modules that are not defined obviously. 

Is there a way to use npm quickblox package in a setup like the mentioned before ? 

Thanks!

**Comment by IegorKozakov** [comment]
JS SDK supports UMD (Universal Module Definition) pattern for JavaScript modules. So it is possible to use SDK everywhere (as browser global variable, with AMD module loader like RequireJS or as CommonJS module).

So, you can get access to the SDK using window.QB

**Comment by bilby91** [comment]
@IegorKozakov Thanks for the tip! 

Another question, what about `react-native` support, I guess window won't be available on a `react-native` environment, is this supported yet ?

**Comment by alvarezloaiciga** [comment]
hi @bilby91 were you able to add it to react-native?

**Comment by bilby91** [comment]
@alvarezloaiciga Moved to `twilio-chat`. Didn't try quickblox at the end. You will probably need to change a couple of things in order to make it work.
