### ISSUE TITLE
Any REST API to get last_presence_at ?

### ISSUE THREAD

**Issue by arpit87** [QuickBlox/quickblox-javascript-sdk#210]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
I want to know when last a user logged in and sent presence packet. Want to do it using REST APIs from server 

**Did this work before?**
The last_request_at field doesn't work as it only tells when was the last User API called using user level token.

**Expected behavior**

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Hi, @arpit87 
If you are talking about last activity (https://xmpp.org/extensions/xep-0012.html) we don't make it yet.
We are planning to make this XEP soon, but we will use websocket not API request

**Comment by dimaspirit** [comment]
I will notify you when we make it by this issue.
