### ISSUE TITLE
Periodic presence packet not sent in latest js sdk

### ISSUE THREAD

**Issue by arpit87** [QuickBlox/quickblox-javascript-sdk#212]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*
in browser console I dont see periodic presence packets being sent 
**Environment details**
*(Operating system, browser information, SDK version)*
chrome

**Did this work before?**
yes. QuickBlox JavaScript SDK - v2.1.2

**Expected behavior**
want periodic presence packets to be sent. 

**Actual behavior**
After login only single presence is sent

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*
QBChat] SENT: <open xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-framing" to=​"chat.quickblox.com" version=​"1.0">​</open>​
quickblox.min.js:43 [QBChat] RECV: <open xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-framing" from=​"chat.quickblox.com" id=​"ca931e0c-93db-40ac-8584-b45b16f8843d" version=​"1.0" xml:lang=​"en">​</open>​
quickblox.min.js:43 [QBChat] RECV: <stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​
quickblox.min.js:43 [QBChat] SENT: <auth xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl" mechanism=​"PLAIN">​…​</auth>​
quickblox.min.js:43 [QBChat] RECV: <success xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​</success>​
quickblox.min.js:43 [QBChat] SENT: <open xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-framing" to=​"chat.quickblox.com" version=​"1.0">​</open>​
quickblox.min.js:43 [QBChat] RECV: <open xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-framing" from=​"chat.quickblox.com" id=​"ca931e0c-93db-40ac-8584-b45b16f8843d" version=​"1.0" xml:lang=​"en">​</open>​
quickblox.min.js:43 [QBChat] RECV: <stream:features xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams">​…​</stream:features>​
quickblox.min.js:43 [QBChat] SENT: <iq type=​"set" id=​"_bind_auth_2" xmlns=​"jabber:​client">​…​</iq>​
quickblox.min.js:43 [QBChat] RECV: <iq xmlns=​"jabber:​client" id=​"_bind_auth_2" type=​"result" to=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732">​…​</iq>​
quickblox.min.js:43 [QBChat] SENT: <iq type=​"set" id=​"_session_auth_2" xmlns=​"jabber:​client">​…​</iq>​
quickblox.min.js:43 [QBChat] RECV: <iq xmlns=​"jabber:​client" id=​"_session_auth_2" type=​"result" to=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732">​</iq>​
quickblox.min.js:43 [ChatProxy] Status.CONNECTED at 19:14:07
quickblox.min.js:43 [QBChat] SENT: <iq type=​"set" from=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732" id=​"7c37ad7c-5e49-4a62-a99d-959ec8c2b82b:​enableCarbons" xmlns=​"jabber:​client">​…​</iq>​
quickblox.min.js:43 [QBChat] SENT: <iq type=​"get" from=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732" id=​"335ac82e-f40a-4979-ad20-ff8e3b58152b:​getRoster" xmlns=​"jabber:​client">​…​</iq>​
quickblox.min.js:43 [QBChat] RECV: <iq xmlns=​"jabber:​client" id=​"7c37ad7c-5e49-4a62-a99d-959ec8c2b82b:​enableCarbons" type=​"result" to=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732">​</iq>​
quickblox.min.js:43 [QBChat] RECV: <iq xmlns=​"jabber:​client" id=​"335ac82e-f40a-4979-ad20-ff8e3b58152b:​getRoster" type=​"result" to=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732">​…​</iq>​
quickblox.min.js:43 [QBChat] SENT: <presence xmlns=​"jabber:​client">​</presence>​
doctor.js:828 Logged in to chat starting video call
doctor.js:829 session created qb
quickblox.min.js:43 [QBChat] RECV: <presence xmlns=​"jabber:​client" id=​"T9Vcq-327" from=​"10383758-23434@chat.quickblox.com/​android_00000000-2d57-1197-ffff-ffffef05ac4a" to=​"10383758-23434@chat.quickblox.com">​</presence>​
quickblox.min.js:43 [QBChat] RECV: <presence xmlns=​"jabber:​client" from=​"10383758-23434@chat.quickblox.com/​1571722472-quickblox-3755732" to=​"10383758-23434@chat.quickblox.com">​</presence>​

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Yes, we removed 'sent present' every 55 seconds. Why do you need it?

**Comment by arpit87** [comment]
I have a custom application built over quickblox in which I am maintaining
a list on online users on my server. On every presence packet received i am
calling presence api to my server.

Anyway to directly query quickblox from server to know last_presence_time
of some user?

**Comment by dimaspirit** [comment]
It's not used for ast_presence_time. 
https://xmpp.org/extensions/xep-0012.html doesn't make yet.

**Comment by dimaspirit** [comment]
@arpit87 , we implemented last activity features. Check out [v2.7.0](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.7.0)
