### ISSUE TITLE
List group chat dialogs which include specific multiple occupants

### ISSUE THREAD

**Issue by lvl99** [QuickBlox/quickblox-javascript-sdk#214]
**Environment details**
*(Operating system, browser information, SDK version)*
macOS Sierra 10.12.2
Google Chrome 56.0.2924.87
Node.JS 6.9.5
Ember 2.11
Quickblox 2.5.1

**Did this work before?**
Not sure if its supported since the documentation mentions `occupants_ids` in the [REST API](https://quickblox.com/developers/Chat#Retrieve_dialogs) but not in the [JS API](https://quickblox.com/developers/Web_XMPP_Chat_Sample#Filters). It would be nice if it could work.

**Expected behavior**
To receive a list of group chat dialogs containing all listed user IDs in the `occupants_ids` array

**Actual behavior**
Receive an undefined value

**Logs**
https://gist.github.com/lvl99/0ed6eebedc45422c5bf28f6c14e2b033

**Steps to reproduce the behavior**
```
QB.chat.dialog.list({
  type: 2,
  // Put in the relevant occupants_ids to test with here
  occupants_ids: [123, 456]
}, (err, dialogs) => {
  console.log(dialogs)
})
```

```
QB.chat.dialog.list({
  type: 2,
  // Put in the relevant occupants_ids to test with here
  occupants_ids: "123,456"
}, (err, dialogs) => {
  console.log(dialogs)
})
```

**Any other comments**
I've attempted with both an Array and a CSV (comma-separated values) string and I still get nothing. It's probable this functionality currently doesn't exist, but it's very important that it could. At the moment I would have to load all of a user's dialogs to then search through them to match the `occupants_ids`. When users have 100+ dialogs, this makes it very laborious to program.

**Comment by IegorKozakov** [comment]
It is possible to get dialogs by `occupants_ids`. 

As example, you can use this curl request

`curl -X GET -H "QB-Token: YOUR TOKEN" -d "type=2&occupants_ids[all]=COMMA SEPARATED OCCUPANTS_IDS" https://api.quickblox.com/chat/Dialog.json`

Using JS SDK you can send request in a this way: 

```javascript
    // Get dialogs which contain only this occupants
    QB.chat.dialog.list({
        "type": 2,
        "occupants_ids": "123,456"
    }, (err, dialogs) => {
        console.log(dialogs)
    });

    // Get dialogs which contain at least one of this occupants.
    QB.chat.dialog.list({
        "type": 2,
        "occupants_ids[in]": "123,456"
    }, (err, dialogs) => {
        console.log(dialogs)
    });

    // Get dialogs which contain ALL of this occupants.
    QB.chat.dialog.list({
        "type": 2,
    "occupants_ids[all]": "123,456"
    }, (err, dialogs) => {
        console.log(dialogs)
    });
```
