### ISSUE TITLE
Retrieving dialogs with custom data

### ISSUE THREAD

**Issue by lvl99** [QuickBlox/quickblox-javascript-sdk#215]
**Environment details**
(Operating system, browser information, SDK version)
macOS Sierra 10.12.2
Google Chrome 56.0.2924.87
Node.JS 6.9.5
Ember 2.11
Quickblox 2.5.1

**Did this work before?**
Not sure, have only tried now

**Expected behavior**
To get a list of dialogs which match the custom data filters.

**Actual behavior**
Gets all of the dialogs for the user.

**Logs**
I'm trying to locate a single dialog, instead I get all available dialogs for the user:
```
{
  "total_entries": 642,
  "skip": 0,
  "limit": 100,
  "items":[{ ... }]
}
```

**Steps to reproduce the behavior**
Replace `XYZ` with your applicable values.

Technically I don't need to specify `user_id=XYZ` as it is implied from the token, but I thought I'd do it anyway.

```
curl -X GET -H "QB-Token: XYZ" -d "data[custom_data_1]=XYZ&data[custom_data_2]=XYZ" https://api.quickblox.com/chat/Dialog.json
```

```
curl -X GET -H "QB-Token: XYZ" -d "type=2&custom_data_1=XYZ&custom_data_2=XYZ&user_id=XYZ" https://api.quickblox.com/chat/Dialog.json
```

```
curl -X GET -H "QB-Token: XYZ" -d "type=2&data[custom_data_1][in]=[XYZ]&data[custom_data_2][in]=[XYZ]&user_id=XYZ" https://api.quickblox.com/chat/Dialog.json
```

I have tried the above examples with `=XYZ`, `[in]=[XYZ]` and `[all]=[XYZ]` with the same results.

**Any others comments?**
Please ensure the documentation has adequate examples to illustrate all usage patterns. The docs for [Retrieve Dialogs](https://quickblox.com/developers/Chat#Retrieve_dialogs) mentions that I can use custom data in the retrieval, and points to the example where I create a dialog. As you can see from above I've attempted a couple different ways to apply it based on the docs' loose description and I've met with failure on all counts.

**Comment by IegorKozakov** [comment]
Hello. First of all, you need to create [CustomObject](https://quickblox.com/developers/Chat#Custom_parameters) class in admin panel. More info [here](https://quickblox.com/developers/Custom_Objects#Create_data_schema).

After that, you need to create dialogs with custom parameters.

[Here](https://quickblox.com/developers/Chat#Filter_dialogs_by_custom_parameters) you can read more about retrieving dialogs by custom parameters.
