### ISSUE TITLE
total message count

### ISSUE THREAD

**Issue by ibabchanik** [QuickBlox/quickblox-javascript-sdk#216]
Hello! 
Is it possible to get total message count of chat room? 
In JS SDK I haven't found information about it.

Thanks in advance.

**Comment by dimaspirit** [comment]
@ibabchanik  https://quickblox.com/developers/Web_XMPP_Chat_Sample#Get_a_number_of_chat_messages

**Comment by ibabchanik** [comment]
@dimaspirit Thanks a lot!
