### ISSUE TITLE
Can't connect to chat from Node backend

### ISSUE THREAD

**Issue by ketanbhatt** [QuickBlox/quickblox-javascript-sdk#22]
I am not able to connect to chat from my node-express backend. 

Creating sessions, users etc is okay, but QB.chat.connect says "Not implemented outside of web yet".

Is there any workaround for that?

**Comment by soulfly** [comment]
It should work from Node.js, we already have some working apps

can you provide more details where do you get this error

**Comment by ketanbhatt** [comment]
So I am trying to do this, 

`
QB.chat.connect({jid: '201278_55sdsd3434d3412068d000c6f@muc.chat.quickblox.com', password: 'password'}, function(err, roster) {
      console.log("connected")
})
`

But I get the error message that "This function isn't supported outside of the browser (...yet)"
I traced it back to the `qbchat.js` file in the quickblox SDK, made isBrowser true there, but then there is an error from 'Strophe'

**Comment by ketanbhatt** [comment]
I searched and found that Strophe is a XMPP library for Javascript, that enables applications to use XMPP on the web, and quickblox uses it too. 
But I need to listen to the channels in real time from my node backend, and since `window != browser`, Strophe wont work.

Any help would be appreciated, need it badly for my application

**Comment by alexbassy** [comment]
There's no support for chat in the Node.js version of the QB library, unfortunately. For internal stuff we used the 'node-xmpp-client' module - when provided with the host, jid, password and port (can grab from the config file of this repo) - it works right out of the box. Though, it is a different API.

**Comment by ketanbhatt** [comment]
Yes, that is what i thought of doing too. 
Thank you for guiding in the right direction, I will try to connect with that, will post if I face any issue. 
Thanks a lot

**Comment by soulfly** [comment]
You can find some useful helpers here https://github.com/QuickBlox/Status/blob/master/helpers/chat.js

**Comment by ketanbhatt** [comment]
Hey, I tried making node-xmpp-client work, but I am unable to. I looked into how QB's JS SDK is using it but couldn't find node-xmpp anywhere there, or the implementation. Could you please help?

**Comment by soulfly** [comment]
https://github.com/QuickBlox/Status/blob/master/package.json#L33

**Comment by ketanbhatt** [comment]
Both the links you gave don't exist :'D

**Comment by soulfly** [comment]
You mean this link returns 404 for you?

https://github.com/QuickBlox/Status/blob/master/package.json#L33

**Comment by ketanbhatt** [comment]
Yes, I changed "status" in the link to "quickblox-status-checker-2.0", then it works:

https://github.com/QuickBlox/quickblox-status-checker-2.0/blob/master/package.json#L33

I was able to connect to chat and receiving messages now. Struggling for getting online users in a group.

**Comment by mitaltank** [comment]
quickblox login and new app id etc. create and app id is user my code and connection success. but chat is not work and error is "Uncaught This function isn't supported outside of the browser (...yet)"

**Comment by dimaspirit** [comment]
@mitaltank what's the version of sdk?

**Comment by mitaltank** [comment]
v1.17.2

**Comment by dimaspirit** [comment]
You need to upgrade the SDK.
https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.3.0

**Comment by mitaltank** [comment]
ok, thank you.

**Comment by mitaltank** [comment]
new upgrade SDK and new appID use my code. connection success but error "Uncaught Error: The method "jidOrUserId" may take jid or id(…)".

**Comment by dimaspirit** [comment]
Could you share your snippet and what are you pass (typeof also) ?

**Comment by mitaltank** [comment]
var QBApp = {
  appId: 50855,
  authKey: 'rE9yv27DevsLGyR',
  authSecret: 'ZFwsym7tdn6-B9y'
};

var config = {
  chatProtocol: {
    active: 2
  },
  debug: {
    mode: 1,
    file: null
  },
  stickerpipe: {
    elId: 'stickers_btn',

    apiKey: '847b82c49db21ecec88c510e377b452c',

    enableEmojiTab: false,
    enableHistoryTab: true,
    enableStoreTab: true,

    userId: null,

    priceB: '0.99 $',
    priceC: '1.99 $'
  }
};

var QBUser1 = {
        id: 21587786,
        name: 'quickuser',
        login: 'admin',
        pass: '	admin@123'
    }, 
    QBUser2 = {
        id: 21587803,
        name: 'bloxuser',
        login: 'user',
        pass: 'user@123'
    };

QB.init(QBApp.appId, QBApp.authKey, QBApp.authSecret, config);

**Comment by mitaltank** [comment]
this is my config file and add my Credentials in this file.

**Comment by dimaspirit** [comment]
No, please provide what exactly are you doing? Which method is get error and what are you pass there?
For example, you try to send a msg.
```
QB.chat.send(123123) // Get error
```

**Comment by mitaltank** [comment]
function sendMessage(text, attachmentFileId) {
    stickerpipe.onUserMessageSent(stickerpipe.isSticker(text));

    var msg = {
        type: currentDialog.type === 3 ? 'chat' : 'groupchat',
        body: text,
        extension: {
            save_to_history: 1,
        },
        markable: 1
    };
  
    if(attachmentFileId !== null){
        msg['extension']['attachments'] = [{id: attachmentFileId, type: 'photo'}];
    }

    if (currentDialog.type === 3) {
        opponentId = QB.chat.helpers.getRecipientId(currentDialog.occupants_ids, currentUser.id);
        
        QB.chat.send(opponentId, msg);

        $('.list-group-item.active .list-group-item-text')
            .text(stickerpipe.isSticker(msg.body) ? 'Sticker' : msg.body);

        if(attachmentFileId === null){
            showMessage(currentUser.id, msg);
        } else {
            showMessage(currentUser.id, msg, attachmentFileId);
        }
    } else {
        QB.chat.send(currentDialog.xmpp_room_jid, msg);
    }

    // claer timer and send 'stop typing' status
    clearTimeout(isTypingTimerId);
    isTypingTimeoutCallback();

    dialogsMessages.push(msg);
}

**Comment by mitaltank** [comment]
send text method

**Comment by mitaltank** [comment]
QB.chat.send(opponentId, msg);

**Comment by dimaspirit** [comment]
Could you show logs ?

**Comment by mitaltank** [comment]
![log](https://cloud.githubusercontent.com/assets/24246062/21095945/b635142e-c083-11e6-9839-4a0b41588360.png)

**Comment by dimaspirit** [comment]
And where is the error?

**Comment by mitaltank** [comment]
message send that time error "Uncaught TypeError: Cannot read property 'onUserMessageSent' of null(…)"


![log2](https://cloud.githubusercontent.com/assets/24246062/21096330/83aa8712-c085-11e6-9676-a2514710ee53.png)

**Comment by dimaspirit** [comment]
It's a stickerpipe error. 
Before start chatting, you need to join in group or create a chat with someone. Are you made this case?

**Comment by mitaltank** [comment]
how to set chat someone?

**Comment by mitaltank** [comment]
hello. in quickblox multiple  admin side user and multiple client side user chat ?

**Comment by dimaspirit** [comment]
http://quickblox.com/developers/Javascript Looking information here.

> hello. in quickblox multiple admin side user and multiple client side user chat ?

What do you mean?

**Comment by mitaltank** [comment]
example 
1) "user1" chat is "user2"     
2) "user3" chat is "user4"
3) "user5" chat is "user6"
4) "user7" free

so that  time "user8" request for chat and "user8" chat to "user7".

**Comment by Vladlukhanin** [comment]
You ask about our chat (http://quickblox.github.io/quickblox-javascript-sdk/samples/chat/) or admin panel (https://admin.quickblox.com)?
Sorry, but we don't understand your problem. Try to describe your issue.
