### ISSUE TITLE
Replacing the existing video stream of current call with screen sharing video stream. 

### ISSUE THREAD

**Issue by utkarshmaximess** [QuickBlox/quickblox-javascript-sdk#221]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Sorry, not screen sharing doesn't add to SDK, also you can't change stream online.
