### ISSUE TITLE
quickblox.min.js for 2.5.2 is not minified

### ISSUE THREAD

**Issue by anton87gp** [QuickBlox/quickblox-javascript-sdk#227]
**quickblox.min.js** for 2.5.2 doesn't seem to be minified and contains sourcemaps, in the repo as well as embedded from cloudflare.
As result file size is 8.2MB vs 1.3MB for previous 2.5.1 (1.8MB vs. 380KB gzipped).

Thanks!

**Comment by dimaspirit** [comment]
@anton87gp , thanks a lot for the issue.
Fixed in the patch [2.5.3](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.5.3)

**Comment by anton87gp** [comment]
@dimaspirit Many thanks for such quick response and fix!
