### ISSUE TITLE
Creating a user with non-numeric number external_user_id says "External user id must be less than 11 characters"

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#23]
The external user id can only be an integer but the error "External user id must be less than 11 characters" doesn't correctly describe why the external user id is invalid if I enter in a non-numeric value.  In the admin interface there is client side validation to test if it is a number.  If it is not a number it will say 'Please enter a valid number.'

So... if I try to create or update a user with a non-numeric value using the API it should say "External user id must be a number."

**Comment by dimaspirit** [comment]
Hi, yep, you are right)
We are working on this issue and thinking how to upgrade id of users.
