### ISSUE TITLE
How to add small window frame in the right bottom of the calling user in video calling

### ISSUE THREAD

**Issue by pankajmanay** [QuickBlox/quickblox-javascript-sdk#230]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Sorry, it's not the issue of SDK.
You can attach the stream to any element.
https://quickblox.com/developers/Sample-webrtc-web#Attach_stream_on_the_page
Sure this ref. will help you https://developer.mozilla.org/en-US/docs/Web/HTML, https://developer.mozilla.org/en-US/docs/Web/CSS
