### ISSUE TITLE
Not getting Users list on click of Create Dialog button

### ISSUE THREAD

**Issue by sbchamadiya** [QuickBlox/quickblox-javascript-sdk#239]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Hi, are you talking about some sample?

**Comment by sbchamadiya** [comment]
Yes,That error have been solved.Now i want to get user full name instead of
login ID and I want to change the view of chat conversion.How it is
possible?

**Comment by dimaspirit** [comment]
This will help you with users https://quickblox.com/developers/Sample-users-javascript#Retrieve_users

What about the view - it's simple HTML, CSS. Change as you want.

**Comment by Vladlukhanin** [comment]
Verify you settings in an admin panel before. "Allow to retrieve a list of users" must be checked.

**Comment by sbchamadiya** [comment]
Ok.Thanks for help.But now issue is i am not getting user full name while
chat.

**Comment by dimaspirit** [comment]
You can retrieve all user info by ID.
Look up quickblox documentation

**Comment by sbchamadiya** [comment]
I have read documentation but i can't understand where to place the
snippet.Please help!

**Comment by sbchamadiya** [comment]
I have a query in quickblox regarding attachment.Query is as below :--

1) How i will identify attachment type i.e image or audio or video?
2) Can i get attachment type on basis of attachment ID?

Response fast with SOLUTION...☺
