### ISSUE TITLE
debug setting is not honored and fills the debug console with "[QBChat] ...."

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#24]
The debug check is commented out here:
https://github.com/QuickBlox/quickblox-javascript-sdk/blob/master/quickblox.js#L2957

and... commented out here:
https://github.com/QuickBlox/quickblox-javascript-sdk/blob/master/quickblox.js#L1076

Perhaps there should also be a setting for debug levels: none, informational, verbose, etc

**Comment by soulfly** [comment]
You are right, thanks for the feedback

will enable this in the upcoming release

**Comment by soulfly** [comment]
This is fixed in 1.14.0

http://quickblox.com/developers/Javascript#Framework_changelog
