### ISSUE TITLE
doc outdated for QB.chat.muc.join

### ISSUE THREAD

**Issue by shide1989** [QuickBlox/quickblox-javascript-sdk#240]
Hi guys,
can you check the QB.chat.muc.join documentation ? 
https://quickblox.com/developers/Web_XMPP_Chat_Sample#Chat_in_dialog

i got the error 'cannot read length of undefined' when using childNodes,
and instead i found this code in the code samples : 
```
               function dialogJoinCb(stanza) {
                    expect(stanza).not.toBeNull();
                    done();
                }

                QB.chat.muc.join(dialog.xmpp_room_jid, dialogJoinCb);
```

**Comment by dimaspirit** [comment]
Hi, thanks for the report. We will make a handle for an answer to make him more useful and will fix this case.

**Comment by vadimkhmyrovqb** [comment]
@shide1989 This issue been fixed. Thanks again for the report.
