### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.socket.send')

### ISSUE THREAD

**Issue by developercakephp** [QuickBlox/quickblox-javascript-sdk#246]
Hi,

I an using ionic with quickblox i am getting below error in ios. android its fine. 

> Error in Success callbackId: iosrtcPlugin1626715567 : TypeError: undefined is not an object (evaluating 'this.socket.send')

![screen](https://cloud.githubusercontent.com/assets/3120484/26528203/75548a02-43c3-11e7-9e23-3798feb2433c.png)

**My Environment:**

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.3.1
    Ionic Framework                 : ionic-angular 2.2.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by soulfly** [comment]
- Can you expand the 'TypeError' block, what's the stack trace there
- did you connect properly all this stuff for iOS? https://quickblox.com/developers/Sample-webrtc-cordova#Integration_details

**Comment by developercakephp** [comment]
![screen2](https://cloud.githubusercontent.com/assets/3120484/26571418/849ba286-4533-11e7-86ad-b9f1ab24566b.png)

**Comment by developercakephp** [comment]
Yes i have connected properly. and also follow all step for  iosrtc integration define in Docs.
it is working fine in android, but not in IOS

**Comment by soulfly** [comment]
It's definitely something wrong with iosrtc plugin..
We are going to fully replicate ionic like environment and get back to you

**Comment by soulfly** [comment]
@developercakephp do you use IONIC NATIVE in your app?

**Comment by developercakephp** [comment]
Yes I am using native ionic. I had share above my project environment details

**Comment by developercakephp** [comment]
i am waiting for your reply. have you reproduce it.

**Comment by dimaspirit** [comment]
Hi, could you check how many times you call `QB.init` method?

**Comment by developercakephp** [comment]
I called it one time when device ready.

**Comment by soulfly** [comment]
@developercakephp  how do you connect QuickBLox to your app?
via HTML <script> tag or via npm/TypeScript file, e.g. app.component.ts ?

**Comment by developercakephp** [comment]
See attached index file. created provider for quickblox and import that class in app.component.ts. in app.component.ts created an object of it. in quickblox provider I have called 

> QB.init(this.QBApp.appId, this.QBApp.authKey, this.QBApp.authSecret);

![index](https://cloud.githubusercontent.com/assets/3120484/26638687/5d67a404-4640-11e7-8c52-10a9669104e0.png)

**Comment by developercakephp** [comment]
Any success ?

**Comment by niccolofanton** [comment]
I'm having the same problem, have you solved somehow?

**Comment by vadimkhmyrovqb** [comment]
@developercakephp  We have not optimized our SDK to work with Ionic yet. We plan to support it in future but no plans for the nearest time.
