### ISSUE TITLE
How to switch between Multiple cameras during video calling?

### ISSUE THREAD

**Issue by swati-bothra** [QuickBlox/quickblox-javascript-sdk#249]
Can anyone please guide me how to switch camera during the video call if I have multiple cameras?

**Comment by swati-bothra** [comment]
Is there any update regarding the issue?

**Comment by dimaspirit** [comment]
@swati-bothra , we haven't this feature.

**Comment by zonaibasiddiqui** [comment]
do we have this feature in latest build ?

**Comment by Vladlukhanin** [comment]
Not in the latest release and not in the next, unfortunately... But we have a task to implement switch between cameras during a call if it will be possible.

**Comment by db2crush** [comment]
Hi, @Vladlukhanin 
this feature applied ?
