### ISSUE TITLE
Issue with checking unread messages on dialogs

### ISSUE THREAD

**Issue by lvl99** [QuickBlox/quickblox-javascript-sdk#251]
**Environment details**
*(Operating system, browser information, SDK version)*
Google Chrome 58.0.3029.110 (64-bit)
Mac OS X 10.12.5

**Did this work before?**
Yes, this did work before

**Expected behavior**
When I use the `quickblox.chat.message.unreadCount` endpoint with `chat_dialog_ids` specified as an array, I should receive an object with the dialogs' IDs as the keys and the accurate `unread_messages_count` for each of those dialogs.

**Actual behavior**
In the return object I receive a `0` value for each dialog I'm attempting to check. However when I get the dialogs from the `quickblox.chat.dialogs.list` endpoint, the `unread_messages_count` values are correct.

**Steps to reproduce the behavior**
1. `curl -X GET -H "QB-Token: ***user token***" https://api.quickblox.com/chat/Message/unread?chat_dialog_ids=***dialog id***`

```
<?xml version="1.0" encoding="UTF-8"?>
<items type="array">
  <item>
    <chat_dialog_id>***dialog id***</chat_dialog_id>
    <count type="integer">0</count>
  </item>
  <total type="integer">10</total>
</items>
```

2. `curl -X GET -H "QB-Token: ***user token***" https://api.quickblox.com/chat/Dialog.json?_id=***dialog id***`

```
{
  "total_entries":1,
  "skip":0,
  "limit":100,
  "items":[
    {
      "_id":"***dialog id***",
      "created_at":"2017-06-12T13:05:27Z",
      "data":{

      },
      "last_message":"Test",
      "last_message_date_sent":1497342266,
      "last_message_user_id":999999999,
      "name":"Testing chat message notification",
      "occupants_ids":[
        999999998,
        999999999
      ],
      "photo":null,
      "type":2,
      "updated_at":"2017-06-13T08:24:27Z",
      "user_id":999999998,
      "xmpp_room_jid":"***dialog id***@muc.chat.quickblox.com",
      "unread_messages_count":3
    }
  ]
}
```

**Any others comments?**
Please ensure your documentation has good examples for multiple use cases.

**Comment by lvl99** [comment]
After checking today, it seems that it's back to working again. Thanks 👍

**Comment by lvl99** [comment]
OK, it's broken again. We're also on an enterprise server now.

**Comment by dimaspirit** [comment]
@lvl99 It seems as an issue on the backend, If you are enterprise write to our support department and we will fix.
