### ISSUE TITLE
Quickblox messages are not getting saved to history,the messages are delivered to other user but not view able in dialog history or not getting saved

### ISSUE THREAD

**Issue by ashish-procentris** [QuickBlox/quickblox-javascript-sdk#254]
Quickblox messages are not getting saved to history,the messages are delivered to other user but not view able in dialog history or not getting saved

**Comment by Vladlukhanin** [comment]
Don't forget about the parametr [save_to_history](https://quickblox.com/developers/Web_XMPP_Chat_Sample#Chat_in_dialog)

**Comment by ashish-procentris** [comment]
yes sir already added and using the parameter ,its like some messages are getting saved some are not...
the percentage of messages not getting saved is very high

**Comment by ashish-procentris** [comment]
also using latest sdk 2.6.0 and startup tier account

**Comment by Vladlukhanin** [comment]
Do had some errors in console from our JS SDK or some other?

**Comment by ashish-procentris** [comment]
no errors

**Comment by Vladlukhanin** [comment]
Send a few messages and check them in your admin panel.

**Comment by ashish-procentris** [comment]
![chat-error1](https://user-images.githubusercontent.com/29539268/27373040-5be08eee-5684-11e7-8298-03ed134b49f4.png)
![chaterror-2](https://user-images.githubusercontent.com/29539268/27373041-5be464ce-5684-11e7-80f4-e9fbfcc6cd54.png)
![chaterror-3](https://user-images.githubusercontent.com/29539268/27373038-5bd8cc18-5684-11e7-873e-3ccb71458711.png)
![chaterror-4](https://user-images.githubusercontent.com/29539268/27373039-5bd91cf4-5684-11e7-990a-45bb2c31815c.png)

no error in console ,the last message can be seen in dialogs last message field but not in the dialog history only the first message is saved rest after that is not saved

**Comment by Vladlukhanin** [comment]
You provided screenshot where I can see just one message (latest from from chat on second image and first from chat on third image), not all history.

**Comment by ashish-procentris** [comment]
![chaterror-6](https://user-images.githubusercontent.com/29539268/27375199-0960445e-568c-11e7-9dcc-7f1af2ce3172.png)

sir..this is the screenshot you are talking about ?..it has only one message saved

**Comment by ashish-procentris** [comment]
![chaterror-7](https://user-images.githubusercontent.com/29539268/27375271-46097f7e-568c-11e7-8bf4-bc56a3eeea3d.png)
this is dialog ,the last message field contains the last message text but not in history

**Comment by Vladlukhanin** [comment]
Could you provide a snippet of code where you send the message?

**Comment by ashish-procentris** [comment]
![codesnippet](https://user-images.githubusercontent.com/29539268/27375923-3935a0c8-568e-11e7-962f-62ffae3f744a.png)
please find the code snippet to send message

**Comment by Vladlukhanin** [comment]
Any other custom parameters must be contained in "extension"

```
...

var msg = {
  type: type,
  body: val,
  extension: {
    save_to_history: 1,
    dialog_id: dialog_id,
    date_sent: time,
    custom_param_1: '111',
    custom_param_2: '222',
    custom_param_3: '333'
  },
  markable: 1
}

msg.id = QB.chat.send(jid, msg);
  
return msg;

...
```

**Comment by ashish-procentris** [comment]
ok let me try this code

**Comment by ashish-procentris** [comment]
![messagesnippet](https://user-images.githubusercontent.com/29539268/27379463-f1d37010-5698-11e7-9e06-7b2c58266231.png)
sir its still the same

**Comment by Vladlukhanin** [comment]
What will console.log(msg) show before the callback(msg)?

**Comment by ashish-procentris** [comment]
![console-msg](https://user-images.githubusercontent.com/29539268/27384531-cdf7b1ec-56ac-11e7-86dd-63a14da936b1.png)
here you go the console log of 2 messages sent out of which only the first is saved second is not

**Comment by Vladlukhanin** [comment]
try to put "jid_or_user_id" in "extension"

**Comment by ashish-procentris** [comment]
![log1](https://user-images.githubusercontent.com/29539268/27385429-4bc4e0c4-56b0-11e7-8ae6-b947aa16b3b6.png)
![log2](https://user-images.githubusercontent.com/29539268/27385430-4bc66cfa-56b0-11e7-9194-e2342e9c9c22.png)

![log3](https://user-images.githubusercontent.com/29539268/27385565-c5c0e36e-56b0-11e7-8c1e-9c8d3083ba78.png)

sir still the same, the first message is saved but not second one

**Comment by Vladlukhanin** [comment]
possible properties for message, for QB.chat.send(jidOrUserId, messages): type, body, extension, markable

You can try to start [our chat sample](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat) with your [app configs](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/samples/chat/js/QBconfig.js#L4) and verify history. I think that you have some problem in code.

**Comment by ashish-procentris** [comment]
ok sure ill let you know

**Comment by Vladlukhanin** [comment]
ok) I want to say that I verified our samples and [q-municate dev](https://qmdev.quickblox.com) and didn't find any problems whith history. These apps use a production server to

**Comment by ashish-procentris** [comment]
we are using free version could somehow that be the reason??

**Comment by Vladlukhanin** [comment]
No, any limitations)

**Comment by sonid9921** [comment]
@ashish-procentris, did you get it working? I am facing the same error. But for us, it's a very less number of messages not appearing in history. Any help will be appreciated.
