### ISSUE TITLE
After 50/60 seconds the connection goes down

### ISSUE THREAD

**Issue by lucav** [QuickBlox/quickblox-javascript-sdk#255]
**Environment details**
*(Operating system, browser information, SDK version)*
PC mobile: Windows 10 + Firefox 54.0 + 2.6.0 sdk
Smartphone: LineageOS 14.1 (Android 7.1.2) + Firefox 54.0 + 2.6.0 sdk

**Did this work before?**
NO

**Expected behavior**
It should works more then 60 seconds.

**Actual behavior**
After 50/60 seconds the connection goes down.

**Logs**
Console logs from browser:

[QBWebRTC]: onCall. UserID:29046377. SessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed  quickblox.min.js:45:13966
[QBWebRTC]: _createPeer, iceServers: {"iceServers":[{"url":"stun:stun.l.google.com:19302","urls":"stun:stun.l.google.com:19302"},{"url":"stun:turn.quickblox.com","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"stun:turn.quickblox.com"},{"url":"turn:turn.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=udp"},{"url":"turn:turn.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=tcp"},{"url":"turn:turnsingapor.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnsingapor.quickblox.com:3478?transport=udp"},{"url":"turn:turnsingapore.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnsingapore.quickblox.com:3478?transport=tcp"},{"url":"turn:turnireland.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnireland.quickblox.com:3478?transport=udp"},{"url":"turn:turnireland.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnireland.quickblox.com:3478?transport=tcp"}]}  quickblox.min.js:45:13966
[QBWebRTC]: RTCPeerConnection init. userID: 29046377, sessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed, type: answer  quickblox.min.js:45:13966
[QBWebRTC]: _startAnswerTimer  quickblox.min.js:45:13966
Using more than two STUN/TURN servers slows down discovery quickblox.min.js:45
Using five or more STUN/TURN servers causes problems quickblox.min.js:45
onaddstream is deprecated! Use peerConnection.ontrack instead.  quickblox.min.js:45
[QBWebRTC]: onCall. UserID:29046377. SessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed  quickblox.min.js:45:13966
ok permessi  remotecall-start.js:248:5
[QBWebRTC]: Accept, extension: {}  quickblox.min.js:45:13966
[QBWebRTC]: _clearAnswerTimer  quickblox.min.js:45:13966
[QBWebRTC]: _startWaitingOfferOrAnswerTimer, timeout: 50.467  quickblox.min.js:45:13966
[QBWebRTC]: _createPeer, iceServers: {"iceServers":[{"url":"stun:stun.l.google.com:19302","urls":"stun:stun.l.google.com:19302"},{"url":"stun:turn.quickblox.com","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"stun:turn.quickblox.com"},{"url":"turn:turn.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=udp"},{"url":"turn:turn.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=tcp"},{"url":"turn:turnsingapor.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnsingapor.quickblox.com:3478?transport=udp"},{"url":"turn:turnsingapore.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnsingapore.quickblox.com:3478?transport=tcp"},{"url":"turn:turnireland.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnireland.quickblox.com:3478?transport=udp"},{"url":"turn:turnireland.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turnireland.quickblox.com:3478?transport=tcp"}]}  quickblox.min.js:45:13966
[QBWebRTC]: RTCPeerConnection init. userID: 29046377, sessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed, type: offer  quickblox.min.js:45:13966
Using more than two STUN/TURN servers slows down discovery quickblox.min.js:45
Using five or more STUN/TURN servers causes problems quickblox.min.js:45
onaddstream is deprecated! Use peerConnection.ontrack instead.  quickblox.min.js:45
[QBWebRTC]: 'setRemoteSessionDescription' success  quickblox.min.js:45:13966
[QBWebRTC]: getAndSetLocalSessionDescription success  quickblox.min.js:45:13966
[QBWebRTC]: _startDialingTimer, dialingTimeInterval: 5000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 0  quickblox.min.js:45:13966
RTCPeerConnection.getLocalStreams/getRemoteStreams sono deprecati. Al loro posto utilizzare RTCPeerConnection.getSenders/getReceivers.  quickblox.min.js:45:6055
[QBWebRTC]: onIceConnectionStateCallback: checking  quickblox.min.js:45:13966
[QBWebRTC]: onIceConnectionStateCallback: connected  quickblox.min.js:45:13966
[QBWebRTC]: onCall. UserID:29046377. SessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed  quickblox.min.js:45:13966
[QBWebRTC]: onIceCandidates. UserID:29046377. SessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed. ICE candidates count: 40  quickblox.min.js:45:13966
[QBWebRTC]: Error on 'addIceCandidate': InvalidStateError: setRemoteDescription needs to called before addIceCandidate quickblox.min.js:45:14093
[QBWebRTC]: _dialingCallback, answerTimeInterval: 5000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 10000  quickblox.min.js:45:13966
[QBWebRTC]: onIceConnectionStateCallback: disconnected  quickblox.min.js:45:13966
[QBWebRTC]: _startWaitingReconnectTimer, timeout: 30000  quickblox.min.js:45:13966
[QBWebRTC]: onIceConnectionStateCallback: connected  quickblox.min.js:45:13966
[QBWebRTC]: _clearWaitingReconnectTimer  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 15000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 20000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 25000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 30000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 35000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 40000  quickblox.min.js:45:13966
[QBWebRTC]: _dialingCallback, answerTimeInterval: 45000  quickblox.min.js:45:13966
[QBWebRTC]: onStop. UserID:29046377. SessionID: ece80ceb-5dc0-49d0-8c27-19971882f7ed  quickblox.min.js:45:13966
[QBWebRTC]: Stop, extension: {}  quickblox.min.js:45:13966
[QBWebRTC]: _close  quickblox.min.js:45:13966
[QBWebRTC]: _clearDialingTimer  quickblox.min.js:45:13966
[QBWebRTC]: onIceConnectionStateCallback: closed  quickblox.min.js:45:13966
[QBWebRTC]: All peer connections closed: true  quickblox.min.js:45:13966
[QBWebRTC]: waitingOfferOrAnswerTimeoutCallback

**Steps to reproduce the behavior**
You can connect on my web site (i tell you in private message if you want).

**Any others comments?**
The video call works, but after 50/60 the connection goes down. Seems that the calling side doesn't see the accept from the other side (but it accept because both side receives the audio/video stream).

**Comment by binhdxnexle** [comment]
How do you resolve it @dimaspirit ? I have the same issue.

**Comment by tojotewve** [comment]
Any Fix for above issue? I have the same issue.

**Comment by rajnishp** [comment]
Refer to [click here] (https://github.com/tornadoweb/tornado/issues/1070)

Nginx as a Websocket proxy and has a default value of 1 minute for proxy_read_timeout setting. Increased that to a sufficiently large value and my problem was fixed. :)
