### ISSUE TITLE
Cannot receive group chat dialogs where no-one has posted a message yet (i.e. `last_message_date_sent` is empty)

### ISSUE THREAD

**Issue by lvl99** [QuickBlox/quickblox-javascript-sdk#256]
**Environment details**
Google Chrome 59.0.3071.115
Quickblox Javascript SDK 2.5.1

**Did this work before?**
I don't think so.

**Expected behaviour**
To receive all group chat dialogs for a user, even if a group chat has had no messages sent yet

**Actual behaviour**
I retrieve only dialogs that have had a message sent, probably due to the `last_message_date_sent` sorting property.

**Steps to reproduce the behaviour**
1. Create a new group chat dialog between two users
2. Get the list of dialogs for one of the users: `curl -X GET -H "QB-Token: ***TOKEN***" -H "Host: api.quickblox.com" https://apimitchjobs.quickblox.com/chat/Dialog.json`
3. The newest group chat dialog created at step 1 won't be in the returned list at step 2

**Any other comments?**
If you could add the sorting fields `created_at` and `updated_at` to the `sort_desc` and `sort_asc` values, then that might work better for my use case, otherwise I have no idea how to get the full list of dialogs.

Ideally, supporting multiple columns to sort/order the return results would be good too:
```
// Example of multi-column sort which should be evaluated in left-to-right order
{
  "sort_desc": ["last_message_date_sent", "updated_at", "created_at"]
}
```

**Comment by vadimkhmyrovqb** [comment]
@lvl99 Hi, this issue is not related to Javascript SDK, but rather to API functionality. Regarding API, please refer to this documentation https://quickblox.com/developers/Chat .
