### ISSUE TITLE
Bower package for quickblox is >50MB

### ISSUE THREAD

**Issue by lvl99** [QuickBlox/quickblox-javascript-sdk#257]
Kind of insane, isn't it?

<img width="828" alt="screen shot 2017-06-28 at 14 55 57" src="https://user-images.githubusercontent.com/238480/27637980-ee624540-5c11-11e7-8056-0e3c0fc650e6.png">

**Comment by dimaspirit** [comment]
@lvl99 , it's something strange.
I don't understand where Bower gets 54MB.
https://i.gyazo.com/4fc625da42ff06dac44000b57dfb0e91.png

Could you explaine this?

**Comment by lvl99** [comment]
It's crazy, I don't understand it either. Unless bower is retrieving the whole git repo history as well? That's the only thing I could think of, but looking at the cached files they don't add up to ~60MB either:

![image](https://user-images.githubusercontent.com/238480/27691362-12b2497c-5ce4-11e7-91f1-8071f5366cfa.png)

**Comment by dimaspirit** [comment]
Anyway, Bower recommends use Yarn. 
I will try to understand, but I think it's Bower sys files/information.
