### ISSUE TITLE
Push Notifications with Ionic 3

### ISSUE THREAD

**Issue by gonzag** [QuickBlox/quickblox-javascript-sdk#264]
**Environment details**
*(Operating system, browser information, SDK version)*
Android with Ionic 3 Framework

**Did this work before?**
No

**Expected behavior**
Send Push Notification to Android devices with Firebase

**Actual behavior**
Notifications appear in the admin panel of Quickblox as sent, but never arrives to the devices.
But inside Firebase, I'm able to send push notifications and those arrives well.

**Any others comments?**
The configuration in my phone appears to be fine, because I'm able to send push notification to iOS devices from my Android phone, and those are arriving well.
Then I implemented in the generated Android project of my ionic app, this guide: 
https://quickblox.com/developers/SimpleSample-messages_users-android
But in the BroadcastReceiver I never get anything. Also, with this configuration, I'm still able to get push notifications from Firebase page.
Also I attempted to send notifications from the admin panel of quickblox, but those never arrives to my Android devices and in the log appears as sent.

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
