### ISSUE TITLE
Bad TImestamp ,Unprocessable Entity

### ISSUE THREAD

**Issue by ashish-procentris** [QuickBlox/quickblox-javascript-sdk#266]
i am getting this unique issues on a specific machine it is Unprocessable Entity with error code 422 and error base as bad timestamp,can anybody guide me as to how to solve this
![01ea5bb51c0de12020c2001f3a77c314cee2a6d071a01cbc93 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/29539268/29259852-61204e2e-80e3-11e7-86d9-5c9d64c52691.jpg)

**Comment by Vladlukhanin** [comment]
@ashish-procentris , the screenshot is very small and has a bad quality. Can you make and show an other?

**Comment by ashish-procentris** [comment]
![quickblox-badtimestamp](https://user-images.githubusercontent.com/29539268/29260883-33d7d886-80ea-11e7-8a16-8df8a33cb208.png)
hope this helps

**Comment by Vladlukhanin** [comment]
ok, can you show code snippet where you create session?

...and we need to know other info from our markdown questions:
**Environment details**
*(Operating system, browser information, SDK version)*

**Comment by ashish-procentris** [comment]
![image](https://user-images.githubusercontent.com/29539268/29261196-f3c9dfee-80eb-11e7-8441-b0064bfc45ea.png)
operating system windows 7 on all browser for this machine..actually this is only for this specific machine

**Comment by ashish-procentris** [comment]
SDK 2.6.0 JSSDk

**Comment by Vladlukhanin** [comment]
Check your local time, it's actual for your region?

**Comment by ashish-procentris** [comment]
i didnt got you??can you explain me in detail

**Comment by Vladlukhanin** [comment]
In your snippet code all are right. Set actual time in your Windows OS, because of your local time is incorrect you got error - bad timestamp.

**Comment by ashish-procentris** [comment]
ok it means for example if i am from india and my machine timezone is from another region that this error occurs?

**Comment by Vladlukhanin** [comment]
The difference in time on your computer (your OS) and your local time (your country/place) should not be more than one hour

**Comment by ashish-procentris** [comment]
ok,but then how this other chat gaints handle this issuse like facebook,watsapp, skype or yahoo...in production enviornment we dont have control on user machines..

**Comment by ashish-procentris** [comment]
any comments on this?

**Comment by dimaspirit** [comment]
It's requirements from our server.
We don't know how another platforms handle this case.
