### ISSUE TITLE
quickblox api taking time for israel location

### ISSUE THREAD

**Issue by ashish-procentris** [QuickBlox/quickblox-javascript-sdk#271]
i need to know the servers location or information of quickblox..for free tier some of our users located in Israel are facing speed issues

**Comment by dimaspirit** [comment]
@ashish-procentris , hi, free servers are based in the USA.

**Comment by ashish-procentris** [comment]
OK.. so what about paid instances can i get detail information about the server region wise ?? No of servers per region??

**Comment by dimaspirit** [comment]
Yiu could contact with sales dept. for this https://quickblox.com/enterprise/
