### ISSUE TITLE
Share Remote Screen in Chrome

### ISSUE THREAD

**Issue by Parmenione** [QuickBlox/quickblox-javascript-sdk#272]
Hi,
I'd like to share screen window by chrome.
I'm using an extension (like https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk) and use getScreenId to retrieve source id and constraints, then i create an offer and set local description but never happen.
I see that the remote Android freeze video stream but it doesn't show the screen video instead of I see it in local view container.
How could I solve it?

I wrote the steps:
-> call getScreenId
-> after retrieve id call getUserMedia with new constraints
-> then I have the new Media stream
-> get the peer and remove previous streams
-> attach new stream at peer and dom video
-> then I call createOffer() that return offer

**Comment by dimaspirit** [comment]
We will research this case soon.

**Comment by vadimkhmyrovqb** [comment]
@Parmenione As an update to this request, I would like to inform you that we are going to develop support of screen sharing in web platform in Q3 2019.
