### ISSUE TITLE
frequently getting 502 error

### ISSUE THREAD

**Issue by ashish-procentris** [QuickBlox/quickblox-javascript-sdk#273]
i am frequently getting 502 bad gateway error since 3 4 days? any details

**Comment by Vladlukhanin** [comment]
Some updates have been on our server.

**Comment by ashish-procentris** [comment]
ok

**Comment by ashish-procentris** [comment]
any estimates till when would the services be up and running

**Comment by Vladlukhanin** [comment]
try in half an hour or an hour
