### ISSUE TITLE
When I upload final code of webrtc on server than It cause problem when I am trying to call with my peer

### ISSUE THREAD

**Issue by hitesh009** [QuickBlox/quickblox-javascript-sdk#274]
** Comments ***
I developed one system using "quickblox webrtc". Locally I tested everything it works fine but when I upload on a server than calling is not working. I am using them file app.js. I did not change anything just I changed the flow of calls. So please anybody knows what I have to do please suggest me. It may be server side issue or maybe on quickblox issue.

**Environment details**
I am using nodeJS 
*(Operating system, browser information, SDK version)*
upload code on iPage server even I also Try on AmazoneEC2 but not running

**Expected behavior**
Solving this issue

**Actual behavior**
When I call to peer then it gives an error or sometimes not connecting, sometimes automatically reject.

![quickblox caller](https://user-images.githubusercontent.com/6704014/31233207-b3e35404-aa09-11e7-9088-b10899a6bd25.PNG)
![quickblox recivaer](https://user-images.githubusercontent.com/6704014/31233213-b48f5420-aa09-11e7-8d66-ab131b4193e5.PNG)

**Comment by dimaspirit** [comment]
Could you provide what is means 'to call with my peer'?
