### ISSUE TITLE
JS error when passing an extraParams object with a null value when making a call

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#28]
The error:
Uncaught TypeError: Cannot convert undefined or null to object

How to reproduce:
````javascript
var extraParams = {
    someProperty: null
};
QB.webrtc.call(calleeId, isOnlyAudio ? 'audio' : 'video', extraParams);
````

The error is caused when it expects obj to not be null in _JStoXML:
````javascript
WebRTCProxy.prototype._JStoXML = function(title, obj, msg) {
  var self = this;
  msg.c(title);
  Object.keys(obj).forEach(function(field) {
    if (typeof obj[field] === 'object')
      self._JStoXML(field, obj[field], msg);
    else
      msg.c(field).t(obj[field]).up();
  });
  msg.up();
};
````

The workaround:
Set the value to an empty string instead of null.

**Comment by soulfly** [comment]
What is the reason to send 'null' ?

null means nothing, so the following 2 cases are the same for me

    var extraParams = {
        someProperty: null
    };

    var extraParams = {
    };

**Comment by fc** [comment]
It was an object I had serialized to JSON and it had a null property.  Sometimes the property null, sometimes not, an optional value.

And... I just realized I didn't send you an accurate way to reproduce the issue.

It was actually something like this:
````javascript
var extraParams = {
    myObject: {something:null}
};
````

**Comment by fc** [comment]
also, you can't send an array although maybe that is already documented somewhere but seems like it should be supported...
````javascript
var extraParams = {property:[123]};
````

**Comment by fc** [comment]
there is a typo in _getExtension, a variable is called 'oponnent' instead of 'opponent' (it's not a 'real' bug) -- not trying to nitpick or anything, just browsing through the code.

**Comment by soulfly** [comment]
Thank you
we will include the 'null' fix in  our next release

**Comment by soulfly** [comment]
The null issue is fixed in 
https://github.com/QuickBlox/quickblox-javascript-sdk/tree/develop.webrtc
