### ISSUE TITLE
Issue with group chat: onRemoteStreamListener not called for multiple users

### ISSUE THREAD

**Issue by sakthig** [QuickBlox/quickblox-javascript-sdk#280]
**Environment details**
OS: Mac
Browser: Chrome
SDK: Latest

**Did this work before?**
No. Infact facing similar issue in the official demo as well. If we create a room and login, the first two users are able to see each other. But when the 3rd person logs-in any of the previous user is getting kicked out. Only two users are visible in the room at any given point of time.

**Expected behavior**
Multiple users should be able to do a video chat by joining the room and on the same call.

**Actual behavior**
onRemoteStreamListener is not called for all the users in the call. It gets called back only once for a random user in the call for each user. Suppose if A, B, C, D are on a call and accept the call sequentially in the same order.. then A gets callback with stream of B, B gets callback with stream of C, C gets callback with stream of D, and D does not get a stream callback at all.

**Logs**
I also keep getting these errors

Ignore 'OnIceCandidates', there is no information about peer connection by some reason.

Ignore 'OnIceCandidates', this session has invalid state.

**Any others comments?**
Read in stackoverflow that the js sdk does not support group chat. Is it still true ?

contact: gomsy.h@gmail.com, deepakuppoor@gmail.com, rahulsahu47@gmail.com, shashank563@gmail.com

**Comment by dimaspirit** [comment]
Hi all, 
no, QB SDK support group calls.
Could you try to reproduce this issue on our [sample](https://quickblox.github.io/quickblox-javascript-sdk/samples/webrtc/#join)?
