### ISSUE TITLE
audio video calling not working on Safari (11+) browser

### ISSUE THREAD

**Issue by neerajbr** [QuickBlox/quickblox-javascript-sdk#288]
hello Team,

I am using the Javascript SDK latest 2.7 version.
Some time i am facing below error during video calling.
(device not found error)
but i attached camera and head phone in my system and it is showing device not found error message on the screen.
****Error Log:**** 
Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Comment by dimaspirit** [comment]
@neerajbr Hi, for Safari as like for Firefox you need to get permission each time when you mae a call.

Give us more information for reproduce this case if you can't to resolve it.

**Comment by dimaspirit** [comment]
@neerajbr , Hi, yes we know that issue. That's why Safari doesn't use autoplay (https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) and won't to get access from a user. We are working on a workaround.

**Comment by dimaspirit** [comment]
@neerajbr also you could set up autoplay by settings in safari 
![7d2b649a-e2a0-47b7-bfaa-07af363e20cb](https://user-images.githubusercontent.com/5120723/36847189-29ff5992-1d66-11e8-85ff-9ea18db9fcec.png)
