### ISSUE TITLE
duplicate login on other pc

### ISSUE THREAD

**Issue by db2crush** [QuickBlox/quickblox-javascript-sdk#290]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
latest chrome version, quickblox 2.7.0

**Did this work before?**
no

**Expected behavior**
1) Login by two PC by same ID.
2) Other PC or mobile calls to this ID.
3) Then call is rejected.

**Actual behavior**
maybe cannot login on two PC (?)

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**
thanks for nice project.

**Comment by dimaspirit** [comment]
@runningo Hi, yes you can login with 2 or more times.
You could make workaround to prevent second login if you want.

But for call we make only 1 active login, what first make accept.
