### ISSUE TITLE
Stream does not attach to video tag

### ISSUE THREAD

**Issue by limaneto** [QuickBlox/quickblox-javascript-sdk#292]
Phonegap/IOS/Android

I've been trying to make the tool work on ios/android with phonegap, and only made it work on android. On iOS using iPhone 6 and iOS 11.2.2 the video does not show on the screen, but on android it does. And it does not show error messages.

`QB.init(CREDENTIALS.appId, CREDENTIALS.authKey, CREDENTIALS.authSecret);

        var calleesIds = [89093];
        var sessionType = QB.webrtc.CallType.VIDEO;
        var session = QB.webrtc.createNewSession(calleesIds, sessionType);

        var mediaParams = {
          audio: true,
          video: true,
          options: {
            muted: true,
            mirror: true
          },
          elemId: 'localVideo'
        };

        var permissions = cordova.plugins.permissions;

        permissions.requestPermission(permissions.CAMERA, success, error);

        function error() {
          console.warn('Camera permission is not turned on');
        }

        function success( status ) {
          if( status.hasPermission ) {
            session.getUserMedia(mediaParams, function (error, mediaStream) {
              if (error) {
                console.log(error);
              } else {
              }
            });
          } else {
            error();
          }
        }`

I have the cordova-plugin-iosrtc,  cordova-custom-config, cordova-plugin-device and the iOS deploy tooll installed.

**Comment by vadimkhmyrovqb** [comment]
@limaneto Hi, is this issue still relevant? Have you tried the latest version of Cordova and JS SDK?

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
