### ISSUE TITLE
Is there any plan to give Typescript Definition File

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-javascript-sdk#299]
I was wondering if you guys are planning to give typescript definition files for your library. Thanks.

**Comment by Vladlukhanin** [comment]
Hi, @itsaboutcode 
Excuse me, what are you mean "typescript definition files"? Does our SDK work with your TypeScript project?

**Comment by itsaboutcode** [comment]
@Vladlukhanin - It's working fine with our typescript project but would like to know if we can get TypeScript Type Definition file (d.ts).

**Comment by Vladlukhanin** [comment]
Haven't thought about adding declaration files. And I can't promise you that we're going to do this at close time.
We will let you know if it happens.

**Comment by dimaspirit** [comment]
@itsaboutcode sorry, now we are not planning add Typescript Definition File, but you could use SDK without it. Check out this [solution](https://hackernoon.com/angular-providers-how-to-inject-3rd-party-library-af4a78722864).
