### ISSUE TITLE
I am facing an issue in real time(Instant) chat

### ISSUE THREAD

**Issue by manojintorque** [QuickBlox/quickblox-javascript-sdk#302]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

==>  

$scope.sendMessage = function(){
var msg = {
			type: $scope.type == 3 ? 'chat' : 'groupchat',
			body: $("#chat-message").val(),
			extension: {
				save_to_history: 1,
				nick: $scope.ChatLogin
			},
			senderId: $scope.fromID,
			send_to_chat:1,
			delay:null,
			markable:1,
			chat_dialog_id:$scope.dialogID
		};

if ($scope.type == 3) {
			opponentId = QB.chat.helpers.getRecipientId($scope.occupants_ids, $scope.fromID);
			var msgId = QB.chat.send(opponentId, msg);
} else {
			QB.chat.send($scope.xmpp_room_jid, msg);
		}
}

**Environment details**
*(Operating system, browser information, SDK version)*
==> Windows 10, Google chorme,  SDK Version: 2.8.0

**Did this work before?**
==> No

**Comment by Vladlukhanin** [comment]
"I am facing an issue in real time(Instant) chat" - what's the problem?

**Comment by manojintorque** [comment]
The problem is that when i send a message to another person then that person not getting instant message he need to re fetch it and then he get it.

**Comment by Vladlukhanin** [comment]
https://quickblox.com/developers/Web_XMPP_Chat_Sample#Chat_in_1-1_private_dialog

Have you used QB.chat.onMessageListener to get messages?

I've found a mistake (you must send custom parameters in "extension" field):
```
var msg = {
    type: $scope.type == 3 ? 'chat' : 'groupchat',
    body: $("#chat-message").val(),
    extension: {
        save_to_history: 1,
        nick: $scope.ChatLogin,
        senderId: $scope.fromID,
        send_to_chat:1,
        delay:null,
        markable:1,
        chat_dialog_id:$scope.dialogID
    }
};
```

**Comment by manojintorque** [comment]
'QB.chat.onMessageListener' - No i haven't use it, Can you tell me where i have to put in code?

**Comment by manojintorque** [comment]
angular.min.js:92 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object._JStoXML (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15236:40)
    at http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15250:62
    at Array.forEach (<anonymous>)
    at Object.filledExtraParams (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15247:47)
    at r.send (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:14622:31)
    at k.$scope.sendMessage (http://localhost/test/Heyoo-Web/app/controllers/qbChatController.js:289:24)
    at http://localhost/test/Heyoo-Web/app/js/angular.min.js:177:68
    at f (http://localhost/test/Heyoo-Web/app/js/angular.min.js:194:174)
    at k.$eval (http://localhost/test/Heyoo-Web/app/js/angular.min.js:112:68) undefined
(anonymous) @ angular.min.js:92
(anonymous) @ angular.min.js:68
(anonymous) @ angular-block-ui.min.js:6
$apply @ angular.min.js:112
(anonymous) @ angular.min.js:194
(anonymous) @ angular.min.js:31
r @ angular.min.js:7
c @ angular.min.js:31

When i used your code i am getting above error.

**Comment by Vladlukhanin** [comment]
```
QB.chat.onMessageListener = onMessage;
 
function onMessage(userId, msg) {
    // the message will be here
    // and here will be your code
    console.log(userId);
    console.log(msg)
}
```

Use our code as example. Read more in [the chat guide].(https://quickblox.com/developers/Web_XMPP_Chat_Sample#Guide:_Getting_Started_with_Chat_API)

**Comment by manojintorque** [comment]
i have to add  "QB.chat.onMessageListener = onMessage;" this after  "QB.chat.send(opponentId, msg);" this line line right? or when i connect chat ?

QB.chat.connect({userId: user['id'], password: $scope.U_Email+$scope.U_Mobile}, function(err, roster) {
						  if (err) {
							  console.log(err);
						  } else {
							  console.log(roster);
						  }
					});

**Comment by Vladlukhanin** [comment]
QB.chat.onMessageListener is a function-listener.
The better way is define the QB.chat.onMessageListener after QB.chat.connect will return a response (not an error). 
The QB.chat.onMessageListener will always execute if it has a new message.

**Comment by manojintorque** [comment]
Thank you for quick response but when i tried above thing its also generate error, i will put "QB.chat.onMessageListener" like below  is okay?
QB.chat.connect({userId: user['id'], password: $scope.U_Email+$scope.U_Mobile}, function(err, roster) {
						  if (err) {
							  console.log(err);
						  } else {
							  console.log(roster);
							  QB.chat.onMessageListener = onMessage;
						  }
					});

**Comment by Vladlukhanin** [comment]
Yes, it's ok! And then you can define the function onMessage(userID, message) anywhere.
```
QB.chat.connect(userParams, function(err, roster) {
    if (err) {
        console.log(err);
    } else {
        console.log(roster);
        QB.chat.onMessageListener = onMessage;
    }
});

function onMessage(id, msg) {
    console.log(`New message >>> ${usersCache.get(id).full_name}: "${msg.body}"`);
}
```

**Comment by manojintorque** [comment]
Sorry be late
Yeah i declare same but it generate error like below !!


angular.min.js:92 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object._JStoXML (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15236:40)
    at http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15250:62
    at Array.forEach (<anonymous>)
    at Object.filledExtraParams (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:15247:47)
    at r.send (http://localhost/test/Heyoo-Web/QB/quickblox.min.js:14622:31)
    at k.$scope.sendMessage (http://localhost/test/Heyoo-Web/app/controllers/qbChatController.js:294:24)
    at http://localhost/test/Heyoo-Web/app/js/angular.min.js:177:68
    at f (http://localhost/test/Heyoo-Web/app/js/angular.min.js:194:174)
    at k.$eval (http://localhost/test/Heyoo-Web/app/js/angular.min.js:112:68) undefined
(anonymous) @ angular.min.js:92
(anonymous) @ angular.min.js:68
(anonymous) @ angular-block-ui.min.js:6
$apply @ angular.min.js:112
(anonymous) @ angular.min.js:194
(anonymous) @ angular.min.js:31
r @ angular.min.js:7
c @ angular.min.js:31

**Comment by Vladlukhanin** [comment]
I think that the error in your **message.extension** object (Cannot convert undefined or null to object). Possible it happens because you set **message.extension.delay** as _null_.

**Comment by manojintorque** [comment]
QB.chat.connect({userId: user['id'], password: $scope.U_Email+$scope.U_Mobile}, function(err, roster) {
						  if (err) {
							  console.log(err);
						  } else {
							  console.log(roster);
							  QB.chat.onMessageListener = onMessage;
						  }
					});

function onMessage(id, msg) {
		
		console.log(msg);
		console.log(id);
	}

var msg = {
			type: $scope.type == 3 ? 'chat' : 'groupchat',
			body: $("#chat-message").val(),
			extension: {
				save_to_history: 1,
				nick: $scope.ChatLogin
			},
			senderId: $scope.fromID,
			send_to_chat:1,
			delay:null,
			markable:1,
			chat_dialog_id:$scope.dialogID
		};
var msgId = QB.chat.send(opponentId, msg);


this is working i got new messages from other user but is not showing me in dialog so i think i have to update dialog right?

**Comment by Vladlukhanin** [comment]
So, you have the message object from other user - just add the message on UI. The dialog where the message comes in will update on server. It always will be updated if you use save_to_history = 1.

**Comment by manojintorque** [comment]
Yeah let try that one i will update you soon :)

**Comment by manojintorque** [comment]
Yeeee Vladlu Khanin
 A BIG Thank you very much for quick response
 now is working Good :)

**Comment by manojintorque** [comment]
I need one more help to load all messages in ui so i follow bellow syntax:
var params = {chat_dialog_id: dialogId, sort_asc: 'date_sent', limit: 100, skip: $scope.msgSkip};
but i want to load all messages
what i have to do?

**Comment by dimaspirit** [comment]
@manojintorque sorry, there is no way to all in one request.
Check out [docs](https://quickblox.com/developers/Web_XMPP_Chat_Sample#List_chat_messages).

**Comment by manojintorque** [comment]
@dimaspirit Okay no problem thank you for response :)
 but any other way to fetch  all messages?

**Comment by dimaspirit** [comment]
No, there is no way. Need to make a loop and fetch messages by 100 items max. 
Check out docs what are give you before.

**Comment by manojintorque** [comment]
okay No Problem
