### ISSUE TITLE
I facing issue in update profile !

### ISSUE THREAD

**Issue by manojintorque** [QuickBlox/quickblox-javascript-sdk#303]
var user_id = localStorage.getItem('userid');				
$scope.profile = data['user']['U_ProfileImage'];
				
QB.users.update(user_id, {full_name: user_fullname,custom_data:$scope.profile)}, function(err, user){
  if (user) {
	console.log(user);
  } else  {
	console.log(err);
  }
});

ERROR

{code: 404, status: "error", message: {…}, detail: null}
code
:
404
detail
:
null
message
:
{code: null, message: "Possible subdomains: admin, api"}
status
:
"error"
__proto__
:
Object

**Comment by dimaspirit** [comment]
@manojintorque , i am not sure but looks like you don't set right configuration.
In any way, if you want to get help fill issue by templete. Now we can't help you.

**Comment by manojintorque** [comment]
@dimaspirit I got solution :) thank you for suggestion

**Comment by anmol2615** [comment]
@manojintorque what's the solution?
