### ISSUE TITLE
Error: devices (camera or microphone) are not found.

### ISSUE THREAD

**Issue by testaccnt0435** [QuickBlox/quickblox-javascript-sdk#304]
I have run the app using cordova in android. When I select the user and click video call button, I get this error "Error: devices (camera or microphone) are not found.". I have turned on the camera permissions and configured my config.xml file as mentioned in [url](https://github.com/QuickBlox/quickblox-javascript-sdk/commit/772cea80428e23a0ceec01918e54df4a0a9aeb23#diff-5f1e743bd47e1286a6f57330e79e0c22)
I face this issue in Android 7.0, 6.0.

**Comment by Ravi-Chudgar** [comment]
Add the  plugins cordova-plugin-media-capture so it will dectec the  device camera and microphone
