### ISSUE TITLE
User X calling User Y who has 2 connections open can lead to the call being aborted since the 2nd connection isn't notified the call was accepted

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#31]
Steps to reproduce.
1. Open this URL into three separate windows: http://quickblox.github.io/quickblox-javascript-sdk/samples/webrtc/peer-to-peer/
2. In the first two windows, select user 9 but in the third window select user 10.
3. User 10 now initiates a call to user 9 by clicking the 'Video Call' button
4. Both of the windows that are open and connected to user 9 will receive a prompt to accept or decline the call.
5. In the first User 9 window, accept the call.  You will continue to hear the call signal coming in the second User 9 window.
6.  I go to the second User 9 window and click 'Decline'
7. It hangs up the call for User 9 in the first window and it hangs up the call for User 10 who initiated the call.

So... ideally:

There must be a way to notify the 2nd User 9 window that the call has been aborted and cancel the display accept/reject prompt and playing audio call signal.

I haven't tested this across Android/iOS devices yet but it may be an issue there too.

**Comment by dimaspirit** [comment]
Thanks, this issue we have in all devices.
It's issue of samples, not of SDK,  we are working on enhancement of samples.

**Comment by dimaspirit** [comment]
@fc we have implemented a new way to log in the sample. Check it https://quickblox.github.io/quickblox-javascript-sdk/samples/webrtc/ , so is it solve your case?
