### ISSUE TITLE
Module not found: Error: Can't resolve 'child_process' 

### ISSUE THREAD

**Issue by roudikk** [QuickBlox/quickblox-javascript-sdk#311]
**Environment details**
*(Operating system, browser information, SDK version)*
- Windows
- Chrome, Firefox
- QB 2.8.1 - 2.8.0 - 2.6.2
- Ionic v3
- Angular 5.2.5

**Did this work before?**
- No

**Expected behavior**
- Building a production build should work without throwing any error

**Actual behavior**
- Building a production build using` ionic build --prod` or `npm run build --prod` throwing below error:

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

`[09:30:48]  ionic-app-script task: "build" 
[09:30:48]  Error: ./node_modules/node-xmpp-client/lib/Client.js Module not found: Error: Can't resolve 'child_process' 
            in 'C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\lib' resolve 
            'child_process' in 'C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\lib' 
            Parsed request is a module using description file: C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\package.json (relative path: ./lib) after 
            using description file: C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\package.json (relative path: ./lib) resolve 
            as module looking for modules in C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules using 
            description file: C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: 
            ./node_modules) Field 'browser' doesn't contain a valid alias configuration after using description file: 
            C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: ./node_modules) using 
            description file: C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: 
            ./node_modules/child_process) no extension Field 'browser' doesn't contain a valid alias configuration 
            C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process doesn't exist .ts Field 'browser' 
            doesn't contain a valid alias configuration C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.ts doesn't exist .js Field 'browser' doesn't 
            contain a valid alias configuration C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.js doesn't exist .json Field 'browser' doesn't 
            contain a valid alias configuration C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.json doesn't exist as directory C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process doesn't exist [C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process] [C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.ts] [C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.js] [C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process.json] [C:\Users\Roudy 
            Kanaan\Documents\synkers-support\node_modules\child_process] @ ./node_modules/node-xmpp-client/lib/Client.js 
            15:11-35 @ ./node_modules/node-xmpp-client/index.js @ ./node_modules/quickblox/src/modules/qbChat.js @ 
            ./node_modules/quickblox/src/qbMain.js @ ./src/provider/chat-service.ts @ ./src/app/app.module.ngfactory.js 
            @ ./src/app/main.ts 
Error: ./node_modules/node-xmpp-client/lib/Client.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\lib'
resolve 'child_process' in 'C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\lib'
  Parsed request is a module
  using description file: C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\package.json (relative path: ./lib)
  after using description file: C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\node-xmpp-client\package.json (relative path: ./lib)
    resolve as module
      looking for modules in C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules
        using description file: C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: ./node_modules)
          using description file: C:\Users\Roudy Kanaan\Documents\synkers-support\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.json doesn't exist
            as directory
              C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process doesn't exist
[C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process]
[C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.ts]
[C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.js]
[C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process.json]
[C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\child_process]
 @ ./node_modules/node-xmpp-client/lib/Client.js 15:11-35
 @ ./node_modules/node-xmpp-client/index.js
 @ ./node_modules/quickblox/src/modules/qbChat.js
 @ ./node_modules/quickblox/src/qbMain.js
 @ ./src/provider/chat-service.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at new BuildError (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (C:\Users\Roudy Kanaan\Documents\synkers-support\node_modules\webpack\lib\Compiler.js:365:9)
`

**Steps to reproduce the behavior**
- Create an empty ionic project, add quickblox, attempt a production build

**Any others comments?**
- Tried the below but didn't work (In webpack config):
`module.exports.node = {
  child_process: 'empty'
};`
and:
`
module.exports.node = {
  fs: 'empty'
};
`

**Comment by dimaspirit** [comment]
@RoudyK , thanks for report th issue. Yes, we don't optimize SDK for Ionic yet, now we are supporting Browers, Node.js and NativeScript. As I see, it's some issues with node-xmpp-client.
We will deal with this issue in the order of the queue and notify you of the updates.

**Comment by kdenaeem** [comment]
@dimaspirit I get the same error but I use vue.js
here is the error
`Failed to compile.

./node_modules/node-xmpp-client/lib/Client.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Naeem\Documents\doctoros\ui\html\node_modules\node-xmpp-client\lib'
 @ ./node_modules/node-xmpp-client/lib/Client.js 15:11-35
 @ ./node_modules/node-xmpp-client/index.js
 @ ./node_modules/quickblox/src/modules/chat/qbChat.js
 @ ./node_modules/quickblox/src/qbMain.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/Chat.vue
 @ ./src/Chat.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js`

I added the source `<script src="https://cdnjs.cloudflare.com/ajax/libs/quickblox/x.x.x/quickblox.min.js"></script>`

and the variables such as require('quickblox')Quickblox
and QB1 and QB2. The version of QB is the latest

**Comment by niccolofanton** [comment]
Hi, you can try import quickblox.min.js from the index.html: 
```
  document.addEventListener('deviceready', () => {

      var jsScript = document.createElement("script");
      jsScript.type = "text/javascript";
      jsScript.async = false; 
      jsScript.src = "https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.3.4/quickblox.min.js";
      document.getElementsByTagName("body")[0].appendChild(jsScript);
    
  }, false);
```

Then in your provider outside the class, under the import: 
`declare var QB: any;`

If you want to use it in iOS you have to follow the guide for the plugins installations:
https://quickblox.com/developers/Sample-webrtc-cordova
(Because iOS doesn't support the WebRTC by default)

**Comment by ghost** [comment]
@niccolofanton @CodingAlien @dimaspirit if you're using ionic you're going to have to copy the entire js from <script src="https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.11.0/quickblox.min.js"></script>
into a quikcblox.js file and include that file in index.html else your prod app won't work.

When done, using declare const QB: any and use it wherever you want. That works.

**Comment by niccolofanton** [comment]
@PampaZiya  now I'm going to try. Have you used Quickblox js also in iOS side Ionic successfully?

**Comment by ghost** [comment]
@niccolofanton Yes and it works

**Comment by niccolofanton** [comment]
@PampaZiya sorry for bothering you, currently I'm working on an application (Ionic 3 iOS-Android) that allows user to make video-calls and I'm stuck in the iOS side of the project, I have a problem when answering a call ( session.accept({}) always log an error "Can't accept the call, there is no information about peer connection by some reason." ). Have you ever face this problem? Thanks.
(https://stackoverflow.com/questions/50137385/unable-to-answer-a-video-call-in-quickblox-javascript this is my question in stackoverflow )

Android side works, and I followed  all the steps https://quickblox.com/developers/Sample-webrtc-cordova for the plugins

**Comment by ghost** [comment]
@niccolofanton Hello, sorry I haven't integrated video call in my implementation, only chat. So I cannot help you :/

**Comment by niccolofanton** [comment]
Ok nevermind thanks for the help :)

**Comment by qafuturex** [comment]
same issue in react.js
