### ISSUE TITLE
unable to resolve module fs

### ISSUE THREAD

**Issue by kingtross88** [QuickBlox/quickblox-javascript-sdk#314]
trying to install this package for a react native project. NSLocalizedDescription=Unable to resolve module `fs` from `/

**Comment by vadimkhmyrovqb** [comment]
@kingtross88 Our team is planning to publish ReactNative SDK in April-May 2019.

**Comment by kingtross88** [comment]
good news!

**Comment by kingtross88** [comment]
I keep getting an error message during the setup. Does this work for react
native?

https://github.com/vinayr/react-native-quickblox
