### ISSUE TITLE
Upload file error (<Code>InvalidArgument</Code>)

### ISSUE THREAD

**Issue by fhackenb** [QuickBlox/quickblox-javascript-sdk#317]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
I'm running it on NativeScript on an iPad. Version 2.8.1

**Did this work before?**
No

**Expected behavior**

I'm attempting to upload image files (specifically png files) as part of a chat message. Everything else with QuickBlox has worked so far, but when I invoke the createAndUpload function I get this error:

{"code":400,"status":"error","message":"<?xml version=\134"1.0\134" encoding=\134"UTF-8\134"?>\134n<Error><Code>InvalidArgument</Code><Message>Conflict
ing query string parameters: acl, policy</Message><ArgumentName>ResourceType</ArgumentName><ArgumentValue>acl</ArgumentValue><RequestId>8DC4BB37F4D3F92C</RequestId><HostId>6IRYiea+gi2URrGYnRIUb4JqVHp+fZOXrazpH7rN
PSsjNnKAkm4zIDKLZiUfcGvwmOlROypfVjI=</HostId></Error>","detail":null}

My code is: 

import { File } from "tns-core-modules/file-system/file-system";
import * as QB from "quickblox";

public sendImage(file: File) {
        let size = this.fileSize(file);
        let params = {name: file.name, file: file, type: "image/png", size: size, 'public': false};
        try {
            QB.content.createAndUpload(params, (err, res) => {
                console.log("create and upload res:");
                console.log(JSON.stringify(res));
                console.log(JSON.stringify(err));
            });
        }   catch (err) {
            console.log(JSON.stringify(err));
        }
    }

w/ fileSize accessing the iPad's native library to get the file's size. I get the same error if I just don't pass in size as a parameter, so I don't think that's the problem.

This may be some permissions issue? But nothing else is giving me any trouble, so any help on this would be appreciated. Thanks

P.S. I saw this guy had a similar issue [https://stackoverflow.com/questions/32849425/quickblox-uploading-of-files](url) but not really clear on how he ended up resolving it.

**Comment by datanotion** [comment]
Any update on this?

**Comment by Vladlukhanin** [comment]
Here is a link how to do it on iOS
https://gist.github.com/soulfly/b55d6c0dd9448bc1dc1133793a6ac22d

On Android it should be pretty the same, maybe some small changes with image picker

**Comment by soulfly** [comment]
Unfortunately, the 'createAndUpload' method is not working on NativeScript because of some issues with FormData on NativeScript, so please try above snippet from Vlad and let us know

**Comment by datanotion** [comment]
The gist did appear work for iOS!  Thank you @soulfly and @Vladlukhanin

In case you didn't see the comment from @fhackenb here: https://gist.github.com/soulfly/b55d6c0dd9448bc1dc1133793a6ac22d

It does not work for Android.  Can you please explain to us what needs to be handled differently, or even provide a small code sample please?  Thank you!

**Comment by Vladlukhanin** [comment]
OK, Thank you @datanotion 
We will try to run this solution for Android and let you know!

**Comment by Vladlukhanin** [comment]
@datanotion 
Could you [look my last comment here](https://gist.github.com/soulfly/b55d6c0dd9448bc1dc1133793a6ac22d)?

**Comment by datanotion** [comment]
Thank you @Vladlukhanin!  We will be trying that solution today!

**Comment by RacknerFrank** [comment]
Hey @Vladlukhanin any update on this? I also posted here:[https://gist.github.com/soulfly/b55d6c0dd9448bc1dc1133793a6ac22d](url) but not sure if you'd see it there

**Comment by vadimkhmyrovqb** [comment]
@fhackenb @RacknerFrank Is this issue relevant? Could you confirm whether it is reproduced with latest Nativescript version?

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-content#upload-file](https://docs.quickblox.com/docs/js-content#upload-file)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
