### ISSUE TITLE
Installing QuickBlox on Ubuntu

### ISSUE THREAD

**Issue by kdenaeem** [QuickBlox/quickblox-javascript-sdk#324]
Im trying to install Quickblox on Ubuntu so I can use it on my site using the javasciprt sdk

**Environment details**
Im using KDE Plasma 5.12.13 OS-TYPE - 64-bit

**Did this work before?** 
No this is the first time I have tried to download it

**Expected behavior**
I expected it to download Quickblox so I can use it on my website

**Actual behavior**
I typed in npm install quickblox --save at username@username:~$
and I got multiple errors
**Logs**
[debugging mode] npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'xmpp/xml' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'nativescript-xmpp-client'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.13.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "quickblox" "--save"
npm ERR! cwd /home/kde_naeexm
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
[debugging mode] 

**Extra notes**
Im using express to compile my site onto the web

**Comment by Vladlukhanin** [comment]
Update the Node.js and npm
