### ISSUE TITLE
ionic 3 integration

### ISSUE THREAD

**Issue by anilkumar007** [QuickBlox/quickblox-javascript-sdk#329]
how can we integrate the quickblox library in ionic 3?

**Comment by niccolofanton** [comment]
Hi you have to use this code in your index.html file:
```
document.addEventListener('deviceready', () => {
      
   var jsScript = document.createElement("script");
    jsScript.type = "text/javascript";
    jsScript.async = false; 
    jsScript.src = "https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.11.0/quickblox.min.js";
    document.getElementsByTagName("body")[0].appendChild(jsScript);

}); 
```

Now in your controller use this (write under the imports):
`declare var QB: any;`

And now you have the QB object. To enable the iOS Webrtc you have to install this plugin:
https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc
Follow all the steps for the installation.

**Edit:**
I've made a simple demo, maybe it can help you.
https://github.com/niccolofanton/quickblox-ionic3

**Comment by duyetnk** [comment]
@niccolofanton Thanks you for your work :))
