### ISSUE TITLE
'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#33]
In Chrome, when clicking hangup from a video/voice call it will output the notice that MediaStream.stop() will soon be deprecated and be removed quite soon.

For more information, check here:
https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en

**Comment by soulfly** [comment]
We are working on next webrtc lib and code sample release
This is also will be fixed there
