### ISSUE TITLE
Recorded blob is in readonly format. How to convert webm format to mp4? 

### ISSUE THREAD

**Issue by gaurav150493** [QuickBlox/quickblox-javascript-sdk#332]
on recorded stop the blob i am getting is in readonly format i am not able to make any change in it so how can i convert its format from webm to mp4? Is there any specified function for it??

**Comment by Vladlukhanin** [comment]
The first - the issue for [the javascript-media-recorder repository](https://github.com/QuickBlox/javascript-media-recorder/issues).

You can check which [mime types are supported](https://quickblox.github.io/javascript-media-recorder/docs/QBMediaRecorder.html#.getSupportedMimeTypes) by your browser. Here are [all possible mime types](https://github.com/QuickBlox/javascript-media-recorder/blob/master/src/mimeTypes.js).

So you can try:
```
var opts = {
    onstart: function onStart() {
        console.log('Recorder is started');
    },
    onstop: function onStop(Blob) {
        videoElement.src = URL.createObjectURL(blob);
    },
    mimeType: 'video/mp4'
};

var recorder = new QBMediaRecorder(opts);
```

Note that the recorder.toggleMimeType(newMimeType) will [change mimeType](https://quickblox.github.io/javascript-media-recorder/docs/QBMediaRecorder.html#toggleMimeType) in the recorder.

**Comment by gaurav150493** [comment]
I have used `mimeType: 'video/mp4'`  in my code but not working.

**Comment by Vladlukhanin** [comment]
You can check which [mime types are supported](https://quickblox.github.io/javascript-media-recorder/docs/QBMediaRecorder.html#.getSupportedMimeTypes) by your browser...

QBMediaRecorder.getSupportedMimeTypes('video') - and you will see all supported video mime types.

https://quickblox.github.io/javascript-media-recorder/sample/ may be helpful

**Comment by gaurav150493** [comment]
This is the list i got for supported mimetypes

`["video/webm;codecs=vp9", "video/webm;codecs=vp8", "video/webm;codecs=h264", "video/webm;codecs=opus","video/webm"]`

so according to this `video/mp4` is not supported for my browser where i can see on other website that `video/mp4` format is working on my browser. 

Is there any way i can download mp4 file?

**Comment by MittalShruti** [comment]
Hi @gaurav150493  I am facing the same issue. Did you find any solution?
