### ISSUE TITLE
Android connection issue causing app crash

### ISSUE THREAD

**Issue by RacknerFrank** [QuickBlox/quickblox-javascript-sdk#333]
**Environment details**
NativeScript running on android, sdk 2.11

**Did this work before?**
No

**Crash**
Using the js sdk seems to work perfect for iOS in NativeScript, but on android there is an issue with the connection continuously disconnecting. My program detects the disconnect and automatically attempts a reconnect. After awhile though, the app crashes on getIdFromNodeMethod because jid is undefined. I enabled the debug logs, so here's what they look like:

**Logs**
JS: WS Connected
JS: [Chat] SENT: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">NDU0NzA1MzgtNjc2MjFAY2hhdC5xdWlja2Jsb3guY29tADQ1NDcwNTM4LTY3NjIxADAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwOA==</auth>
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
JS: [Chat] ERROR - 12:43:05
JS: [undefined] error:  ERROR - An error has occurred
[Chat] CONNECTED - 12:43:05
JS: [Chat] SENT: <iq type="get" from="45470538-67621@chat.quickblox.com/null" id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster"><query xmlns="jabber:iq:roster"/></iq>
JS: [Chat] SENT: <iq type="set" from="45470538-67621@chat.quickblox.com/null" id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons"><enable xmlns="urn:xmpp:carbons:2"/></iq>
JS: [Chat] CONNECTED - 12:43:05
JS: [Chat] SENT: <iq type="get" from="45470538-67621@chat.quickblox.com/null" id="2343c36b-59ad-4cd8-98e5-b3e8fcc32dd6:getRoster"><query xmlns="jabber:iq:roster"/></iq>
JS: [Chat] SENT: <iq type="set" from="45470538-67621@chat.quickblox.com/null" id="47686c42-b135-40f4-82bf-55d05889e21e:enableCarbons"><enable xmlns="urn:xmpp:carbons:2"/></iq>
JS: [Chat] CONNECTED - 12:43:05
JS: [Chat] SENT: <iq type="get" from="45470538-67621@chat.quickblox.com/null" id="a1932c18-33cc-4f99-8811-633b52116479:getRoster"><query xmlns="jabber:iq:roster"/></iq>
JS: [Chat] SENT: <iq type="set" from="45470538-67621@chat.quickblox.com/null" id="9c921516-ae26-48d2-90ac-d1f75ac53bac:enableCarbons"><enable xmlns="urn:xmpp:carbons:2"/></iq>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS
</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><m
ethod>zlib</method></compression></stream:features>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS
</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><m
ethod>zlib</method></compression></stream:features>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS
</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><m
ethod>zlib</method></compression></stream:features>
JS: [Chat] RECV: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.quickblox.com" id="dc4f9ffd-e063-460d-9e95-1e18d92e38cd" version="1.0" xml:lang="en"/>
JS: [Chat] RECV: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.quickblox.com" id="dc4f9ffd-e063-460d-9e95-1e18d92e38cd" version="1.0" xml:lang="en"/>
JS: [Chat] RECV: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" from="chat.quickblox.com" id="dc4f9ffd-e063-460d-9e95-1e18d92e38cd" version="1.0" xml:lang="en"/>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compres
sion xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compres
sion xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
JS: [Chat] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compres
sion xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:params:
xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] SENT: <presence/>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:params:
xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:params:
xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="ed5d5e39-3f99-4ef5-80fb-c2d4e00463e4:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:
params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="503" type="cancel"><service-unavailable xmlns="ur
n:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="503" type="cancel"><service-unavailable xmlns="ur
n:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="ef4fe27b-229e-443e-9c61-8b235e34af4d:enableCarbons" type="error" xmlns="jabber:client"><enable xmlns="urn:xmpp:carbons:2"/><error code="503" type="cancel"><service-unavailable xmlns="ur
n:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Service not available.</text></error></iq>
JS: [Chat] RECV: <iq id="2343c36b-59ad-4cd8-98e5-b3e8fcc32dd6:getRoster" type="error" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/><error code="401" type="auth"><not-authorized xmlns="urn:ietf:params:
xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></iq>
JS: [Chat] SENT: <presence/>

JS: [Chat] RECV: <presence type="error" xmlns="jabber:client"><error code="401" type="auth"><not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-st
anzas">You must bind the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind</text></error></presence>
System.err: com.tns.NativeScriptException:
System.err: Calling js method onMessage failed
System.err:
System.err: TypeError: Cannot read property 'indexOf' of null
System.err: File: "file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js, line: 2295, column: 19
System.err:
System.err: StackTrace:
System.err:     Frame: function:'getIdFromNode', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js', line: 2295, column: 20
System.err:     Frame: function:'ChatProxy._onPresence', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js', line: 483, column: 31
System.err:     Frame: function:'', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js', line: 844, column: 26
System.err:     Frame: function:'EventEmitter.emit', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/node-event-emitter/index.js', line: 108, column: 20
System.err:     Frame: function:'Client._handleStanza', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/Client.js', line: 226, column: 12
System.err:     Frame: function:'Client.onStanza', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/Client.js', line: 220, column: 8
System.err:     Frame: function:'EventEmitter.emit', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/node-event-emitter/index.js', line: 86, column: 17
System.err:     Frame: function:'WSConnection.onStanza', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/websockets.js', line: 125, column: 10
System.err:     Frame: function:'', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/websockets.js', line: 96, column: 10
System.err:     Frame: function:'EventEmitter.emit', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/node-event-emitter/index.js', line: 86, column: 17
System.err:     Frame: function:'', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/deps/@xmpp/streamparser/index.js', line: 81, column: 14
System.err:     Frame: function:'EventEmitter.emit', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/node-event-emitter/index.js', line: 86, column: 17
System.err:     Frame: function:'SaxLtx._handleTagOpening', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/ltx-ea/lib/parsers/ltx.js', line: 36, column: 12
System.err:     Frame: function:'SaxLtx.write', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/ltx-ea/lib/parsers/ltx.js', line: 96, column: 18
System.err:     Frame: function:'StreamParser.write', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/deps/@xmpp/streamparser/index.js', line: 146, column: 17
System.err:     Frame: function:'WSConnection.onmessage', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-xmpp-client/lib/websockets.js', line: 116, column: 17
System.err:     Frame: function:'NativeWebSockets._notifyBrowser', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-websockets/websockets.js', line: 322, column: 32
System.err:     Frame: function:'onMessage', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-websockets/websockets.js', line: 102, column: 26
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.access$2400(Runtime.java:34)
System.err:     at com.tns.Runtime$3.run(Runtime.java:1099)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6682)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
JS: [Sentry - Android] Exeption on capture:  Error: Cannot convert object to Lio/sentry/event/Event; at index 0
JS: [object Object]
JS: sending
ActivityManager: Process com.jsoftllc.loopmein (pid 8657) has died(134,350)
ActivityManager: cleanUpApplicationRecord -- 8657

**Comment by Vladlukhanin** [comment]
Hi, @RacknerFrank 
We are solving this issue.
Here is prepared [pull-request](https://github.com/QuickBlox/quickblox-javascript-sdk/pull/331) and I hope that this PR will be helpful for you.
This update will go to the next release, but you can try it - `npm install git+https://github.com/QuickBlox/quickblox-javascript-sdk.git#dev.chat_stability_improvements`. Check it and let us know if there are some problems will be.

**Comment by RacknerFrank** [comment]
Thanks, that branch does seem better. It definitely isn't crashing as often as it was before, but after waiting awhile, the app did crash again with this error:

System.err: com.tns.NativeScriptException:
System.err: Calling js method onMessage failed
System.err:
System.err: TypeError: Cannot read property 'indexOf' of null
System.err: File: "file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js, line: 2348, column: 19
System.err:
System.err: StackTrace:
System.err:     Frame: function:'getIdFromNode', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js', line: 2348, column: 20
System.err:     Frame: function:'ChatProxy._onPresence', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/quickblox/src/modules/chat/qbChat.js', line: 483, column: 31

**Comment by datanotion** [comment]
Thanks for pointing out that PR Vlad.  Now that it has been merged, is there another PR or branch that resolves the new issue that @RacknerFrank pointed out?  We're still seeing it randomly pop up.  Thank you!

**Comment by Vladlukhanin** [comment]
@RacknerFrank , @datanotion , I have tried to look the problem, but have not met this issue.
Could you guys show some reproduction steps?

**Comment by datanotion** [comment]
Yes, we will try to figure out how to replicate this.  So far we have not found a pattern.  Give us a few days to try some different things. Thank you @Vladlukhanin !

**Comment by datanotion** [comment]
Hello @Vladlukhanin!  A quick update: we are still experiencing this, but have still not been able to find a solid replication pattern - its just happens randomly.  It certainly has to do with the app sleeping and waking - so its possible it's happening during reconnection or before it has a chance to reconnect.

Here is the error report we are getting from Sentry, not sure if it has anything new in it other than what @RacknerFrank mentioned above.

https://sentry.io/share/issue/f0e2d292db71426e9834b70cfa206a53/

We are continuing to try to find exact steps to replicate, and will report back if so.

We also have a Pro ticket open on assist.quickblox.com (# 53233) if you'd like us to move this conversation there.
