### ISSUE TITLE
Could not login to Chat service.

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-javascript-sdk#341]
Hi supporter,

I am having a problem on javascript SDK. I am using quickblox version:
/* QuickBlox JavaScript SDK - v2.3.3 - 2016-10-07 */

My script code:

WebRTCDesktop.prototype.login = function (user, successCallback, failureCallback) {
    var self = this;
    QB.chat.connect({
        jid: QB.chat.helpers.getUserJid(user.ID, self.QBApp.appID),
        password: user.password
    }, function (err, res) {
        if (err !== null) {
            failureCallback(err);
        } else {
            successCallback();
        }
    });
};
 The problem is:

        + COULD login with same account on some device/network.
        + COULD NOT login on some device/network

I don't know why but when i could not login i will receive an error message with code: 422.

Could you please tell me how to resolve it?

BR,
William Tran.

**Comment by williamtran1988** [comment]
The issue is moved to iOS sdk

https://github.com/QuickBlox/quickblox-ios-sdk/issues/1072

**Comment by VishlDeveloper** [comment]
how to merge quick Blox chat SDK with audio-video call

**Comment by ghost** [comment]
@VishlDeveloper hello, please clarify if you mean creating an application with chat and video calling functionalities. You can refer to the documentation:
https://docs.quickblox.com/docs/js-quick-start
If you have any specific question, I will be happy to help you
