### ISSUE TITLE
data channel

### ISSUE THREAD

**Issue by db2crush** [QuickBlox/quickblox-javascript-sdk#343]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
window 
chrome 66.0.3359.181 
latest javascript sdk

**Did this work before?**
no

**Expected behavior**
use data channel

**Any others comments?**
How to use data channel by QB ?
Does any way or method or API to use WebRTC datachannel ?

thanks :)

**Comment by vadimkhmyrovqb** [comment]
@runningo sorry for a late response.
Quickblox does support WebRTC. Please check this guide for more information:
https://quickblox.com/developers/Sample-webrtc-web#Browsers_support_of_WebRTC
