### ISSUE TITLE
How to destroy app session?

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-javascript-sdk#349]
Hi All,

Could you please tell me how to destroy app session when i logout? 

Thanks and regards,
William Tran.

**Comment by vadimkhmyrovqb** [comment]
Hi @williamtran1988 
The session destroys itself after 2 hours.
To force destroy a session, check this example request:

curl -X DELETE \
-H "QuickBlox-REST-API-Version: 0.1.0" \
-H "QB-Token: 8b75a6c7191285499d890a81df4ee7fe49bc732a" \
https://api.quickblox.com/session.json

(from Quickblox documentation: https://quickblox.com/developers/Authentication_and_Authorization#API_Session_Destroy )
