### ISSUE TITLE
Could not make a call

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-javascript-sdk#351]
I am facing the problem when i re-initialization Quickblox again

![screen shot 2018-07-24 at 4 57 30 pm](https://user-images.githubusercontent.com/22092643/43131262-cf86b96e-8f62-11e8-8a4c-3a4d4e9b49f8.png)

It will not happen if i do not init QB again. (Why do i need to re-init, because i support dynamic configuration QuickBlox app).

Are there anybody know how to resolve this issue?

**Comment by vadimkhmyrovqb** [comment]
@williamtran1988 please provide steps to reproduce the issue.

**Comment by vivekdoshi2** [comment]
**How we init QuickBlox :**
Generating token from server side ( node js ) , then init QuickBlox with token and app id

**Step to produce issue :**
Serving angular project on host:port eg. http://192.168.15.100:4200 ( local server )
Now if me and my colleague opens the url and login with same user and init Quickblox then it throws error

**Error :**

```
TypeError: Cannot read property 'ondevicechange' of undefined
    at new u (quickblox.min.js:1)
    at s.init (quickblox.min.js:1)
    at quickblox.service.ts:132
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3824)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)
```

> at quickblox.service.ts:132 // This is the line where I am inited Quickblox

`QB.init(token, appId , null , config);`

**Comment by sanjeet-iws** [comment]
> **How we init QuickBlox :**
> Generating token from server side ( node js ) , then init QuickBlox with token and app id
> 
> **Step to produce issue :**
> Serving angular project on host:port eg. http://192.168.15.100:4200 ( local server )
> Now if me and my colleague opens the url and login with same user and init Quickblox then it throws error
> 
> **Error :**
> 
> ```
> TypeError: Cannot read property 'ondevicechange' of undefined
>     at new u (quickblox.min.js:1)
>     at s.init (quickblox.min.js:1)
>     at quickblox.service.ts:132
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
>     at Object.onInvoke (core.js:3824)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
>     at zone.js:872
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:3815)
> ```
> 
> > at quickblox.service.ts:132 // This is the line where I am inited Quickblox
> 
> `QB.init(token, appId , null , config);`

Same issue with me. 
Any solution for it? 

I'm facing this issue from version 2.12.0 and on 2.11.0 it is working fine. 
One more thing, code is working on ubuntu but not on windows. Whereas 2.11.0 is working on all systems.

**Comment by vivekdoshi2** [comment]
@sanjeet-iws ,

No, still having this issue. Have a create a new ticket #378
