### ISSUE TITLE
Ability to download image

### ISSUE THREAD

**Issue by Glebasty8** [QuickBlox/quickblox-javascript-sdk#352]
I am generating a download link with help of function QB.content.privateUrl(uid) and I want to give opportunity for user to download this file.
![image](https://user-images.githubusercontent.com/33228450/43322803-6fa9acf6-91b8-11e8-9e50-5514029666bd.png)

**Comment by vadimkhmyrovqb** [comment]
@Glebasty8 Was the file created private or public? This problem can occur if the file was created as public and you attempt to create a private link.

**Comment by Glebasty8** [comment]
@vadimkhmyrovqb its public file. So how to download this file by this link? Is it possible?

**Comment by vadimkhmyrovqb** [comment]
@Glebasty8 If the file was uploaded as public, try this method: QB.content.publicUrl(uid)

**Comment by Glebasty8** [comment]
@vadimkhmyrovqb ok thanks I will try.
