### ISSUE TITLE
Cannot access to Quickblox

### ISSUE THREAD

**Issue by mrhocuong** [QuickBlox/quickblox-javascript-sdk#354]
Hi everyone,
I was pulling the project then change the config (AppId, AuthKey, AuthSecet) but it not working.
With default config, I can log in and chat but with my config, I cannot. 

The first request to get the application session is done, I got the session token but the login request will throw the error 401 Auth Fail.

Can someone help me to solve this issue? I was trying to research on StackOverflow but don't see any issues like that.
Thanks.

![image](https://user-images.githubusercontent.com/12780298/43815451-ed5ce614-9af9-11e8-859e-febf35e7ab15.png)

**Comment by vadimkhmyrovqb** [comment]
@mrhocuong please check the following article in Quickblox documentation:
https://quickblox.com/developers/Authentication_and_Authorization#Request
