### ISSUE TITLE
NPM Install Not Working Version 2.7.0 

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-javascript-sdk#356]
**Environment details**
SDK Version 2.7.0

**Did this work before?**
No Idea

**Expected behavior**
Library should be installed

**Actual behavior**
Library should work

**Steps to reproduce the behavior**
Install npm in React App
`
npm install quickblox@2.7.0`

**Screenshots**

<img width="1053" alt="screen shot 2018-09-10 at 3 32 11 pm" src="https://user-images.githubusercontent.com/204423/45292772-a14b3e80-b50f-11e8-9db4-58a5f9d98a32.png">
<img width="1058" alt="screen shot 2018-09-10 at 3 32 22 pm" src="https://user-images.githubusercontent.com/204423/45292774-a14b3e80-b50f-11e8-98d5-ff48d993d259.png">

**Comment by vadimkhmyrovqb** [comment]
Hi @itsaboutcode could you test it with SDK version 2.12.2 and let me know if it works as expected?
