### ISSUE TITLE
QB WebRTCClient returns old reference to _instance event after disconnecting from it

### ISSUE THREAD

**Issue by nileskh16** [QuickBlox/quickblox-javascript-sdk#358]
**Environment details**

I have been using Quickblox library for enabling the Audio and Video web calls over WebRTC in our application but I am facing one issue. We are trying to open the chat modal and every time we close the modal, we are disconnecting the QB chat proxy. However, if we are trying to open the same modal again, the WebRTCClient is somehow persisting in the system and it returns the old reference of the **__instance** which stores null web socket. Therefore, all succeeding communication is failing due to null web socket. 
- Operating System: Windows 10, Ubuntu LTS 18.02
- Browser: Google Chrome 69.0.3497.100

**Did this work before?**
Unfortunately, it never worked before.

**Expected behavior**
Ideally, it should clean the WebRTCClient instance by flushing old references while disconnecting from the chat proxy. Or there should be some method present to put **__instance** back to its place i.e. make it null.

**Actual behavior**
This is not happening anyway in the Javascript SDK. Please, help me in this particular context.

**Comment by vadimkhmyrovqb** [comment]
@nileskh16 You can try to extend WebRTCClient with a method which will set __instance to null like this:
WebRTCClient.prototype.nullify = function ()
{ WebRTCClient.__instance = null; }
;
And call it after disconnection.
