### ISSUE TITLE
[QBWebRTC]: 'setRemoteSessionDescription' error: OperationError: Failed to parse SessionDescription. null Expect line: v=

### ISSUE THREAD

**Issue by binita12345** [QuickBlox/quickblox-javascript-sdk#361]
Hello,
I am getting Error: 'setRemoteSessionDescription' error: OperationError: Failed to parse SessionDescription. null Expect line: v= because of that i am not able to call AcceptCallListener.
Please, help me how to resolve this 'setRemoteSessionDescription' error through code.

Environment details
(Operating system, browser information, SDK version)
Mac
Chrome
SDK:^2.12.0

Did this work before?
No, it is not working already.

Expected behavior
Should not get setRemoteSessionDescription

Actual behavior
getting setRemoteSessionDescription so once outgoing call is done and accept the call from opponent side then after there is not getting acceptCallListener response and getting setRemoteSessionDescription on opponent side.

**Comment by binita12345** [comment]
![screen shot 2018-11-23 at 10 30 52 am](https://user-images.githubusercontent.com/23699891/48929072-2ccb4d80-ef0b-11e8-9f22-cc93091aa5ff.png)

**Comment by vadimkhmyrovqb** [comment]
Hi @binita12345 Please provide detailed steps to reproduce this issue.
