### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided

### ISSUE THREAD

**Issue by mimrank** [QuickBlox/quickblox-javascript-sdk#364]
*Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.*

**Environment details**
*Browser, IOS, Android App, Ionic, cordova*

**Did this work before?**
Yes.

**Expected behavior**
To work video calling

**Actual behavior**
Not start video calling at Ionic app side.

**Logs**
*Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

at WebRTCSession.attachMediaStream (quickblox2.4.0.min.js:86327)
at quickblox2.4.0.min.js:86306

WebRTCSession.attachMediaStream @ quickblox2.4.0.min.js:86327
(anonymous) @ quickblox2.4.0.min.js:86306
*

**Comment by vadimkhmyrovqb** [comment]
@mimrank Could you try it with SDK version 2.12.2 ?

**Comment by mimrank** [comment]
> @mimrank Could you try it with SDK version 2.12.2 ?

currently using quickblox2.4.0 with cordova plugin. 

let we update it's SDK version.

**Comment by mimrank** [comment]
> @mimrank Could you try it with SDK version 2.12.2 ?

Can you please share this video integration with ionic 3+ ? any sample or any guide or documents?

**Comment by duyetnk** [comment]
hi @mimrank 
i have the same issue, i integrated quickblox with ionic 3
did you make it work ?

**Comment by duyetnk** [comment]
i tried version 2.12.2 and it worked :)

**Comment by mimrank** [comment]
> hi @mimrank
> i have the same issue, i integrated quickblox with ionic 3
> did you make it work ?

latest version work with android but not iOS. For iOS we use 2.4.

**Comment by duyetnk** [comment]
> latest version work with android but not iOS. For iOS we use 2.4.

Why doesn't the quickblox team fix it?

**Comment by ghost** [comment]
Hello, dear @mimrank @duyetnk 

Thank you for contacting QuickBlox support.
In this ticket, you can see QB feedback about the current situation with supporting of Ionic framework: https://github.com/QuickBlox/quickblox-javascript-sdk/issues/368#

If you have any additional questions, please let us know.
