### ISSUE TITLE
Latest SDK (2.12.2) not working with ionic 3. 

### ISSUE THREAD

**Issue by mimrank** [QuickBlox/quickblox-javascript-sdk#368]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*
yes
**Environment details**
*(Operating system, browser information, SDK version)*
Browser, IOS, Android App, Ionic, cordova

**Did this work before?**
Yes.

**Expected behavior**
To work video calling with voice and video.

**Actual behavior**
On web I'm not listen voice of other person.
Also on other user (Ionic Mobile App) not listen and view my video.

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*
no error on both web and mobile app console.

**Any others comments?**
Hi,  
updated version (2.12.2) not work on ionic. we try to make a video call from web (Safari, chrome) to Mobile App (Ionic android, iOS). but now it's not showing video stream on mobile app and also no voice on both end (Web and Mobile)

**Comment by ghost** [comment]
Hello, dear @mimrank 

Thank you for contacting QuickBlox support.
We got a number of requests for Ionic from the users and we can see interest in this framework, but unfortunately, there is no ready to use solution for now.
According to internal QB client-side roadmap, team is going to prepare Ionic samples and documentation in Q3/Q4 of 2019.
We would like to point your attention that you have prioritized support via Customer Portal via Enterprise department section, as GitHub isn’t a best place to share QuickBlox SDK’s debug logs with client-side logic.

Thank you for understanding.
Always glad to help you.
