### ISSUE TITLE
Frequently Getting 502 Bad Gateway. Demo is not working too 

### ISSUE THREAD

**Issue by itsmeasadali** [QuickBlox/quickblox-javascript-sdk#369]
Frequently Getting 502 Bad Gateway. Demo is not working too.

It worked really well before. I was getting lots of 502 today. Now I have checked your demo. And that is getting 502 too from server. What's the issue ?

**Comment by ghost** [comment]
Hello, dear @areyasad 

Thank you for contacting QuickBlox support.
There was a temporary issue that caused some interruptions on Shared instance. This issue affected part of our Starter, Advanced and Pro plan users.
Reason: functionality update.
Currently, all works as expected.

Take our apologies for the temporary inconvenience.

If you have any additional questions, please let us know.
