### ISSUE TITLE
Is there a way to change group chat admin/owner

### ISSUE THREAD

**Issue by arme2401** [QuickBlox/quickblox-javascript-sdk#393]
From the documentation: "Only dialog's creator(owner) can remove any users from occupants_ids"

Is there a way to change the admin/owner of a group-chat?
The problem is, if the owner leaves the group, no one can remove users from the chat.

**Comment by ghost** [comment]
@arme2401 Hello,

This is Nikolay from QuickBlox support.

Unfortunately, it is not possible to change the dialog owner at this moment.

As an option, you can recreate a dialog.
