### ISSUE TITLE
NPM out of date

### ISSUE THREAD

**Issue by stevie-mayhew** [QuickBlox/quickblox-javascript-sdk#4]
Hi,

It appears the NPM repository mirror for this (https://www.npmjs.org/package/quickblox) is a few versions behind - currently its at 1.2.2 (which doesn't match any tags on this github?) Would it be possible to get this updated?

Cheers

**Comment by AndreyPovelichenko** [comment]
https://www.npmjs.com/package/quickblox

**Comment by stevie-mayhew** [comment]
Thanks @AndreyPovelichenko
