### ISSUE TITLE
In Iphone Safari browser loosing camera permission and video stream when we click on flip camera option in Quickblox JavaScript SDK

### ISSUE THREAD

**Issue by avinash-2021** [QuickBlox/quickblox-javascript-sdk#403]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
2.12.9 Javascript SDK

**Did this work before?** Working in android but not in iphone safari browser

**Expected behavior** When we flip camera we need to get the stream from the camera without loosing camera permissions

**Actual behavior** When we flip camera we need to get the stream from the camera but once I get access to back camera I am loosing permission to front camera even though when I am sending front camera device ID I am not getting access to camera and loosing video stream on both the sides

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
 Open javascript app in iphone safari and click on flip camera button to get rear camera and front camera access

**Any others comments?**

**Comment by ghost** [comment]
Hello, 

This is Nikolay from QuickBlox support.

According to my check, it is possible to use both device cameras (front/back) in the mobile browsers of both Android and IOS devices.
Also, the browsers should have the resolution to use device cameras, especially for IOS devices, it's a very important point for the correct working of this functionality.

Please let me know if you tried to use this method to switch the camera:
[https://docs.quickblox.com/docs/js-video-calling-advanced#switch-camera ](https://docs.quickblox.com/docs/js-video-calling-advanced#switch-camera )
