### ISSUE TITLE
Error in session.getUserMedia() trying to start a simple video session

### ISSUE THREAD

**Issue by virtualixst** [QuickBlox/quickblox-javascript-sdk#408]
Good day. I am trying to create a simple video call session as I have just been testing the platform.
There was a problem when creating the session with getUserMedia (), hopefully you can help me. The code is the following:

`$("body").append("<div id='videoTemporal' style='position: fixed; top:100px; left:0; width: 500px; height: 500px; background: white'></div>");`
`var session = QB.webrtc.createNewSession([chatContactId], QB.webrtc.CallType.VIDEO, null, {});`
`var mediaParams = {audio: true, video: { min: 320, ideal: 720, max: 1080 }, options: {muted: true, mirror: false}, elemId: "videoTemporal"};`
`session.getUserMedia(mediaParams, function (error, stream) {`
`if(error){`
`alert(error);`
`} else {`
`session.attachMediaStream('videoTemporal', stream);`
`}`
`});`

It is worth mentioning that I already created a user session at the beginning with which I already have a working text chat.

The version of the SDK used is 2.13.0.

The error message is:

In Chrome: **TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.**
In Firefox: **TypeError: URL.createObjectURL: Argument 1 is not valid for any of the 1-argument overloads.**

The debug:{mode:1} shows nothing in the console.

It is the first time that I use the platform, maybe I am doing something wrong. Thanks in advance for your collaboration.

**Comment by TarunNarula** [comment]
I am facing same issue - Any update on this ?

**Comment by virtualixst** [comment]
Hello friend, yes I solved the issue. The problem was that I was trying to put the local video inside a div (like other platforms that create a video element). I select a video element and everything is alright 👍
