### ISSUE TITLE
Error: There is no videoroom plugin instance

### ISSUE THREAD

**Issue by rahulconsagous** [QuickBlox/quickblox-javascript-sdk#426]
Showing error on web

<script src="https://unpkg.com/quickblox/quickblox.min.js"></script>
  <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
  <script src="[assets/video/quickblox-multiparty-video-conferencing-client-0.8.8.min.js](https://educationcloud.app/teachers/assets/video/quickblox-multiparty-video-conferencing-client-0.8.8.min.js)"></script>
const config = {
  server: "wss://...",
  debug: true, // optional
  iceServers: [], // optional
};
const client = new QBVideoConferencingClient(config);
    const joinParams = {
      roomId: content.dialog_id,
      userId: quickUserId,
      display: userInfo.name,
      onlyAudio: false,
      role: 'publisher',
      video: 'stdres',
    };
    client.join(joinParams).then( () => {
      console.log('joined successfully');
    }).catch( (error) => {
      console.log(error);
    })
![Screen Shot 2022-05-01 at 23 35 36](https://user-images.githubusercontent.com/84760088/166190222-eb91cef1-a65b-4fa3-8031-1a9a4ed86b7a.png)
;

**Comment by ghost** [comment]
@rahulconsagous Hello,
Unfortunately, I am not able to reproduce the issue on my end.
Please make sure that you followed our documentation, created a session, and attached the video conferencing plugin:
https://docs.quickblox.com/docs/js-video-conference
If the issue persists, please provide more detailed steps to reproduce and a sample app
