### ISSUE TITLE
i am not able to get call from web to mobile Or Mobile to web but web to web working fine 

### ISSUE THREAD

**Issue by gyanish77** [QuickBlox/quickblox-javascript-sdk#430]

**Comment by ghost** [comment]
Hello, please lemme know what SDKs you use for Mobile. 
You need to use the latest versions you can find here:
https://github.com/quickblox

Make sure that you use the latest version of the Javascript SDK:
https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.11

**Comment by gyanish77** [comment]
I am already using   "quickblox": "^2.13.11", the latest version of the Javascript SDK and in react native mobile app I use quickblox-react-native-sdk  0.5.0-beta facing issues please solve this issues

**Comment by gyanish77** [comment]
I am using ReactJS for the web and for mobile i use react native
