### ISSUE TITLE
Not ready for Node.js

### ISSUE THREAD

**Issue by aaronksaunders** [QuickBlox/quickblox-javascript-sdk#5]
from what I have read in the documentation, you state that this library can be used with node.js... it cannot because of the dependency on `FormData`.

https://github.com/QuickBlox/quickblox-javascript-sdk/blob/master/js/modules/qbData.js#L59

Is it possible that this will be addressed or should I just not use the library in node.js applications.

Thanks

**Comment by AndreyPovelichenko** [comment]
https://www.npmjs.com/package/quickblox
