### ISSUE TITLE
Content Type when uploading file to Custom Object

### ISSUE THREAD

**Issue by aaronksaunders** [QuickBlox/quickblox-javascript-sdk#7]
when uploading a file from a `FormData` object, the file that you have access to has no extension in some cases so quickblox is unable to determine the correct `content_type`. I see that there is a `content_type` returned after the object is created, is there a way explicitly set the content_type when creating the object?

**Comment by Vladlukhanin** [comment]
Hi! What is the format of the file you try upload?

**Comment by soulfly** [comment]
Also please provide the whole code how you use a FormData object

**Comment by soulfly** [comment]
Closing for now, didn't receive more details
