### ISSUE TITLE
application_id not set for session when using a token, calling with a token does not work

### ISSUE THREAD

**Issue by fc** [QuickBlox/quickblox-javascript-sdk#72]
When using a token to connect the application_id in getSession() is undefined.

In QB.init the call to setSession looks like this:

```
this.service.setSession({ token: appId });
```

Then later when calling `QB.webrtc.call(...)` it executes the following:

```
  params = {
    from: connection.jid,
    to: this.helpers.getUserJid(userId, this.service.getSession().application_id), // <-- it is undefined here
    type: 'headline',
    id: Utils.getBsonObjectId()
  };
```

When making a call the "to" attribute will look something like this in the debug output `12348092-undefined@chat.quickblox.com`

Workaround if you have this issue:

```
QB.init(token, false, false, QBConfig);
QB.service.getSession().application_id = your_app_id;
```

Two unrelated but minor issue:
1. quickblox.js is not in your current release when previously it was included.  It's nice to have.
2. I'm not 100% certain but if you call QB.init twice - let's say with a token first then afterward using key/secret it may lead to unexpected behavior.  Since QB is acting as a single instance perhaps it should throw an error if init executed more than once.

**Comment by fc** [comment]
Additionally... it should throw an exception in createSession if you are using a token which can lead to a confusing experience, refer to this http://stackoverflow.com/questions/34124381/questions-using-quickblox-javascript-sdk/

**Comment by soulfly** [comment]
Thanks for reporting this, 
will review and prepare a fix

**Comment by soulfly** [comment]
//1. quickblox.js is not in your current release when previously it was included. It's nice to have.

you can build it by yourself, just run 'grunt'

**Comment by soulfly** [comment]
Released 1.17.1 http://quickblox.com/developers/Javascript#Framework_changelog

**Comment by fc** [comment]
getSession().application_id is still undefined and doing a webrtc video call still does not work.

```
    to: this.helpers.getUserJid(userId, this.service.getSession().application_id), // <-- it is undefined here
```

This would probably fix it:

```
this.service.setSession({ token: appIdOrToken, application_id: authKeyOrAppId });
```

**Comment by soulfly** [comment]
Better to replace 

```
 this.helpers.getUserJid(userId, this.service.getSession().application_id)
```

with

```
var config = require('../qbConfig');
var appId = config.creds.appId;
```

**Comment by fc** [comment]
definitely, booya! 😀

**Comment by soulfly** [comment]
Here it is

https://github.com/QuickBlox/quickblox-javascript-sdk/commit/1bb46b537189ce6ea16f951a54940f0717238ff1
