### ISSUE TITLE
Chat Dialog search question

### ISSUE THREAD

**Issue by sgshawnblanchard** [QuickBlox/quickblox-javascript-sdk#9]
when using this call ` QB.chat.dialog.list({"type": 2}, function(err,response) ... `  I get the correct number of records back, but the following code does ` QB.chat.dialog.list({"unread_messages_count": 0}, function(err,response) ... ` returns all records instead of just the filtered ones ?   thanks

**Comment by soulfly** [comment]
it's not possible to filter by unread_messages_count because it's not a field of a dialog, we generate it dynamically

Anyway Will review this case
